Repository warp-drive-data/warp-drive, pull requests merged in 2018-08, with the labels that each got.

#5546 Serialize empty hasMany relationships
  addon/serializers/json-api.js
  tests/integration/serializers/json-api-serializer-test.js
Labels: towards-beta

#5560 Bump default scenario ember-source version.
  package.json
  yarn.lock
Labels: towards-beta

#5562 [BUGFIX] use internalModel promise if already loading
  addon/-legacy-private/system/relationships/state/belongs-to.js
  addon/-record-data-private/system/store.js
  tests/integration/relationships/belongs-to-test.js
Labels: Regression, towards-beta

#5567 [FEAT] enable external partner testing
  .travis.yml
  lib/scripts/test-external.js
  package.json
  yarn.lock
Labels: towards-beta

#5545 [FEAT] TrackableRequests for when async leakage is detected
  addon/-legacy-private/system/relationships/state/belongs-to.js
  addon/-legacy-private/system/relationships/state/has-many.js
  addon/-legacy-private/system/store.js
  addon/-private/system/store/common.js
  addon/-record-data-private/system/relationships/state/belongs-to.js
  addon/-record-data-private/system/relationships/state/has-many.js
  addon/-record-data-private/system/store.js
  tests/integration/store-test.js
  tests/unit/store/async-leak-test.js
Labels: towards-beta

#5582 [BUGFIX] Reference.reload should not cause sync-relationship assertion
  addon/-legacy-private/system/relationships/state/belongs-to.js
  addon/-legacy-private/system/relationships/state/has-many.js
  addon/-legacy-private/system/relationships/state/relationship.js
  tests/acceptance/relationships/belongs-to-test.js
  tests/acceptance/relationships/has-many-test.js
  tests/integration/records/create-record-test.js
  tests/integration/records/reload-test.js
Labels: lts-target

#5604 [BUGFIX] use xhr.textStatus not xhr.statusText
  addon/adapters/rest.js
Labels: lts-target

#5605 [FEAT] assert when methods are called on a destroyed store instance
  addon/-legacy-private/system/store.js
  addon/-record-data-private/system/store.js
  tests/unit/store/asserts-test.js
Labels: lts-target

#5619 [FEAT] deprecate instead of assert method calls on a destroyed store instance
  addon/-legacy-private/system/store.js
  addon/-record-data-private/system/store.js
  tests/unit/store/asserts-test.js
Labels: lts-target
