Repository warp-drive-data/warp-drive, pull requests merged in 2019-09, with the labels that each got.

#6433 Keeping beta up to date
  packages/adapter/addon/-private/utils/fetch.ts
Labels: bot_automerge

#6459 [TEST] ensure @ember-data/serializer package encapsulation
  azure-pipelines.yml
  package.json
  packages/-build-infra/src/stripped-build-plugins.js
  packages/-ember-data/tests/unit/utils-test.js
  packages/-serializer-encapsulation-test-app/.editorconfig
  packages/-serializer-encapsulation-test-app/.ember-cli
  packages/-serializer-encapsulation-test-app/.eslintignore
  packages/-serializer-encapsulation-test-app/.eslintrc.js
  packages/-serializer-encapsulation-test-app/.gitignore
  packages/-serializer-encapsulation-test-app/.template-lintrc.js
  packages/-serializer-encapsulation-test-app/.travis.yml
  packages/-serializer-encapsulation-test-app/.watchmanconfig
  packages/-serializer-encapsulation-test-app/README.md
  packages/-serializer-encapsulation-test-app/app/app.js
  packages/-serializer-encapsulation-test-app/app/components/.gitkeep
  packages/-serializer-encapsulation-test-app/app/controllers/.gitkeep
  packages/-serializer-encapsulation-test-app/app/helpers/.gitkeep
  packages/-serializer-encapsulation-test-app/app/index.html
  packages/-serializer-encapsulation-test-app/app/models/.gitkeep
  packages/-serializer-encapsulation-test-app/app/resolver.js
  packages/-serializer-encapsulation-test-app/app/router.js
  packages/-serializer-encapsulation-test-app/app/routes/.gitkeep
  packages/-serializer-encapsulation-test-app/app/styles/app.css
  packages/-serializer-encapsulation-test-app/app/templates/application.hbs
  packages/-serializer-encapsulation-test-app/app/templates/components/.gitkeep
  packages/-serializer-encapsulation-test-app/config/environment.js
  packages/-serializer-encapsulation-test-app/config/optional-features.json
  packages/-serializer-encapsulation-test-app/config/targets.js
  packages/-serializer-encapsulation-test-app/ember-cli-build.js
  packages/-serializer-encapsulation-test-app/package.json
  packages/-serializer-encapsulation-test-app/public/robots.txt
  packages/-serializer-encapsulation-test-app/testem.js
  packages/-serializer-encapsulation-test-app/tests/helpers/.gitkeep
  packages/-serializer-encapsulation-test-app/tests/index.html
  packages/-serializer-encapsulation-test-app/tests/integration/.gitkeep
  packages/-serializer-encapsulation-test-app/tests/integration/smoke-test.js
  packages/-serializer-encapsulation-test-app/tests/test-helper.js
  packages/-serializer-encapsulation-test-app/tests/unit/.gitkeep
  packages/-serializer-encapsulation-test-app/vendor/.gitkeep
  packages/store/addon/-debug/index.js
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/relationships/state/belongs-to.ts
  packages/store/addon/-private/system/relationships/state/has-many.ts
  packages/store/index.js
  yarn.lock
Labels: changelog:cleanup, changelog:test, target:canary, 🌲 Project Trim 🌲

#6390 [DEPRECATION] RFC-522 implementation to add deprecations
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
  packages/-ember-data/tests/unit/store/serializer-for-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/model.js
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/serializers.js
Labels: 🌲 Project Trim 🌲

#6451 [DOC serializer] implements MinimumSerializerInterface
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/adapter/addon/-private/index.js
  packages/adapter/addon/-private/utils/serialize-into-hash.js
  packages/adapter/addon/json-api.js
  packages/adapter/addon/rest.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/identity-map.ts
  packages/store/addon/-private/system/internal-model-map.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
  packages/store/addon/-private/ts-interfaces/utils.ts
Labels: changelog:doc, target:beta, target:canary, target:lts-3-12, target:release, 🌲 Project Trim 🌲

#6502 [TEST BETA CANARY] Test against Ember 3.12 LTS
  .travis.yml
  azure-pipelines.yml
  packages/-ember-data/config/ember-try.js
Labels: changelog:chore, target:beta, target:canary

#6521 [CHORE] fully encapsulate adapter package
  packages/-adapter-encapsulation-test-app/package.json
  packages/-adapter-encapsulation-test-app/tests/integration/smoke-test.js
  packages/adapter/addon/error.js
  packages/adapter/package.json
  packages/serializer/addon/json.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/model.js
  packages/store/index.js
  packages/store/package.json
Labels: 🌲 Project Trim 🌲

#6478 [CHORE]: move Model and related to @ember-data/model
  packages/model/addon/-private/index.ts
  packages/model/addon/-private/model.js
  packages/model/addon/index.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/system/schema-definition-service.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/index.ts
Labels: 🌲 Project Trim 🌲
