Repository warp-drive-data/warp-drive, pull requests merged in 2019-10, with the labels that each got.

#6539 [TEST] serialize test for serializer encapsulation side quest
  packages/-serializer-encapsulation-test-app/tests/integration/serialize-test.js
Labels: 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6533 [CHORE] Cleanup ESLint config
  .eslintignore
  .eslintrc.js
Labels: CI

#6526 [CHORE] Configure @typescript-eslint for linting TypeScript files
  .eslintrc.js
  .github/workflows/main.yml
  .travis.yml
  azure-pipelines.yml
  bin/lint-changed-js
  package.json
  packages/-ember-data/tests/integration/identifiers/cache-test.ts
  packages/-ember-data/tests/integration/identifiers/new-records-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/adapter/addon/-private/utils/determine-body-promise.ts
  packages/adapter/addon/-private/utils/serialize-query-params.ts
  packages/model/addon/index.ts
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/relationship-meta.ts
  packages/store/addon/-private/system/relationships/state/create.ts
  packages/store/addon/-private/system/relationships/state/relationship.ts
  packages/store/addon/-private/system/request-cache.ts
  packages/store/addon/-private/system/schema-definition-service.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/addon/-private/ts-interfaces/record-data-record-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
  packages/store/addon/-private/utils/promise-record.ts
  packages/store/types/@ember/array/index.d.ts
  packages/store/types/@ember/ordered-set/index.d.ts
  packages/store/types/@ember/polyfills/index.d.ts
  packages/store/types/@ember/runloop/index.d.ts
  packages/store/types/ember/index.d.ts
  yarn.lock
Labels: CI

#6530 [TEST] deleteRecord test for serializer encapsulation side quest
  packages/-serializer-encapsulation-test-app/tests/integration/delete-record-test.js
Labels: 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6531 [TEST] Get a simple fastboot smoke test working
  .github/workflows/main.yml
  .travis.yml
  azure-pipelines.yml
  package.json
  packages/-fastboot-test-app/.editorconfig
  packages/-fastboot-test-app/.ember-cli
  packages/-fastboot-test-app/.gitignore
  packages/-fastboot-test-app/.template-lintrc.js
  packages/-fastboot-test-app/.watchmanconfig
  packages/-fastboot-test-app/README.md
  packages/-fastboot-test-app/app/adapters/application.ts
  packages/-fastboot-test-app/app/app.ts
  packages/-fastboot-test-app/app/config/environment.d.ts
  packages/-fastboot-test-app/app/helpers/.gitkeep
  packages/-fastboot-test-app/app/index.html
  packages/-fastboot-test-app/app/models/.gitkeep
  packages/-fastboot-test-app/app/models/person.js
  packages/-fastboot-test-app/app/resolver.ts
  packages/-fastboot-test-app/app/router.ts
  packages/-fastboot-test-app/app/routes/.gitkeep
  packages/-fastboot-test-app/app/routes/index.js
  packages/-fastboot-test-app/app/serializers/application.ts
  packages/-fastboot-test-app/app/styles/app.css
  packages/-fastboot-test-app/app/templates/.gitkeep
  packages/-fastboot-test-app/app/templates/application.hbs
  packages/-fastboot-test-app/app/templates/index.hbs
  packages/-fastboot-test-app/config/environment.js
  packages/-fastboot-test-app/config/optional-features.json
  packages/-fastboot-test-app/config/targets.js
  packages/-fastboot-test-app/ember-cli-build.js
  packages/-fastboot-test-app/package.json
  packages/-fastboot-test-app/public/robots.txt
  packages/-fastboot-test-app/testem.js
  packages/-fastboot-test-app/tests/fastboot/index-test.js
  packages/-fastboot-test-app/tests/helpers/.gitkeep
  packages/-fastboot-test-app/tests/index.html
  packages/-fastboot-test-app/tests/integration/.gitkeep
  packages/-fastboot-test-app/tests/test-helper.js
  packages/-fastboot-test-app/tests/unit/.gitkeep
  packages/-fastboot-test-app/tsconfig.json
  packages/-fastboot-test-app/types/fastboot-test-app/index.d.ts
  packages/-fastboot-test-app/types/global.d.ts
  packages/-fastboot-test-app/vendor/.gitkeep
  packages/-model-encapsulation-test-app/.eslintrc.js
  packages/debug/package.json
  packages/record-data/package.json
  yarn.lock
Labels: CI, changelog:test

#6547 [CHORE ci] Remove Azure Pipelines configuration
  azure-pipelines.yml
Labels: CI

#6551 [CHORE ci] Add Ember LTS 3.12 to GitHub Actions test matrix
  .github/workflows/main.yml
Labels: CI, changelog:chore, target:beta, target:canary, target:release

#6592 chore(ci): Increase browser start timeout
  packages/-ember-data/testem.js
Labels: changelog:chore, target:canary

#6586 [BUGFIX links] relationship setup for link fetch should batch
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/store/finders.js
Labels: changelog:bugfix, target:beta, target:canary, target:lts-3-12, target:lts-3-8, target:release

#6575 [FIX DOCS] cleanup serializer documentation
  packages/adapter/addon/index.js
  packages/serializer/addon/index.js
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
Labels: changelog:bugfix, changelog:doc, target:beta, target:canary, target:lts, target:lts-3-12, target:release

#6606 [FEAT links] ensures full links object support for relationships
  packages/-build-infra/src/features.js
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/integration/adapter/record-persistence-test.js
  packages/-ember-data/tests/integration/relationships/relationship-links-test.js
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
  packages/canary-features/package.json
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/addon/-private/relationships/state/relationship.ts
  packages/store/addon/-private/system/many-array.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/promise-proxies.js
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/system/store/finders.js
Labels: changelog:feat, target:canary

#6568 [BUGFIX release] Enable `store.createRecord` in FastBoot
  packages/-fastboot-test-app/app/router.ts
  packages/-fastboot-test-app/app/routes/person/new.js
  packages/-fastboot-test-app/app/templates/person/new.hbs
  packages/-fastboot-test-app/package.json
  packages/-fastboot-test-app/tests/fastboot/person/new-test.js
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
  packages/store/types/fastboot/index.d.ts
Labels: changelog:bugfix, target:beta, target:canary, target:release
