Repository warp-drive-data/warp-drive, pull requests merged in 2019-07, with the labels that each got.

#6059 [CHORE] RFC-0329 - adding deprecation about using evented in ember-data
  packages/-ember-data/tests/helpers/deprecated-test.js
  packages/-ember-data/tests/integration/lifecycle-hooks-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/merge-test.js
  packages/store/addon/-private/system/deprecated-evented.js
  packages/store/addon/-private/system/many-array.js
  packages/store/addon/-private/system/model/errors.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/model.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/record-arrays/record-array.js
Labels: code-review

#6231 Use @ember-data/canary-features/default-features module as single source of truth for feature flags
  packages/-build-infra/package.json
  packages/-build-infra/src/features.js
  packages/canary-features/addon/default-features.js
  packages/canary-features/addon/index.js
  yarn.lock
Labels: internal

#6236 Make canary features tests work on Windows
  azure-pipelines.yml
  packages/-ember-data/package.json
Labels: internal

#6244 chore: eliminate dead code
  packages/store/addon/-private/system/store.js
Labels: code-review

#6245 chore: eliminate store._getInternalModelForRecordData
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/store.js
Labels: code-review

#6239 chore: convert store to ts
  packages/-ember-data/addon/store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/relationship-meta.ts
  packages/store/addon/-private/system/relationships/state/create.ts
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/package.json
  packages/store/tsconfig.json
  packages/store/types/@ember/utils/index.d.ts
  packages/store/types/ember/index.d.ts
Labels: code-review, ts-review

#6161 chore: refactor promiseRecord
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/utils/promise-record.ts
Labels: code-review, ts-review

#6246 chore: encapsulate InternalModel usage
  packages/-ember-data/tests/unit/model-test.js
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/coerce-id.ts
  packages/store/addon/-private/system/internal-model-map.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/model.js
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data-json-api.ts
Labels: code-review

#6247 [RFC 403] Identifiers Infra
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/canary-features/addon/default-features.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/identifiers/is-stable-identifier.ts
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/identity-map.ts
  packages/store/addon/-private/system/internal-model-map.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/record-data.ts
  packages/store/addon/-private/system/relationships/state/belongs-to.ts
  packages/store/addon/-private/system/relationships/state/has-many.ts
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  packages/store/addon/-private/ts-interfaces/record-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
  packages/store/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/store/addon/-private/ts-interfaces/utils.ts
  packages/store/addon/-private/utils/is-non-empty-string.ts
Labels: code-review, ts-review

#6249 chore: refactor store to class
  package.json
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/adapter/queries-test.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
  yarn.lock
Labels: ts-review

#6272 [FEAT identifiers] adds flagged public API and integration tests
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/identifiers/record-identifier-for-test.ts
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/records/rematerialize-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/store/peek-record-test.js
  packages/-ember-data/tsconfig.json
  packages/canary-features/addon/default-features.js
  packages/canary-features/addon/index.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/coerce-id.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  packages/store/addon/-private/utils/has-valid-id.ts
  packages/store/addon/index.js
Labels: ts-review
