Repository warp-drive-data/warp-drive, pull requests merged in 2019-11, with the labels that each got.

#6661 [DOC] Close code block in the description
  packages/store/addon/-private/system/snapshot-record-array.js
Labels: Documentation

#6610 [BUGFIX] modelFor should return a stable ShimModelClass
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/shim-model-class.ts
  packages/store/addon/-private/system/schema-definition-service.ts
  packages/unpublished-model-encapsulation-test-app/app/app.js
  packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js
Labels: ts-review

#6628 [CHORE] test fixes for deprecations, enables asserting all deprecations
  packages/-ember-data/tests/helpers/deprecated-test.js
  packages/-ember-data/tests/helpers/qunit-asserts/assert-assertion.ts
  packages/-ember-data/tests/helpers/qunit-asserts/assert-deprecation.ts
  packages/-ember-data/tests/helpers/qunit-asserts/assert-warning.ts
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/lifecycle-hooks-test.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/test-helper.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/-ember-data/tests/unit/store/serializer-for-test.js
Labels: CI, 🌲 Project Trim 🌲

#6660 Backport #6472: Use GitHub Actions for CI (#6472)
  .github/workflows/main.yml
  packages/-ember-data/config/ember-try.js
Labels: CI

#6676 [CHORE] Improve output and fail test for Asset size Check
  .github/workflows/asset-size-check.yml
  bin/asset-size-tracking/generate-diff.js
  bin/asset-size-tracking/src/library.js
Labels: CI, changelog:chore, target:canary, 🌲 Project Trim 🌲

#6700 Backport #6692 to 3.13
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
Labels: changelog:bugfix, target:release

#6683 [BUGFIX RELEASE BETA CANARY] Fastboot issues
  packages/adapter/addon/rest.js
  packages/unpublished-fastboot-test-app/tsconfig.json
  tsconfig.json
Labels: ts-review

#6707 Keeping beta up to date
  packages/adapter/addon/rest.js
  packages/unpublished-fastboot-test-app/tsconfig.json
  tsconfig.json
Labels: bot_automerge

#6702 [BREAKING BUGFIX] eliminate infrastructure for filter record arrays
  packages/-ember-data/tests/unit/store/asserts-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/record-array-manager.js
Labels: changelog:bugfix, changelog:cleanup, target:canary

#6673 [BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldReloadAll
  packages/store/addon/-private/system/core-store.ts
  packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js
Labels: changelog:bugfix, changelog:test, target:canary, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6718 [BUGFIX TEST] reloading tests for adapter encapsulation side quest - shouldBackgroundReloadRecord
  packages/store/addon/-private/system/core-store.ts
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js
Labels: changelog:bugfix, changelog:test, target:canary, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6726 [CHORE] turn off fingerprinting in the perf app
  packages/unpublished-relationship-performance-test-app/ember-cli-build.js
Labels: Relationship Refactor

#6631 Add TracerBench to unpublished-relationship-performance-test-app
  .github/workflows/relationship-performance-check.yml
  azure-pipelines.yml
  bin/relationship-performance-tracking/generate-analysis.sh
  bin/relationship-performance-tracking/head-vs-master.sh
  bin/relationship-performance-tracking/src/.gitignore
  bin/relationship-performance-tracking/src/har-remix.js
  bin/relationship-performance-tracking/src/trace.har
  bin/relationship-performance-tracking/src/tracerbench.js
  package.json
  packages/unpublished-relationship-performance-test-app/.gitignore
  packages/unpublished-relationship-performance-test-app/PERFORMANCE_BENCHMARKING.md
  packages/unpublished-relationship-performance-test-app/app/routes/application.js
  packages/unpublished-relationship-performance-test-app/tracerbench-results/.gitignore
  yarn.lock
Labels: CI, Relationship Refactor, changelog:test, target:canary

#6729 [CHORE] documentation for @ember-data/debug package
  packages/debug/addon/index.js
Labels: 🌲 Project Trim 🌲

#6599 Using a config to include ember-data/debug in the build
  packages/debug/index.js
Labels: changelog:feat, target:canary, 🌲 Project Trim 🌲

#6712 [CHORE] refactor: Remove runloop usage in integration tests for store/ find All module
  packages/-ember-data/tests/integration/store-test.js
Labels: changelog:test, target:canary, 🔌 Project Unplug 🔌

#6734 [CHORE] build speed improvements & docs path fix
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/-ember-data/yuidoc.json
  packages/debug/addon/index.js
Labels: CI, changelog:chore, target:canary

#6735 [TESTS] improve docs coverage
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/-ember-data/node-tests/fixtures/expected.js
Labels: changelog:test, target:canary, 🌲 Project Trim 🌲

#6736 [CHORE] delete unused infra
  package.json
  packages/-ember-data/addon/-private/features.js
  packages/-ember-data/addon/-private/index.js
  packages/canary-features/package.json
  packages/private-build-infra/config/in-progress-features.json
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/cli-flags.js
  packages/private-build-infra/src/stripped-build-plugins.js
  packages/store/addon/-debug/index.js
  yarn.lock
Labels: changelog:cleanup, target:canary, 🌲 Project Trim 🌲

#6738 [BUGFIX] only allow feature flag alterations in canary
  packages/private-build-infra/src/features.js
Labels: Feature, changelog:bugfix, target:beta, target:canary, target:lts, target:release

#6741 [DOC] Fix typo
  packages/model/addon/-private/errors.js
Labels: Documentation, changelog:doc, target:canary

#6742 Strip FeatureFlagged code in non canary builds
  packages/private-build-infra/src/features.js
Labels: Feature, changelog:bugfix, target:beta, target:canary, 🌲 Project Trim 🌲

#6746 [BUGFIX] ensure MandatorySetter does not trigger for modelName
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/store/addon/-private/system/schema-definition-service.ts
Labels: Bug, Octane, changelog:bugfix, target:beta, target:canary, target:lts-3-12, target:lts-3-8, target:release

#6749 [BUGFIX] ensure MandatorySetter does not trigger for modelName
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/store/addon/-private/system/store.ts
Labels: backport-lts

#6748 [BUGFIX] ensure MandatorySetter does not trigger for modelName
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/store/addon/-private/system/schema-definition-service.ts
Labels: backport-release

#6747 [BUGFIX] ensure MandatorySetter does not trigger for modelName
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/store/addon/-private/system/schema-definition-service.ts
Labels: backport-beta

#6752 [CHORE] feature flag reversal test
  .github/workflows/main.yml
  .travis.yml
  azure-pipelines.yml
  package.json
  packages/-ember-data/package.json
  packages/private-build-infra/src/features.js
Labels: CI, Feature, changelog:test

#6750 [BUGFIX lts-3-8] ensure MandatorySetter does not trigger for modelName
  addon/-private/system/store.js
  tests/integration/store/model-name-test.js
Labels: backport-lts

#6753 [CHORE] deactivate all but allowed-fail travis jobs
  .travis.yml
Labels: CI, changelog:chore

#6755 [TEST] mutations tests for adapter encapsulation side quest
  packages/model/addon/-private/errors.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/mutations-test.js
Labels: changelog:test, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6754 [TEST] queries tests for adapter encapsulation side quest
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/queries-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/reload-test.js
Labels: changelog:bugfix, changelog:test, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6767 [BUGFIX] fix detect usage for native class polymorphism
  packages/-ember-data/tests/integration/relationships/polymorphic-mixins-has-many-test.js
  packages/store/addon/-debug/index.js
Labels: Octane, changelog:bugfix, target:beta, target:lts-3-12, target:release

#6766 [CHORE issue-template] capture nested package deps in cli output
  .github/ISSUE_TEMPLATE.md
Labels: changelog:chore

#6763 [CHORE] rename Record to RecordInstance
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/addon/-private/ts-interfaces/record-instance.ts
Labels: changelog:chore

#6764 [CHORE] introduce static ModelSchema interface
  packages/store/addon/-private/system/model/shim-model-class.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
Labels: changelog:chore, ts-review, 🌲 Project Trim 🌲

#6775 Fix setting ID on Record Data from DS.Model
  packages/-ember-data/tests/unit/model-test.js
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
Labels: Bug, changelog:bugfix, target:beta, target:lts, target:lts-3-12, target:lts-3-8, target:release

#6779 [BUGFIX] Set IDs on Record Data when mutating DS Model (#6775)
  packages/-ember-data/tests/unit/model-test.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/record-data.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
Labels: backport-release

#6780 [BUGFIX] Set IDs on Record Data when mutating DS Model (#6775)
  packages/-ember-data/tests/unit/model-test.js
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
Labels: backport-beta

#6778 [BUGFIX] Set IDs on Record Data when mutating DS Model (#6775)
  packages/-ember-data/tests/unit/model-test.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/record-data.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
Labels: backport-lts

#6777 Set IDs on Record Data when mutating DS Model
  addon/-private/system/model/internal-model.js
  addon/-private/system/model/record-data.js
  tests/unit/model-test.js
Labels: backport-lts

#6782 Backport @babel/plugin-transform-block-scoping fix to 3.8.0
  package.json
  yarn.lock
Labels: backport-lts

#6789 [CHORE] Move -private/system/relationships/ext from store to model
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/relationships/ext.js
  packages/store/addon/-private/index.ts
Labels: changelog:chore, 🌲 Project Trim 🌲

#6787 [TEST] coalescing tests for adapter encapsulation side quest
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
Labels: changelog:test, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6798 [CHORE ts] type SnapshotRecordArray
  packages/store/addon/-private/system/record-arrays.ts
  packages/store/addon/-private/system/snapshot-record-array.ts
Labels: ts-review

#6799 [CHORE] refactor: Update tests for integration/adapter/query
  packages/-ember-data/tests/integration/adapter/queries-test.js
  packages/-ember-data/tests/integration/store-test.js
Labels: changelog:test, 🔌 Project Unplug 🔌

#6802 [CHORE] Move _modelForMixin to Model package
  packages/model/addon/-private/index.ts
  packages/model/addon/-private/system/model-for-mixin.ts
  packages/store/addon/-private/system/schema-definition-service.ts
Labels: changelog:chore, 🌲 Project Trim 🌲

#6797 [BUGFIX TEST] relationships tests for adapter enapsulation side quest
  packages/store/addon/-private/system/core-store.ts
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/belongs-to-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/has-many-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/test-helper.js
Labels: changelog:test, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6809 [BUGFIX] cleanup rollup warnings
  packages/-ember-data/index.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/record-data-for.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data-record-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
Labels: Build Infra, CI, changelog:bugfix

#6808 [FIX] improve tarball insertion
  bin/-tarball-info.js
  bin/test-external-partner-project.js
  package.json
Labels: CI, changelog:bugfix

#6820 [CHORE] improve comment bot
  .github/workflows/asset-size-check.yml
  .github/workflows/relationship-performance-check.yml
  bin/asset-size-tracking/src/post-comment.sh
  bin/relationship-performance-tracking/src/create-comment-text.js
Labels: CI, changelog:chore

#6818 [CHORE] cleanup build
  packages/debug/index.js
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/unpublished-test-infra/index.js
Labels: Build Infra, CI, changelog:chore

#6823 [FIX] comment-bot, partner-tests: use yarn lock-file when we can
  bin/asset-size-tracking/src/post-comment.sh
  bin/test-external-partner-project.js
  package.json
Labels: CI

#6824 [TEST] generateIdForRecord tests for adapter encapsulation side quest
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/generate-id-test.js
Labels: changelog:test, 🌲 Project Trim 🌲, 🌲 📦 Encapsulation & Interface Tests 📦 🌲

#6819 [CHORE] 11!
  bin/asset-size-tracking/generate-diff.js
  bin/asset-size-tracking/src/library.js
Labels: CI, changelog:chore

#6827 [BUGFIX] fix no-rollup check
  packages/-ember-data/index.js
  packages/private-build-infra/src/addon-build-config-for-data-package.js
Labels: CI, changelog:chore
