Repository warp-drive-data/warp-drive, pull requests merged in 2019-08, with the labels that each got.

#6325 Update to ember-qunit@4.5.1.
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  yarn.lock
Labels: internal

#6336 Keeping beta up to date
  packages/store/addon/-private/system/store.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
Labels: bot_automerge

#6338 [CHORE] Use model name instead of store in isPrimaryType
  packages/serializer/addon/rest.js
Labels: 🌲 Project Trim 🌲

#6221 [CHORE] Modernize integration/ tests and remove run loop calls
  packages/-ember-data/tests/integration/adapter/find-all-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/debug-adapter-test.js
  packages/-ember-data/tests/integration/inverse-test.js
  packages/-ember-data/tests/integration/lifecycle-hooks-test.js
  packages/-ember-data/tests/integration/polymorphic-belongs-to-test.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/integration/snapshot-test.js
Labels: 🌲 Project Trim 🌲

#6353 [CHORE tests] simplify setupStore registrations
  packages/-ember-data/addon/setup-container.js
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/serializers/json-serializer-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
Labels: 🌲 Project Trim 🌲

#6086 [FEAT serializers] clean up packages organization
  packages/-ember-data/addon/setup-container.js
  packages/-ember-data/app/serializers/-default.ts
  packages/-ember-data/app/serializers/-json-api.ts
  packages/-ember-data/app/serializers/-rest.ts
  packages/-ember-data/app/transforms/boolean.ts
  packages/-ember-data/app/transforms/date.ts
  packages/-ember-data/app/transforms/number.ts
  packages/-ember-data/app/transforms/string.ts
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/adapter/types/require/index.d.ts
  packages/serializer/tsconfig.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/store/serializers.js
  packages/store/index.js
  packages/store/types/require/index.d.ts
Labels: TRACK-packages, 🌲 Project Trim 🌲

#6347 [CHORE] Refactor away from `createStore` test helper
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/integration/record-arrays/peeked-records-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
  packages/-ember-data/tests/unit/debug-test.js
  packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
  packages/-ember-data/tests/unit/model/merge-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/-ember-data/tests/unit/store/create-record-test.js
  packages/-ember-data/tests/unit/store/has-model-for-test.js
  packages/-ember-data/tests/unit/store/unload-test.js
  packages/-ember-data/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js
Labels: 🌲 Project Trim 🌲

#6361 [CHORE tests] Replace setupStore for relationship integration tests
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/many-to-many-test.js
  packages/-ember-data/tests/integration/relationships/nested-relationship-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-one-test.js
  packages/-ember-data/tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/polymorphic-mixins-has-many-test.js
Labels: 🌲 Project Trim 🌲

#6368 [CHORE tests] eliminates usage of -rest serializer fallback in tests
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
Labels: 🌲 Project Trim 🌲

#6369 [CHORE tests] Added explicit -json-api serializer registration in tests
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/adapter/find-all-test.js
  packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
  packages/-ember-data/tests/integration/adapter/queries-test.js
  packages/-ember-data/tests/integration/client-id-generation-test.js
  packages/-ember-data/tests/integration/lifecycle-hooks-test.js
  packages/-ember-data/tests/integration/record-array-test.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/-ember-data/tests/unit/model-test.js
Labels: 🌲 Project Trim 🌲

#6370 [CHORE tests] eliminates remaining usage of -json-api serializer fallback in tests
  packages/-ember-data/tests/helpers/store.js
  packages/-ember-data/tests/integration/backwards-compat/non-dasherized-lookups-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/json-api-links-test.js
  packages/-ember-data/tests/integration/serializers/json-api-serializer-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/model/init-properties-test.js
Labels: 🌲 Project Trim 🌲
