Repository warp-drive-data/warp-drive, pull requests merged in 2019-12, with the labels that each got.

#6826 [CHORE] AssetSize check for both modern and IE11 builds
  .github/workflows/asset-size-check.yml
  bin/asset-size-tracking/generate-analysis.js
  bin/asset-size-tracking/generate-diff.js
  bin/asset-size-tracking/print-analysis.js
  bin/asset-size-tracking/src/create-comment-text.js
  bin/asset-size-tracking/src/library.js
Labels: CI, changelog:chore

#6828 [CHORE] Fix workflow and enable partner test debugging
  .github/workflows/main.yml
  bin/test-external-partner-project.js
  package.json
  packages/canary-features/addon/index.ts
Labels: CI

#6830 [CHORE] IE11 Testing
  .eslintrc.js
  .github/workflows/main.yml
  packages/-ember-data/testem.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/relationships/inverse-relationship-load-test.js
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/test-helper.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/request-cache.ts
  packages/store/addon/-private/ts-interfaces/utils/symbol.ts
  packages/unpublished-test-infra/addon-test-support/public-props.js
  packages/unpublished-test-infra/addon-test-support/todo.js
  packages/unpublished-test-infra/addon-test-support/watch-property.js
Labels: CI, changelog:chore, changelog:test

#6829 [BUGFIX] Octane: should not need to use get with model.id
  package.json
  packages/-ember-data/.ember-cli.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/acceptance/tracking-model-id-test.js
  packages/-ember-data/tests/dummy/config/optional-features.json
  packages/model/addon/-private/model.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/unpublished-relationship-performance-test-app/package.json
  tsconfig.json
  yarn.lock
Labels: Octane, changelog:bugfix

#6835 [CHORE] Use model name instead of store in isPrimaryType
  packages/serializer/addon/rest.js
Labels: changelog:chore, 🌲 Project Trim 🌲

#6836 [CHORE] Fix deprecation warnings; improve tooling
  packages/-ember-data/tests/test-helper.js
  packages/model/addon/-private/model.js
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
Labels: CI, changelog:chore

#6817 [CHORE] remove unneeded configs
  packages/-ember-data/tsconfig.json
  packages/adapter/tsconfig.json
  packages/debug/tsconfig.json
  packages/model/tsconfig.json
  packages/record-data/tsconfig.json
  packages/serializer/tsconfig.json
  packages/store/tsconfig.json
  packages/unpublished-test-infra/tsconfig.json
Labels: changelog:chore, ts-review

#6831 [BUGFIX TESTS] matrix tests for fastboot & ie11 w/jquery & fetch
  .github/workflows/main.yml
  azure-pipelines.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/adapter/addon/rest.js
  packages/unpublished-fastboot-test-app/config/ember-try.js
  packages/unpublished-fastboot-test-app/package.json
  yarn.lock
Labels: CI, changelog:test

#6840 [CHORE CI] fix timeout issues
  .github/workflows/main.yml
  packages/unpublished-fastboot-test-app/testem.js
Labels: CI, changelog:chore

#6847 [FIX CI] fetch full history for checks against master
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/relationship-performance-check.yml
Labels: CI, changelog:chore

#6814 [FEAT] Strip resolved Deprecations
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/canary-features/addon/default-features.ts
  packages/debug/index.js
  packages/model/addon/-private/model.js
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/create-version-module.js
  packages/private-build-infra/src/debug-macros.js
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/stripped-build-plugins.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/deprecated-evented.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/store/finders.js
  packages/unpublished-test-infra/addon-test-support/deprecated-test.js
  packages/unpublished-test-infra/index.js
Labels: CI, changelog:cleanup, changelog:feat, 🌲 Project Trim 🌲

#6859 [CHORE] document canary feature-flag infra
  CONTRIBUTING.md
  packages/canary-features/addon/default-features.ts
Labels: Feature, changelog:doc, 🌲 Project Trim 🌲

#6861 [DOCS] fix inclusion of docs for deprecation and canary features
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/yuidoc.json
  packages/private-build-infra/addon/index.ts
Labels: changelog:doc, 🌲 Project Trim 🌲

#6801 [CHORE ts] type Snapshot
  package.json
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  yarn.lock
Labels: changelog:chore, ts-review

#6873 [CHORE]: refactor: Remove usage of run function and use async/await syntax
  packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
Labels: changelog:chore, 🔌 Project Unplug 🔌

#6839 [DEPRECATION] deprecate belongsToReference.push accepting a model
  packages/-ember-data/tests/integration/references/belongs-to-test.js
  packages/private-build-infra/addon/current-deprecations.ts
  packages/store/addon/-private/system/references/belongs-to.js
Labels: changelog:deprecation, 🌲 Project Trim 🌲

#6644 [BUGFIX] fix single-table polymorphism when IDENTIFIERS is ON
  packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
  packages/store/addon/-private/identifiers/cache.ts
Labels: Bug, Feature, changelog:bugfix, target:beta

#6643 [FEAT docs] minimal adapter interface
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/adapter/addon/index.js
  packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
Labels: changelog:doc, target:canary, 🌲 Project Trim 🌲

#6926 [DOCS adapter] specify when findBelongsTo/findHasMany are used
  packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
Labels: changelog:doc, 🌲 Project Trim 🌲
