Repository warp-drive-data/warp-drive, pull requests merged in 2020-04, with the labels that each got.

#7103 [BUGFIX] dont use Ember.get on internals
  packages/-ember-data/tests/helpers/create-tracking-context.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/store/addon/-private/system/references/has-many.js
Labels: Octane, changelog:bugfix, target:beta, target:lts, target:release

#7109 clear relationships during delete
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/record-data/addon/-private/record-data.ts
Labels: changelog:bugfix, target:beta, target:lts, target:release, unload-apis

#7110 clear initialState after construction
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/model/addon/-private/system/many-array.js
Labels: changelog:bugfix, target:beta, target:lts, target:release

#6980 [CHORE]: refactor: Update record persisting tests to remove run loop usage
  packages/-ember-data/tests/integration/adapter/record-persistence-test.js
Labels: 🔌 Project Unplug 🔌

#7144 Release 3.17 backports
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/helpers/create-tracking-context.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/integration/store/store-creation-recursion-test.js
  packages/adapter/node-tests/blueprints/adapter-test.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/addon/-private/system/many-array.js
  packages/model/blueprints/model/index.js
  packages/model/node-tests/blueprints/model-test.js
  packages/model/package.json
  packages/private-build-infra/src/utilities/edition-detector.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/package.json
  packages/serializer/node-tests/blueprints/serializer-test.js
  packages/serializer/node-tests/blueprints/transform-test.js
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/references/has-many.js
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/src/node-test-helpers/setup-test-environment.js
  yarn.lock
Labels: backport-release

#7145 Beta 3.18 backports
  .github/workflows/main.yml
  azure-pipelines.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/helpers/create-tracking-context.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/integration/store/store-creation-recursion-test.js
  packages/adapter/node-tests/blueprints/adapter-test.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/addon/-private/system/many-array.js
  packages/model/blueprints/model/index.js
  packages/model/node-tests/blueprints/model-test.js
  packages/model/package.json
  packages/private-build-infra/src/utilities/edition-detector.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/package.json
  packages/serializer/node-tests/blueprints/serializer-test.js
  packages/serializer/node-tests/blueprints/transform-test.js
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/references/has-many.js
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/src/node-test-helpers/setup-test-environment.js
  yarn.lock
Labels: backport-beta

#7143 LTS 3.16 Backports
  .github/workflows/main.yml
  azure-pipelines.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/helpers/create-tracking-context.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/integration/store/store-creation-recursion-test.js
  packages/adapter/node-tests/blueprints/adapter-test.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/addon/-private/system/many-array.js
  packages/model/blueprints/model/index.js
  packages/model/node-tests/blueprints/model-test.js
  packages/model/package.json
  packages/private-build-infra/src/utilities/edition-detector.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/package.json
  packages/serializer/node-tests/blueprints/serializer-test.js
  packages/serializer/node-tests/blueprints/transform-test.js
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/references/has-many.js
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/src/node-test-helpers/setup-test-environment.js
  yarn.lock
Labels: backport-lts
