Repository warp-drive-data/warp-drive, pull requests merged in 2020-09, with the labels that each got.

#7315 [CI]: remove azure pipeline
  azure-pipelines.yml
Labels: CI

#7283 Chore: fix deprecate import path to @ember/debug
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
Labels: code-review

#7322 [Build]: disable esm cache
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/packages.js
Labels: Build Infra

#7323 [CI]: update github actions to v2
  .github/workflows/main.yml
Labels: CI

#7317 [Cleanup]: relationship push method does not need `initial` argument
  packages/model/addon/-private/system/many-array.js
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/create.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/addon/-private/relationships/state/relationship.ts
  packages/store/addon/-private/system/references/belongs-to.js
Labels: Cleanup

#7326 [Build]: disable esm cache (#7322)
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/packages.js
Labels: backport-lts

#7327 Release target: [Build]: disable esm cache (#7322)
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/packages.js
Labels: backport-release

#7329 [Build]: disable esm cache (#7322)
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/packages.js
Labels: backport-beta

#7285 Feature:Allow fetch to accept credentials
  packages/-ember-data/tests/unit/adapters/rest-adapter/fetch-options-test.js
  packages/adapter/addon/rest.js
Labels: Improvement

#7331 [Bug]: errors `remove` to accurately update in template
  packages/-ember-data/tests/integration/model-errors-test.ts
  packages/model/addon/-private/errors.js
Labels: Bug

#7332 [Chore]: Update finders-test to modern @ember-data imports
  packages/-ember-data/tests/unit/store/finders-test.js
Labels: changelog:chore

#7339 [Bug]: errors `remove` to accurately update in template
  packages/-ember-data/tests/integration/model-errors-test.ts
  packages/model/addon/-private/errors.js
Labels: backport-release

#7340 [Bug]: errors `remove` to accurately update in template
  .github/workflows/main.yml
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/tests/integration/model-errors-test.ts
  packages/model/addon/-private/errors.js
Labels: backport-beta

#7341 Add adapterOptions parameter to documentation of adapters query() and queryRecord() functions
  packages/adapter/addon/index.js
Labels: Documentation
