Repository warp-drive-data/warp-drive, pull requests merged in 2020-10, with the labels that each got.

#7337 [Debug]: improved debug msg instead of [object Object]
  packages/-ember-data/tests/integration/identifiers/cache-test.ts
  packages/store/addon/-private/identifiers/cache.ts
Labels: Improvement

#7336 [Docs]: `fields` user implementation
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/fetch-options-test.js
  packages/adapter/addon/rest.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/snapshot.ts
Labels: Documentation

#7330 [BUG]: Consume array access to autotrack hasMany
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/acceptance/tracking-model-id-test.js
  packages/model/addon/-private/system/many-array.js
Labels: Bug

#7230 [CHORE] najax deprecation when ember-fetch is also installed
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/adapter/addon/rest.js
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/store/addon/-private/index.ts
Labels: code-review, internal

#7126 Bugfix for wrong hasMany relationship state in scenario of sideposting with lid
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
Labels: Bug

#7347 [Backport]: beta 3.22.0-beta
  package.json
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/acceptance/tracking-model-id-test.js
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/adapter/addon/rest.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/addon/-private/system/many-array.js
  packages/model/package.json
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/addon/-private/index.ts
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: backport-beta

#7348 Update Changelog for v3.22.0
  CHANGELOG.md
Labels: target:release

#7349 Update Changelog for v3.23.0-beta.0
  CHANGELOG.md
Labels: target:beta

#7353 [Feature Flag]: RECORD_ARRAY_MANAGER_IDENTIFIERS: true
  packages/canary-features/addon/default-features.ts
Labels: 🌲 Project Trim 🌲

#7350 [Chore]: convert adapters to class syntax
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/unit/adapters/json-api-adapter/ajax-options-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/ajax-options-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
  packages/adapter/addon/index.js
  packages/adapter/addon/json-api.js
  packages/adapter/addon/rest.js
Labels: code-review

#7356 [Deps]: add `@ember/string` dependency in preparation of deprecation
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  yarn.lock
Labels: dependencies

#7359 [CI]: bump failure asset size to 75 bytes
  .github/workflows/asset-size-check.yml
  .github/workflows/nightly.yml
  .github/workflows/relationship-performance-check.yml
  bin/asset-size-tracking/generate-diff.js
Labels: CI

#7262 [CHORE]: Extract internalModel access to identifiers for Relationships
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/references/belongs-to-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/normalize-model-name.ts
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
Labels: code-review, 🌲 Project Trim 🌲
