Repository warp-drive-data/warp-drive, pull requests merged in 2020-03, with the labels that each got.

#7080 [BUGFIX] Fix #7015 - calling changedAttributes for non instantiated r…
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/store/addon/-private/system/snapshot.ts
Labels: target:beta, target:canary, target:release

#7083 Backport #7080 for beta
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/store/addon/-private/system/snapshot.ts
Labels: backport-beta

#7082 Backport #7080 for release
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/store/addon/-private/system/snapshot.ts
Labels: backport-release

#7084 [Backport] cleanup serializer documentation (#6575)
  packages/adapter/addon/index.js
  packages/serializer/addon/index.js
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
Labels: backport-lts

#7085 Backport #7020 for LTS
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/adapter/addon/index.js
  packages/store/addon/-private/system/store.ts
Labels: backport-lts
