Repository warp-drive-data/warp-drive, pull requests merged in 2020-01, with the labels that each got.

#6960 [BUGFIX] fix @ember-data/store import
  packages/-ember-data/addon/store.ts
  packages/-ember-data/tests/integration/store/package-import-test.js
  packages/store/addon/-private/system/ds-model-store.ts
Labels: changelog:bugfix, target:beta, target:canary, target:release

#6967 [FIX release] install local lint rules using link instead of a version
  package.json
  yarn.lock
Labels: changelog:bugfix, target:beta, target:release

#6970 fix release and install by using a link instead of a version (#6967)
  package.json
  yarn.lock
Labels: backport-beta

#6985 [FIX] RecordData is not a constructor
  .eslintignore
  packages/-ember-data/addon/index.js
  packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/unpublished-relationship-performance-test-app/app/routes/application.js
Labels: changelog:bugfix, release-blocker, target:beta, target:release

#6969 [CHORE] Drop support for Node 8
  package.json
  packages/-ember-data/package.json
  packages/adapter/node-tests/fixtures/addon/package/package.json
  packages/adapter/node-tests/fixtures/app/package/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/node-tests/fixtures/addon/package/package.json
  packages/model/node-tests/fixtures/app/package/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/node-tests/fixtures/addon/package/package.json
  packages/serializer/node-tests/fixtures/app/package/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
Labels: changelog:chore, target:beta

#6986 [BUFGIX BETA] dont run canary model tests in beta
  packages/unpublished-model-encapsulation-test-app/ember-cli-build.js
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js
Labels: backport-beta

#6968 remove IDENTIFIERS off branches
  packages/-ember-data/tests/integration/identifiers/cache-test.ts
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
  packages/-ember-data/tests/integration/identifiers/record-identifier-for-test.ts
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/records/rematerialize-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/belongs-to-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/has-many-test.js
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/queries-test.js
  packages/unpublished-serializer-encapsulation-test-app/app/services/store.js
Labels: Feature, changelog:chore, 🌲 Project Trim 🌲

#6966 turn on FULL_LINKS_ON_RELATIONSHIPS
  packages/canary-features/addon/default-features.ts
Labels: Feature, changelog:feat

#6987 [BUFGIX BETA] dont run feature flag model tests in beta
  packages/unpublished-model-encapsulation-test-app/ember-cli-build.js
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js
Labels: changelog:bugfix

#6927 [FIX] groupRecordsForFindMany should be optional
  packages/store/addon/-private/system/core-store.ts
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
Labels: changelog:bugfix, 🌲 Project Trim 🌲

#7003 beta backports
  .eslintignore
  package.json
  packages/-ember-data/addon/index.js
  packages/-ember-data/addon/store.ts
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/store/package-import-test.js
  packages/adapter/node-tests/fixtures/addon/package/package.json
  packages/adapter/node-tests/fixtures/app/package/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/node-tests/fixtures/addon/package/package.json
  packages/model/node-tests/fixtures/app/package/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/record-data/package.json
  packages/serializer/node-tests/fixtures/addon/package/package.json
  packages/serializer/node-tests/fixtures/app/package/package.json
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/app/routes/application.js
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
Labels: backport-beta

#7002 3.15.x release backports
  .eslintignore
  package.json
  packages/-ember-data/addon/store.ts
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
  packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/integration/records/delete-record-test.js
  packages/-ember-data/tests/integration/records/edit-record-test.js
  packages/-ember-data/tests/integration/records/reload-test.js
  packages/-ember-data/tests/integration/records/rematerialize-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/json-api-links-test.js
  packages/-ember-data/tests/integration/relationships/many-to-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/unload-new-record-test.js
  packages/-ember-data/tests/integration/serializers/embedded-records-mixin-test.js
  packages/-ember-data/tests/integration/serializers/json-api-serializer-test.js
  packages/-ember-data/tests/integration/serializers/json-serializer-test.js
  packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/-ember-data/tests/integration/store/package-import-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/relationships/belongs-to-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/-ember-data/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js
  packages/adapter/node-tests/blueprints/adapter-test.js
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/addon/-private/util.ts
  packages/model/node-tests/blueprints/model-test.js
  packages/model/package.json
  packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/record-data/package.json
  packages/serializer/node-tests/blueprints/serializer-test.js
  packages/serializer/node-tests/blueprints/transform-test.js
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/many-array.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-relationship-performance-test-app/app/routes/application.js
  yarn.lock
Labels: backport-release

#7020 Ensure adapters and serializers are destroyed upon store destruction.
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
Labels: lts-target, target:beta, target:release
