Repository warp-drive-data/warp-drive, pull requests merged in 2020-12, with the labels that each got.

#7363 [BUGFIX identifiers] Address issue with polymorphic findRecord
  packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
  packages/store/addon/-private/identifiers/cache.ts
Labels: changelog:bugfix, target:beta

#7378 [Deps]: ember-cli-typescript 4.0.0
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: dependencies

#7394 [Cleanup]: Remove RECORD_ARRAY_MANAGER_IDENTIFIERS
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/model/relationships/record-array-test.js
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/record-arrays/record-array.js
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/system/store/finders.js
Labels: Feature

#7393 [Cleanup]: Remove FULL_LINKS_ON_RELATIONSHIPS
  packages/-ember-data/tests/integration/relationships/relationship-links-test.js
  packages/model/addon/-private/system/many-array.js
  packages/model/addon/-private/system/promise-many-array.js
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/reference.ts
Labels: Feature

#7292 [DOC model] convert api examples to native classes/Octane
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/errors.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/many-array.js
  packages/model/addon/-private/system/model-for-mixin.ts
  packages/model/addon/index.ts
Labels: hacktoberfest-accepted

#7405 [DOC adapter] fix parent class invocation syntax
  packages/adapter/addon/-private/build-url-mixin.js
Labels: Documentation
