Repository warp-drive-data/warp-drive, pull requests merged in 2021-05, with the labels that each got.

#7130 changelog: Switch to using lerna-changelog
  RELEASE.md
  bin/changelog
  package.json
  yarn.lock
Labels: Release Infra

#7493 Relationship Refactor (part 2): The graph should coordinate state updates
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/helpers/accessors.ts
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/-ember-data/tests/integration/records/edit-record-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/integration/relationships/many-to-many-test.js
  packages/-ember-data/tests/integration/serializers/json-api-serializer-test.js
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model/relationships/belongs-to-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/utils-test.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/many-array.js
  packages/record-data/addon/-private/graph/-edge-definition.ts
  packages/record-data/addon/-private/graph/-operations.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/add-to-related-records.ts
  packages/record-data/addon/-private/graph/operations/remove-from-related-records.ts
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/index.ts
  packages/record-data/addon/-private/ordered-set.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/addon/-private/relationships/state/implicit.ts
  packages/record-data/addon/-private/relationships/state/relationship.ts
  packages/record-data/tests/integration/graph/edge-removal/helpers.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/record-data/tests/integration/graph/edge-test.ts
  packages/store/addon/-debug/index.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/backburner.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/notify-changes.ts
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
Labels: Relationship Refactor, changelog:chore, performance, relationship-polymorphism

#7258 feat: record.destroyRecord should also unload the record
  packages/-ember-data/tests/acceptance/relationships/tracking-record-state-test.js
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/integration/record-array-test.js
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/records/delete-record-test.js
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/errors.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/notify-changes.ts
  packages/model/addon/-private/record-state.ts
  packages/model/addon/-private/tmp-cached-polyfill.js
  packages/model/index.js
  packages/model/package.json
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/types/@ember/object/compat.d.ts
  packages/store/types/@ember/runloop/-private/backburner.d.ts
  packages/store/types/@glimmer/tracking.d.ts
  packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
  yarn.lock
Labels: Bug, changelog:bugfix, changelog:feat, target:beta, unload-apis

#7505 Perf: Refactor PromiseManyArray and prep for RFC#745
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/promise-proxies-test.js
  packages/model/addon/-private/system/promise-many-array.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/types/@ember/object/compat.d.ts
  packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
  packages/unpublished-relationship-performance-test-app/app/routes/unload.js
Labels: Relationship Refactor, changelog:feat, performance, target:beta, 🔌 Project Unplug 🔌

#7522 [Test]: modernization rest adapter tests
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
Labels: test-contribution

#7527 [BUGFIX] rollup step should deactivate ember modules polyfill >= 3.27
  package.json
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/utilities/rollup-private-module.js
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: backport-beta, backport-lts, backport-release

#7546 chore: don't minify IE11 builds for tests to improve debugging experience
  packages/-ember-data/ember-cli-build.js
Labels: Build Infra, CI, changelog:chore

#7534 fix: #7039 Ensure meta and links update when fetched relationship is empty or does not include the data key
  packages/-ember-data/tests/integration/references/belongs-to-test.js
  packages/store/addon/-private/system/store/finders.js
Labels: changelog:bugfix

#7544 test: ensure coalesced find requests properly associate options and includes with their snapshot
  packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/store/addon/-private/system/store/finders.js
Labels: changelog:test

#7548 chore: build-url-mixin | replaced comment.reopen with individual definitions per test
  packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
Labels: changelog:test

#7532 fix: belongsTo should not attempt load if inverse in payload provided its data (#7049)
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/tests/integration/graph/edge-test.ts
Labels: changelog:bugfix

#7552 [BUGFIX release] rollup step should deactivate ember modules polyfill >= 3.27
  package.json
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/utilities/rollup-private-module.js
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: backport-release, changelog:bugfix

#7551 test: Ensure many-many order preserved when pushing individual records
  packages/-ember-data/tests/unit/store/push-test.js
Labels: changelog:test

#7550 fix: add asserts and assert tests for belongsTo/hasMany/findRecord empty responses
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/store/finders.js
Labels: changelog:bugfix

#7554 [BUGFIX] reset previously failed linked async belongs-to now works
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
Labels: changelog:bugfix

#7549 [DOC] Fixes JSONAPISerializer serialize documentation
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/serializer/addon/json-api.js
  packages/serializer/addon/json.js
Labels: Documentation, changelog:doc

#7556 adds label enforcement for PRs
  .github/dependabot.yml
  .github/workflows/enforce-pr-labels-beta.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .github/workflows/enforce-pr-labels-lts-prev.yml
  .github/workflows/enforce-pr-labels-lts.yml
  .github/workflows/enforce-pr-labels-old-release.yml
  .github/workflows/enforce-pr-labels-release.yml
Labels: skip-changelog, target:canary

#7537 chore: upgrades to tsconfig
  .eslintrc.js
  packages/-ember-data/tests/dummy/app/routes/application/route.ts
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
  packages/-ember-data/tests/integration/identifiers/record-identifier-for-test.ts
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/adapter/addon/-private/build-url-mixin.ts
  packages/adapter/addon/-private/utils/determine-body-promise.ts
  packages/adapter/addon/json-api.ts
  packages/adapter/addon/rest.ts
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/system/relationships/relationship-meta.ts
  packages/record-data/addon/-private/graph/-edge-definition.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  packages/serializer/addon/index.ts
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/shim-model-class.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  packages/store/addon/-private/ts-interfaces/record-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/record-data-schemas.ts
  root-tsconfig.json
  tsconfig.json
Labels: skip-changelog, target:canary, ts-review, typescript

#7563 [DOC] Updates this._super in native classes to native class super
  packages/serializer/addon/json.js
Labels: changelog:doc, target:canary

#7564 [DOC] Fixes broken EmberObject links and updates this._super in native class examples
  packages/adapter/addon/error.js
  packages/adapter/addon/index.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/many-array.js
  packages/serializer/addon/index.ts
  packages/serializer/addon/json.js
  packages/store/addon/-private/system/core-store.ts
Labels: Documentation, changelog:doc, target:canary
