Repository warp-drive-data/warp-drive, pull requests merged in 2021-11, with the labels that each got.

#7734 CI timeouts testing bump
  .github/workflows/main.yml
Labels: target:canary, changelog:cleanup

#7736 [cleanup]: Remove implicit store injection slated for Ember v4.0.0 (#…
  .github/workflows/main.yml
  packages/-ember-data/addon/setup-container.js
  packages/-ember-data/app/initializers/ember-data.js
  packages/-ember-data/tests/integration/injection-test.js
  packages/unpublished-fastboot-test-app/app/routes/index.js
  packages/unpublished-fastboot-test-app/app/routes/person/new.js
  packages/unpublished-relationship-performance-test-app/app/routes/add-children.js
  packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
  packages/unpublished-relationship-performance-test-app/app/routes/materialization.js
  packages/unpublished-relationship-performance-test-app/app/routes/unload.js
  packages/unpublished-relationship-performance-test-app/app/routes/unused-relationships.js
Labels: changelog:cleanup, backport-beta

#7737 Remove IE11 asset size checks
  .github/workflows/asset-size-check.yml
  scripts/asset-size-tracking/src/create-comment-text.js
Labels: target:canary, changelog:cleanup

#7739 Remove TARGET_IE11 flag
  .github/workflows/main.yml
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/tests/dummy/config/targets.js
  packages/adapter/tests/dummy/config/targets.js
  packages/debug/tests/dummy/config/targets.js
  packages/model/tests/dummy/config/targets.js
  packages/record-data/tests/dummy/config/targets.js
  packages/serializer/tests/dummy/config/targets.js
  packages/store/tests/dummy/config/targets.js
  packages/unpublished-adapter-encapsulation-test-app/config/targets.js
  packages/unpublished-debug-encapsulation-test-app/config/targets.js
  packages/unpublished-fastboot-test-app/config/targets.js
  packages/unpublished-model-encapsulation-test-app/config/targets.js
  packages/unpublished-model-encapsulation-test-app/testem.js
  packages/unpublished-record-data-encapsulation-test-app/config/targets.js
  packages/unpublished-serializer-encapsulation-test-app/config/targets.js
  packages/unpublished-test-infra/tests/dummy/config/targets.js
Labels: target:canary, changelog:cleanup

#7732 [Chore]: Convert transforms to class syntax
  packages/-ember-data/tests/unit/transform/custom-test.js
  packages/serializer/addon/-private/transforms/boolean.js
  packages/serializer/addon/-private/transforms/date.js
  packages/serializer/addon/-private/transforms/number.js
  packages/serializer/addon/-private/transforms/string.js
  packages/serializer/addon/-private/transforms/transform.js
Labels: target:canary, changelog:chore

#7722 Fix deprecated assign usage from @ember/assign
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/store/peek-record-test.js
  packages/adapter/addon/rest.ts
  packages/canary-features/addon/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  packages/serializer/addon/json.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/finders.js
  packages/unpublished-test-infra/addon-test-support/public-props.js
Labels: target:canary, changelog:cleanup, changelog:chore

#7744 Disable ilios partner test
  .github/workflows/main.yml
Labels: target:canary, changelog:test

#7742 Remove InternalModel access in Reference
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/store/addon/-private/system/references/reference.ts
Labels: target:canary, changelog:cleanup, changelog:deprecation

#7740 Remove symbol util in place of built in Symbol
  .eslintrc.js
  packages/adapter/addon/rest.ts
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/request-cache.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  packages/store/addon/-private/utils/symbol.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/utils/symbol-ponyfill.ts
  tsconfig.json
Labels: target:canary, changelog:cleanup

#7741 Remove IE11 hacks
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/private-build-infra/src/stripped-build-plugins.js
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/store/finders.js
Labels: target:canary, changelog:cleanup

#7746 Remove deprecated toJSON on model instance
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/unit/model-test.js
  packages/model/addon/-private/model.js
Labels: target:canary, changelog:cleanup, changelog:deprecation

#7745 Remove delete and unload record deprecations in core-store
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/store/addon/-private/system/core-store.ts
Labels: target:canary, changelog:cleanup, changelog:deprecation

#7750 reference: Fix broken `meta()` snippet
  packages/store/addon/-private/system/references/reference.ts
Labels: target:canary, changelog:doc

#7748 Fix deprecated assign usage from @ember/assign (#7722)
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/store/peek-record-test.js
  packages/adapter/addon/rest.ts
  packages/canary-features/addon/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  packages/serializer/addon/json.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/finders.js
  packages/unpublished-test-infra/addon-test-support/public-props.js
Labels: backport-beta, changelog:deprecation

#7729 Cache dependencies in GitHub Actions CI workflow
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
Labels: CI, target:canary, changelog:cleanup

#7725 Update package.json to include the repository
  packages/canary-features/package.json
  packages/private-build-infra/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-eslint-rules/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
Labels: target:canary, changelog:chore

#7757 Remove legacy test support in setup
  packages/-ember-data/addon/setup-container.js
Labels: target:canary, changelog:cleanup, changelog:chore

#7760 chore: cancel older CI jobs
  .github/workflows/asset-size-check.yml
  .github/workflows/enforce-pr-labels-beta.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .github/workflows/enforce-pr-labels-lts-prev.yml
  .github/workflows/enforce-pr-labels-lts.yml
  .github/workflows/enforce-pr-labels-old-release.yml
  .github/workflows/enforce-pr-labels-release.yml
  .github/workflows/main.yml
  .github/workflows/perf-check.yml
Labels: CI, target:canary, changelog:chore

#7767 Remove TARGET_IE11 flag
  .eslintrc.js
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/enforce-pr-labels-beta.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .github/workflows/enforce-pr-labels-lts-prev.yml
  .github/workflows/enforce-pr-labels-lts.yml
  .github/workflows/enforce-pr-labels-old-release.yml
  .github/workflows/enforce-pr-labels-release.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/perf-check.yml
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/tests/dummy/config/targets.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/integration/store/model-name-test.js
  packages/adapter/addon/rest.ts
  packages/adapter/tests/dummy/config/targets.js
  packages/debug/tests/dummy/config/targets.js
  packages/model/tests/dummy/config/targets.js
  packages/private-build-infra/src/stripped-build-plugins.js
  packages/record-data/tests/dummy/config/targets.js
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/serializer/tests/dummy/config/targets.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/identifiers/utils/uuid-v4.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/request-cache.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/ts-interfaces/identifier.ts
  packages/store/addon/-private/utils/symbol.ts
  packages/store/tests/dummy/config/targets.js
  packages/unpublished-adapter-encapsulation-test-app/config/targets.js
  packages/unpublished-debug-encapsulation-test-app/config/targets.js
  packages/unpublished-fastboot-test-app/config/targets.js
  packages/unpublished-model-encapsulation-test-app/config/targets.js
  packages/unpublished-model-encapsulation-test-app/testem.js
  packages/unpublished-record-data-encapsulation-test-app/config/targets.js
  packages/unpublished-serializer-encapsulation-test-app/config/targets.js
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/utils/symbol-ponyfill.ts
  packages/unpublished-test-infra/tests/dummy/config/targets.js
  scripts/asset-size-tracking/src/create-comment-text.js
  tsconfig.json
Labels: changelog:cleanup, backport-beta, changelog:deprecation

#7762 chore(deps): bump broccoli-rollup from 4.1.1 to 5.0.0 (#7559)
  .github/workflows/main.yml
  packages/-ember-data/tests/integration/store-test.js
  packages/private-build-infra/package.json
  yarn.lock
Labels: target:lts, changelog:bugfix, backport-lts
