Repository warp-drive-data/warp-drive, pull requests merged in 2021-06, with the labels that each got.

#7568 Fixes `DeprecatedEvented` link
  packages/model/addon/-private/model.js
  packages/store/addon/-private/system/deprecated-evented.js
Labels: changelog:doc, target:canary

#7577 chore: store-adapter-test | removed run loop where possible
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
Labels: changelog:test, target:canary

#7578 [Chore]: shouldAssertMethodCallsOnDestroyedStore: true
  packages/store/addon/-private/system/core-store.ts
Labels: changelog:cleanup, target:canary

#7104 [FEAT] RFC-521 Accept Identifiers for store methods
  packages/-ember-data/tests/integration/adapter/rest-adapter/find-record-test.js
  packages/-ember-data/tests/integration/identifiers/cache-test.ts
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/references/record-test.js
  packages/-ember-data/tests/unit/store/asserts-test.js
  packages/-ember-data/tests/unit/store/peek-record-test.js
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/store.ts
  packages/store/addon/-private/utils/construct-resource.ts
Labels: Feature, changelog:feat, code-review, target:canary

#7579 Add labeling guidance to contributing guide
  CONTRIBUTING.md
Labels: skip-changelog, target:canary

#7581 Follow up: store identifier #7104
  packages/-ember-data/tests/integration/references/record-test.js
  packages/store/addon/-private/system/core-store.ts
Labels: changelog:cleanup, target:canary

#7591 Move files from bin to scripts folder
  .codeclimate.yml
  .eslintrc.js
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/perf-check.yml
  .gitignore
  RELEASE.md
  package.json
  packages/store/addon/-private/system/core-store.ts
  scripts/-tarball-info.js
  scripts/add-dev-dependency.js
  scripts/asset-size-tracking/generate-analysis.js
  scripts/asset-size-tracking/generate-diff.js
  scripts/asset-size-tracking/print-analysis.js
  scripts/asset-size-tracking/src/create-comment-text.js
  scripts/asset-size-tracking/src/get-built-dist.js
  scripts/asset-size-tracking/src/library.js
  scripts/asset-size-tracking/src/parse-modules.js
  scripts/asset-size-tracking/src/post-comment.sh
  scripts/lint-changed-js.js
  scripts/lint-features.js
  scripts/packages-for-commit.js
  scripts/perf-tracking/create-comment.js
  scripts/publish.js
  scripts/sync-dev-dependency.js
  scripts/test-external-partner-project.js
Labels: skip-changelog, target:canary

#7592 Add a comment explaining setting an errors status as a string
  packages/adapter/addon/rest.ts
Labels: changelog:doc, target:canary

#7589 chore: fix or silence-expected deprecations
  .github/workflows/perf-check.yml
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/adapter/find-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/injection-test.js
  packages/-ember-data/tests/integration/multiple-stores-test.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/integration/snapshot-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/system/snapshot-record-array-test.js
  packages/adapter/addon/index.ts
  packages/adapter/addon/rest.ts
  packages/store/types/@ember/version.d.ts
  packages/store/types/ember-compatibility-helpers/index.d.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/utils/symbol-ponyfill.ts
  packages/unpublished-test-infra/package.json
Labels: changelog:chore, target:canary
