Repository warp-drive-data/warp-drive, pull requests merged in 2021-08, with the labels that each got.

#7651 Igor/request caching
  packages/-ember-data/tests/integration/store-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
Labels: target:beta, changelog:bugfix

#7652 Deprecate passing non ember data records to unloadRecord and deleteRecord
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/store/addon/-private/system/core-store.ts
Labels: target:beta, changelog:deprecation

#7653 Nightly test: beta and canary fail b/c semver comparison
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
Labels: target:canary, changelog:test

#7615 [DOC] Fix transform example not using native class syntax
  packages/model/addon/-private/attr.js
Labels: target:canary, changelog:doc

#7662 [deps]: bump ember-compatibility-helpers
  package.json
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/store/types/ember-compatibility-helpers/index.d.ts
  yarn.lock
Labels: target:canary, changelog:chore

#7670 Update version on master to v4.0.0-alpha.1
  lerna.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-eslint-rules/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
Labels: target:canary, skip-changelog

#7674 Changelog for v4.0.0-beta.1
  CHANGELOG.md
Labels: skip-changelog

#7675 Changelog for v4.0.0-beta.0
  CHANGELOG.md
Labels: target:canary, skip-changelog

#7683 Revert assertion on content attribute and add test to prevent regression
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/attr-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
Labels: target:beta, target:release, changelog:bugfix

#7689 Revert "[BUGFIX Model] assert when 'content' is used as a property on a record (#7545)"
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/attr-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
Labels: changelog:bugfix, backport-release
