Repository warp-drive-data/warp-drive, pull requests merged in 2021-12, with the labels that each got.

#7776 Release 4.0
  .github/workflows/main.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/adapter/addon/rest.ts
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-adapter-encapsulation-test-app/config/optional-features.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-debug-encapsulation-test-app/config/optional-features.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/app/templates/application.hbs
  packages/unpublished-fastboot-test-app/app/templates/person/new.hbs
  packages/unpublished-fastboot-test-app/config/ember-try.js
  packages/unpublished-fastboot-test-app/config/fastboot-testing.js
  packages/unpublished-fastboot-test-app/config/optional-features.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/config/optional-features.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-record-data-encapsulation-test-app/config/optional-features.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-serializer-encapsulation-test-app/config/optional-features.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tests/dummy/config/optional-features.json
  yarn.lock
Labels: backport-release

#7789 CHANGELOG 4.0
  CHANGELOG.md
Labels: backport-release

#7788 Release 4.0 (#7776)
  .github/workflows/main.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/adapter/addon/rest.ts
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-adapter-encapsulation-test-app/config/optional-features.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-debug-encapsulation-test-app/config/optional-features.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/app/templates/application.hbs
  packages/unpublished-fastboot-test-app/app/templates/person/new.hbs
  packages/unpublished-fastboot-test-app/config/ember-try.js
  packages/unpublished-fastboot-test-app/config/fastboot-testing.js
  packages/unpublished-fastboot-test-app/config/optional-features.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/config/optional-features.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-record-data-encapsulation-test-app/config/optional-features.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-serializer-encapsulation-test-app/config/optional-features.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tests/dummy/config/optional-features.json
  yarn.lock
Labels: backport-beta

#7791 Changelog BETA
  CHANGELOG.md
Labels: backport-beta

#7792 Cherry-pick 4.0 #7776
  .github/workflows/main.yml
  package.json
  packages/-ember-data/config/ember-try.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/adapter/addon/rest.ts
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-adapter-encapsulation-test-app/config/optional-features.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-debug-encapsulation-test-app/config/optional-features.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/app/templates/application.hbs
  packages/unpublished-fastboot-test-app/app/templates/person/new.hbs
  packages/unpublished-fastboot-test-app/config/ember-try.js
  packages/unpublished-fastboot-test-app/config/fastboot-testing.js
  packages/unpublished-fastboot-test-app/config/optional-features.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/config/optional-features.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-record-data-encapsulation-test-app/config/optional-features.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/app/templates/application.hbs
  packages/unpublished-serializer-encapsulation-test-app/config/optional-features.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tests/dummy/config/optional-features.json
  yarn.lock
Labels: target:canary, changelog:cleanup, changelog:chore

#7759 Remove fallback for when no model serializer
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/store/serializer-for-test.js
  packages/adapter/addon/index.ts
  packages/adapter/addon/json-api.ts
  packages/adapter/addon/rest.ts
  packages/store/addon/-private/system/core-store.ts
  packages/unpublished-fastboot-test-app/app/adapters/application.ts
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/create-record-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/delete-record-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/errors-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/relationships-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/requests-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/update-record-test.js
Labels: target:canary, changelog:cleanup, changelog:deprecation

#7795 [bug]: findRecord should not cache if includes differ (#7702)
  packages/-ember-data/tests/integration/store-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/ts-interfaces/fetch-manager.ts
  packages/store/addon/-private/ts-interfaces/store.ts
Labels: backport-lts

#7797 [bug]: findRecord should not cache if includes differ (#7702)
  packages/-ember-data/tests/integration/store-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/ts-interfaces/fetch-manager.ts
Labels: backport-release

#7796 feat: autotracking for reference id access
  .eslintrc.js
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/record-notification-manager.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/index.js
  packages/store/package.json
  tsconfig.json
  yarn.lock
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7800 update test and fix lid reflection
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/model/states.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7801 add test and fix push of duplicate identifiers to a relationship
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7691 add test + fix for chained async has many
  packages/-ember-data/tests/acceptance/relationships/tracking-record-state-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/store/addon/-private/system/model/internal-model.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7771 Fix: assign unknown properties in init after initialization is finished to ensure proper setup timing
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/model/addon/-private/model.js
  packages/store/addon/-private/system/ds-model-store.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7802 fix: A(PromiseManyArray) should have no-effect
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/store/types/ember/index.d.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, bugfix-3-28

#7803 Backport Train for Beta
  .eslintrc.js
  .github/workflows/main.yml
  packages/-ember-data/tests/acceptance/relationships/tracking-record-state-test.js
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/record-notification-manager.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/index.js
  packages/store/package.json
  packages/store/types/ember/index.d.ts
  tsconfig.json
  yarn.lock
Labels: changelog:bugfix, backport-beta

#7804 Backport Train for Release
  .eslintrc.js
  .github/workflows/main.yml
  packages/-ember-data/tests/acceptance/relationships/tracking-record-state-test.js
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/record-notification-manager.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/index.js
  packages/store/package.json
  packages/store/types/ember/index.d.ts
  tsconfig.json
Labels: changelog:bugfix, backport-release

#7807 Backport Train for Release (#7803)
  yarn.lock
Labels: backport-release

#7811 Fix nightly runs
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: target:release, changelog:chore

#7812 Remove RECORD_ARRAY_MANAGER_IDENTIFIERS
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
Labels: target:canary, changelog:chore

#7813 Regenerate lockfile
  yarn.lock
Labels: target:canary, changelog:chore

#7814 Remove IDENTIFIERS feature flag
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
Labels: target:canary, changelog:chore

#7815 Remove FULL_LINKS_ON_RELATIONSHIPS feature flag
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
Labels: target:canary, changelog:chore

#7816 Remove !CUSTOM_MODEL_CLASS branches
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model-test.js
  packages/canary-features/addon/default-features.ts
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/model.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/serializer/addon/json-api.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/unpublished-model-encapsulation-test-app/app/app.js
  packages/unpublished-model-encapsulation-test-app/tests/integration/model-for-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/serialize-test.js
Labels: target:canary, changelog:chore

#7830 CHANGELOG 4.1.0
  CHANGELOG.md
Labels: changelog:chore, backport-release

#7831 Regen yarn lockfile
  yarn.lock
Labels: changelog:chore, backport-release

#7832 CHANGELOG 4.2.0-beta.0
  CHANGELOG.md
Labels: changelog:chore, backport-beta
