Repository warp-drive-data/warp-drive, pull requests merged in 2021-04, with the labels that each got.

#7425 Pass lid from relationship data to get record data
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
Labels: Bug

#7451 [DOC] Fix `JSONAPISerializer` import in docs
  packages/serializer/addon/json-api.js
Labels: Documentation

#7448 Bugfix: coalesceFindRequests should work with non native Adapter classes
  packages/-ember-data/testem.js
  packages/-ember-data/tests/unit/adapters/json-api-adapter/json-api-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/rest-test.js
  packages/adapter/addon/index.ts
  packages/adapter/addon/json-api.ts
  packages/adapter/addon/rest.ts
  packages/unpublished-adapter-encapsulation-test-app/testem.js
  packages/unpublished-debug-encapsulation-test-app/testem.js
  packages/unpublished-fastboot-test-app/testem.js
  packages/unpublished-model-encapsulation-test-app/testem.js
  packages/unpublished-record-data-encapsulation-test-app/testem.js
  packages/unpublished-relationship-performance-test-app/testem.js
  packages/unpublished-serializer-encapsulation-test-app/testem.js
  packages/unpublished-test-infra/testem.js
Labels: Bug

#7434 [Task]: remove meaningless assertion
  packages/store/addon/-private/system/core-store.ts
Labels: Improvement

#7454 [PERF] Class Fields Use Optimization & Made OrderedSet Faster (Again)
  packages/-ember-data/package.json
  packages/record-data/addon/-private/ordered-set.ts
  packages/record-data/addon/-private/relationships/state/relationship.ts
  packages/record-data/index.js
  packages/record-data/package.json
  packages/record-data/types/@ember/ordered-set/index.d.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/types/ember/index.d.ts
  yarn.lock
Labels: performance, 🌲 Project Trim 🌲, 🔌 Project Unplug 🔌

#7436 [CHORE] auto publish alpha versions
  .github/workflows/alpha-release.yml
  RELEASE.md
  bin/determine-next-alpha-version.js
  bin/publish.js
Labels: CI, Release Infra

#7464 chore: resolve implicit this and deprecation-staging deprecations
  packages/-ember-data/addon/setup-container.js
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/adapter/addon/rest.ts
  packages/model/addon/-private/model.js
  packages/serializer/addon/rest.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/deprecated-evented.js
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/types/@ember/debug/index.d.ts
  packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js
Labels: test-contribution

#7457 [CHORE] setup test suite for the record-data package
  .eslintrc.js
  package.json
  packages/-ember-data/package.json
  packages/-ember-data/tests/dummy/config/targets.js
  packages/adapter/index.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/index.js
  packages/model/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/record-data/ember-cli-build.js
  packages/record-data/index.js
  packages/record-data/package.json
  packages/record-data/testem.js
  packages/record-data/tests/dummy/config/environment.js
  packages/record-data/tests/dummy/config/optional-features.json
  packages/record-data/tests/dummy/config/targets.js
  packages/record-data/tests/index.html
  packages/record-data/tests/integration/graph.ts
  packages/record-data/tests/test-helper.js
  packages/serializer/index.js
  packages/serializer/package.json
  packages/store/index.js
  packages/store/package.json
  packages/unpublished-fastboot-test-app/package.json
  yarn.lock
Labels: CI

#7453 [CHORE] burndown of InternalModel methods that can be eliminated safely
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/many-array.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
Labels: 🌲 Project Trim 🌲

#7226 refactor: Native Model
  .github/workflows/asset-size-check.yml
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/attr-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/relationships/ext.js
  packages/model/addon/-private/system/relationships/relationship-meta.ts
  packages/model/index.js
  packages/model/package.json
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/index.js
  packages/store/package.json
  yarn.lock
Labels: changelog:chore

#7470 chore: convert relationships to use identifiers
  .prettierrc
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/record-data/addon/-private/accessors.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/index.ts
  packages/record-data/addon/-private/ordered-set.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/create.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/addon/-private/relationships/state/relationship.ts
  packages/record-data/addon/-private/ts-interfaces/relationship-record-data.ts
  packages/record-data/package.json
  packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/record-data/tests/integration/graph/edge-test.ts
  packages/record-data/tests/integration/graph/graph-test.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/backburner.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/references/belongs-to.js
  packages/store/addon/-private/system/references/has-many.js
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/system/ts-upgrade-map.ts
  packages/store/addon/-private/ts-interfaces/record-data-record-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
  packages/store/addon/-private/utils/brand.ts
Labels: Relationship Refactor, performance, 🌲 Project Trim 🌲
