Repository warp-drive-data/warp-drive, pull requests merged in 2021-09, with the labels that each got.

#7680 [Bugfix] ensure `shouldCompileModules` is once again respected
  packages/private-build-infra/src/utilities/rollup-private-module.js
Labels: Bug, target:beta, target:release, target:canary, changelog:bugfix

#7690 Revert "[BUGFIX Model] assert when 'content' is used as a property on a record (#7545)"
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/attr-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
Labels: changelog:bugfix, backport-beta

#7694 [Bugfix] ensure `shouldCompileModules` is once again respected (#7680)
  packages/private-build-infra/src/utilities/rollup-private-module.js
Labels: changelog:bugfix, backport-release

#7695 [Bugfix] ensure `shouldCompileModules` is once again respected (#7680)
  packages/private-build-infra/src/utilities/rollup-private-module.js
Labels: changelog:bugfix, backport-beta

#7697 [BUGFIX] Update @ember/string to the latest version to fix compatibility with ember-source 4.x
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  yarn.lock
Labels: target:beta, target:release, target:canary, changelog:bugfix

#7698 [BACKPORT Release] @ember/string to the latest version. The prior (#7697)
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  yarn.lock
Labels: changelog:bugfix, backport-release

#7699 [BACKPORT Beta] Update @ember/string to the latest version. The prior (#7697)
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  yarn.lock
Labels: changelog:bugfix, backport-beta

#7703 fix tests
  packages/-ember-data/tests/integration/store-test.js
Labels: target:canary, changelog:cleanup

#7667 [cleanup]: Remove implicit store injection slated for Ember v4.0.0
  packages/-ember-data/addon/setup-container.js
  packages/-ember-data/app/initializers/ember-data.js
  packages/-ember-data/tests/integration/injection-test.js
  packages/unpublished-fastboot-test-app/app/routes/index.js
  packages/unpublished-fastboot-test-app/app/routes/person/new.js
  packages/unpublished-relationship-performance-test-app/app/routes/add-children.js
  packages/unpublished-relationship-performance-test-app/app/routes/destroy.js
  packages/unpublished-relationship-performance-test-app/app/routes/materialization.js
  packages/unpublished-relationship-performance-test-app/app/routes/unload.js
  packages/unpublished-relationship-performance-test-app/app/routes/unused-relationships.js
Labels: target:canary, changelog:cleanup, changelog:deprecation
