Repository warp-drive-data/warp-drive, pull requests merged in 2022-09, with the labels that each got.

#8159 fix: uuid polyfill logic
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/utils/uuid-polyfill.ts
Labels: target:release, target:canary, target:lts, changelog:bugfix

#8161 chore: restructure graph home
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/record-data/addon/-private/graph/-edge-definition.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/graph.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/add-to-related-records.ts
  packages/record-data/addon/-private/graph/operations/merge-identifier.ts
  packages/record-data/addon/-private/graph/operations/remove-from-related-records.ts
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/store/addon/-private/caches/instance-cache.ts
Labels: target:canary, changelog:chore

#8169 fix: uuid polyfill logic
  packages/store/addon/-private/identifier-cache.ts
  packages/store/addon/-private/utils/uuid-polyfill.ts
Labels: changelog:bugfix, backport-old-release

#8172 fix: correct deprecation message for toArray
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: target:beta, target:release, target:canary, changelog:bugfix

#8171 fix: filterBy should compare values
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: target:beta, target:release, target:canary, changelog:bugfix

#8178 fix: filterBy should compare values
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: changelog:bugfix, backport-release

#8181 backport fix for clearing subscriptions from #8116 (fix #7857)
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/record-notification-manager.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
Labels: changelog:bugfix, backport-lts-prev

#8176 fix: correct deprecation message for toArray
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: changelog:bugfix, backport-release

#8154 [BUGFIX] Model state error 3.28
  packages/-ember-data/tests/integration/model-errors-test.ts
  packages/store/addon/-private/system/model/states.js
Labels: changelog:bugfix, backport-lts-prev

#8182 backport fixes to 3.28 lts
  packages/-ember-data/tests/integration/debug-adapter-test.js
  packages/-ember-data/tests/unit/utils/serialize-query-params-test.js
  packages/adapter/addon/-private/utils/serialize-query-params.ts
  packages/debug/addon/index.js
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/tests/integration/graph/operations-test.ts
Labels: changelog:bugfix, backport-lts-prev

#8184 Use array notation instead of at for accessing values
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: target:release, target:canary, changelog:bugfix

#8185 Use array notation instead of at for accessing values (#8184)
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: changelog:bugfix, backport-release

#8189 Use array notation instead of at for accessing object at values
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: target:release, target:canary, changelog:bugfix

#8191 Use array notation instead of at for accessing object at values (#8189)
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/record-arrays/identifier-array.ts
Labels: changelog:bugfix, backport-release
