Repository warp-drive-data/warp-drive, pull requests merged in 2022-02, with the labels that each got.

#7848 Don't use array.push(...spread) with unknown input
  packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
  packages/serializer/addon/-private/embedded-records-mixin.js
  packages/serializer/addon/json.js
  packages/serializer/addon/rest.js
Labels: target:canary, changelog:bugfix

#7856 Fix: assign unknown properties in init after initialization is finished to ensure proper setup timing (#7771)
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/model/addon/-private/model.js
  packages/store/addon/-private/system/ds-model-store.ts
Labels: backport-lts-prev

#7861 chore: remove things deprecated for 4.0
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/lifecycle-hooks-test.js
  packages/-ember-data/tests/integration/references/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationship-load-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/lifecycle-callbacks-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/model/addon/-private/errors.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/system/many-array.js
  packages/model/addon/-private/system/promise-many-array.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/serializer/addon/rest.js
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/deprecated-evented.js
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/record-arrays/record-array.js
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/store/finders.js
  packages/unpublished-test-infra/tests/unit/deprecations-stripped-test.js
Labels: target:canary, changelog:cleanup

#7863 Update eslint and typescript to latest
  .eslintrc.js
  package.json
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/identifiers/new-records-test.ts
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/model-errors-test.ts
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/adapter/addon/-private/utils/determine-body-promise.ts
  packages/adapter/addon/rest.ts
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/record-data/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  packages/record-data/tests/integration/graph/edge-removal/helpers.ts
  packages/record-data/tests/integration/graph/edge-test.ts
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/package.json
  packages/store/types/ember-data-qunit-asserts/index.d.ts
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-assertion.ts
  packages/unpublished-test-infra/package.json
  tsconfig.json
  yarn.lock
Labels: target:canary, changelog:chore

#7864 feat: better debuggability
  package.json
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/record-data/addon/-private/graph/index.ts
  packages/store/addon/-private/identifiers/cache.ts
  packages/store/addon/-private/identifiers/is-stable-identifier.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/shim-model-class.ts
  packages/store/addon/-private/system/record-array-manager.js
  packages/store/addon/-private/system/record-data-for.ts
  packages/store/addon/-private/system/record-notification-manager.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/references/reference.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/weak-cache.ts
  packages/store/addon/-private/ts-interfaces/identifier.ts
  yarn.lock
Labels: target:canary, changelog:feat

#7865 Cleanup eslint config
  .eslintrc.js
  package.json
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
  scripts/lint-changed-js.js
  scripts/publish.js
Labels: target:canary, changelog:chore

#7867 RFC 794: Simplifying Schema Definition Service type signatures
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/shim-model-class.ts
  packages/store/addon/-private/system/schema-definition-service.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/ts-interfaces/schema-definition-service.ts
Labels: target:canary, changelog:chore

#7878 Remove lint rule to prevent global Promise
  .eslintrc.js
  packages/store/types/ember-data-qunit-asserts/index.d.ts
Labels: target:canary, changelog:chore

#7866 Autofix most qunit linting
  .eslintrc.js
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/integration/application-test.js
  packages/-ember-data/tests/integration/client-id-generation-test.js
  packages/-ember-data/tests/integration/identifiers/configuration-test.ts
  packages/-ember-data/tests/integration/identifiers/lid-reflection-test.ts
  packages/-ember-data/tests/integration/identifiers/new-records-test.ts
  packages/-ember-data/tests/integration/identifiers/polymorphic-scenarios-test.ts
  packages/-ember-data/tests/integration/record-array-test.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/-ember-data/tests/integration/records/edit-record-test.js
  packages/-ember-data/tests/integration/records/reload-test.js
  packages/-ember-data/tests/integration/records/rematerialize-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/integration/relationships/json-api-links-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/unload-new-record-test.js
  packages/-ember-data/tests/integration/store/adapter-for-test.js
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/init-properties-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/promise-proxies-test.js
  packages/-ember-data/tests/unit/store/peek-record-test.js
  packages/-ember-data/tests/unit/store/unload-test.js
  packages/record-data/tests/integration/graph/edge-test.ts
Labels: target:canary, changelog:chore

#7881 Simplify import linting
  .eslintrc.js
Labels: target:canary, changelog:cleanup

#7885 chore: add eslint-plugin-eslint-comments
  .eslintrc.js
  package.json
  packages/-ember-data/lib/yui-docs-preprocessor.js
  packages/unpublished-test-infra/addon-test-support/assert-all-deprecations.js
  scripts/lint-changed-js.js
  yarn.lock
Labels: target:canary, changelog:chore

#7882 fix: dont early exit loop when filtering duplicates from relationship updates
  .eslintrc.js
  package.json
  packages/-ember-data/node-tests/docs/test-coverage.js
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/tests/integration/graph/operations-test.ts
  tsconfig.json
  yarn.lock
Labels: target:beta, target:release, target:canary, changelog:bugfix

#7887 [RFC 637] Customizable test setups
  packages/adapter/blueprints/adapter-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/adapter/blueprints/adapter-test/qunit-files/__root__/__path__/__test__.js
  packages/adapter/node-tests/fixtures/adapter-test/application-default.js
  packages/adapter/node-tests/fixtures/adapter-test/foo-default.js
  packages/adapter/node-tests/fixtures/adapter-test/mocha-rfc232.js
  packages/adapter/node-tests/fixtures/adapter-test/rfc232.js
  packages/model/blueprints/model-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/model/blueprints/model-test/qunit-files/__root__/__path__/__test__.js
  packages/model/node-tests/fixtures/model-test/comment-default.js
  packages/model/node-tests/fixtures/model-test/foo-default.js
  packages/model/node-tests/fixtures/model-test/mocha-rfc232.js
  packages/model/node-tests/fixtures/model-test/post-default.js
  packages/model/node-tests/fixtures/model-test/rfc232.js
  packages/serializer/blueprints/serializer-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/serializer-test/qunit-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/transform-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/transform-test/qunit-files/__root__/__path__/__test__.js
  packages/serializer/node-tests/fixtures/serializer-test/application-default.js
  packages/serializer/node-tests/fixtures/serializer-test/foo-default.js
  packages/serializer/node-tests/fixtures/serializer-test/mocha-rfc232.js
  packages/serializer/node-tests/fixtures/serializer-test/rfc232.js
  packages/serializer/node-tests/fixtures/transform-test/default.js
  packages/serializer/node-tests/fixtures/transform-test/mocha-rfc232.js
  packages/serializer/node-tests/fixtures/transform-test/rfc232.js
Labels: target:canary, changelog:feat

#7898 Changelog 4.1.0
  CHANGELOG.md
Labels: target:canary, changelog:doc

#7905 chore: faster checks by cloning less
  .github/workflows/asset-size-check.yml
  .github/workflows/perf-check.yml
Labels: target:canary, changelog:chore
