Repository warp-drive-data/warp-drive, pull requests merged in 2022-04, with the labels that each got.

#7945 fix for #7904 computed chains not updated for async hasMany loading
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/model/addon/-private/system/promise-many-array.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix

#7949 fix for #7904 computed chains not updated for async hasMany loading
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/model/addon/-private/system/promise-many-array.ts
Labels: changelog:bugfix, backport-beta

#7849 Remove some usage of runtime require
  packages/-ember-data/addon/index.js
  packages/-ember-data/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/schema-definition-service.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/index.js
  packages/store/package.json
  yarn.lock
Labels: target:canary, changelog:cleanup

#7947 fix for #7904 computed chains not updated for async hasMany loading
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/model/addon/-private/system/promise-many-array.ts
Labels: changelog:bugfix, backport-lts

#7950 some small cleanups and fix test container
  packages/-ember-data/tests/index.html
  packages/adapter/tests/index.html
  packages/model/tests/index.html
  packages/record-data/tests/index.html
  packages/serializer/tests/index.html
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/ds-model-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/tests/index.html
  packages/unpublished-adapter-encapsulation-test-app/tests/index.html
  packages/unpublished-debug-encapsulation-test-app/tests/index.html
  packages/unpublished-fastboot-test-app/tests/index.html
  packages/unpublished-model-encapsulation-test-app/tests/index.html
  packages/unpublished-record-data-encapsulation-test-app/tests/index.html
  packages/unpublished-relationship-performance-test-app/tests/index.html
  packages/unpublished-serializer-encapsulation-test-app/tests/index.html
  packages/unpublished-test-infra/tests/index.html
Labels: target:canary, changelog:cleanup

#7624 [CHORE]: Modernize find-all-test
  packages/-ember-data/tests/integration/adapter/find-all-test.js
Labels: target:canary, changelog:cleanup, changelog:chore

#7625 [CHORE]: Modernize client-side-delete-test
  packages/-ember-data/tests/integration/adapter/client-side-delete-test.js
Labels: target:canary, changelog:test

#7629 [CHORE]: Modernize queries-test
  packages/-ember-data/tests/integration/adapter/queries-test.js
Labels: target:canary, changelog:cleanup

#7630 [CHORE]: Modernize record-persistence-test
  packages/-ember-data/tests/integration/adapter/record-persistence-test.js
Labels: target:canary, changelog:test

#7626 [CHORE]: Modernize build-url-mixin-strict-equal
  packages/-ember-data/tests/integration/adapter/build-url-mixin-test.js
Labels: target:canary, changelog:test

#7628 [CHORE]: Modernize json-api-adapter-test
  packages/-ember-data/tests/integration/adapter/json-api-adapter-test.js
Labels: target:canary, changelog:test

#7951 chore: remove unneeded version code in ember-data package
  packages/-ember-data/addon/index.js
Labels: target:canary, changelog:cleanup

#7952 chore: migrate files that only re-export to ts to preserve type flow
  packages/-ember-data/addon/-private/index.ts
  packages/-ember-data/addon/adapter.ts
  packages/-ember-data/addon/adapters/errors.ts
  packages/-ember-data/addon/adapters/json-api.ts
  packages/-ember-data/addon/adapters/rest.ts
  packages/-ember-data/addon/attr.ts
  packages/-ember-data/addon/model.ts
  packages/-ember-data/addon/relationships.ts
  packages/-ember-data/addon/serializer.ts
  packages/-ember-data/addon/serializers/embedded-records-mixin.ts
  packages/-ember-data/addon/serializers/json-api.ts
  packages/-ember-data/addon/serializers/json.ts
  packages/-ember-data/addon/serializers/rest.ts
  packages/-ember-data/addon/setup-container.ts
  packages/-ember-data/addon/transform.ts
Labels: target:canary, changelog:cleanup

#7631 [CHORE]: Modernized serialize-test
  packages/-ember-data/tests/integration/adapter/serialize-test.js
Labels: target:canary, changelog:chore

#7623 [CHORE]: Modernize Find-Test
  packages/-ember-data/tests/integration/adapter/find-test.js
Labels: target:canary, changelog:cleanup

#7854 fix: pass correct args to keyFor<Attribute|Relationship> when normalizing
  packages/serializer/addon/json.js
Labels: target:canary, changelog:bugfix

#7622 [CHORE]: Modernize Handle-Response-Test
  packages/-ember-data/tests/integration/adapter/handle-response-test.js
Labels: target:canary, changelog:chore

#7761 Cherry pick: chore(deps): bump broccoli-rollup from 4.1.1 to 5.0.0
  .github/workflows/main.yml
  packages/-ember-data/tests/integration/store-test.js
  packages/private-build-infra/package.json
  yarn.lock
Labels: changelog:bugfix, target:lts-prev, backport-lts-prev

#7953 chore: cleanup a few more leaf types
  packages/-ember-data/tests/integration/store/serializer-for-test.js
  packages/adapter/addon/-private/utils/parse-response-headers.ts
  packages/adapter/addon/-private/utils/serialize-into-hash.js
  packages/adapter/addon/-private/utils/serialize-into-hash.ts
  packages/adapter/addon/json-api.ts
  packages/adapter/addon/rest.ts
  packages/model/addon/-private/system/diff-array.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/snapshot.ts
  packages/store/addon/-private/system/store/serializer-response.ts
  packages/store/addon/-private/ts-interfaces/ember-data-json-api.ts
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
Labels: target:canary, changelog:cleanup

#7582 chore: type DeprecatedEvented Mixin and Errors class
  .eslintrc.js
  packages/model/addon/-private/errors.ts
  packages/store/types/@ember/array/-private/enumerable.d.ts
  packages/store/types/@ember/array/-private/mutable-enumerable.d.ts
  packages/store/types/@ember/array/-private/native-array.d.ts
  packages/store/types/@ember/array/index.d.ts
  packages/store/types/@ember/array/mutable.d.ts
  packages/store/types/@ember/array/proxy.d.ts
  tsconfig.json
Labels: ts-review, target:canary, typescript, skip-changelog

#7954 port more types work over from #7585
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/request-state-service-test.ts
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/adapter/addon/index.ts
  packages/adapter/addon/json-api.ts
  packages/adapter/addon/rest.ts
  packages/model/addon/-private/errors.ts
  packages/model/addon/-private/system/many-array.ts
  packages/model/addon/-private/system/promise-belongs-to.js
  packages/model/addon/-private/system/promise-belongs-to.ts
  packages/model/addon/-private/system/promise-many-array.ts
  packages/private-build-infra/src/utilities/rollup-private-module.js
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/record-data/types/@ember/polyfills/index.d.ts
  packages/record-data/types/@ember/runloop/index.d.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/promise-proxies.ts
  packages/store/addon/-private/system/promise-proxy-base.d.ts
  packages/store/addon/-private/system/promise-proxy-base.js
  packages/store/addon/-private/system/record-array-manager.ts
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js
  packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.ts
  packages/store/addon/-private/system/record-arrays/record-array.ts
  packages/store/addon/-private/system/record-data-for.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/snapshot-record-array.ts
  packages/store/addon/-private/system/store/internal-model-factory.ts
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/store/addon/-private/system/store/serializer-response.ts
  packages/store/addon/-private/ts-interfaces/ds-model.ts
  packages/store/addon/-private/ts-interfaces/minimum-adapter-interface.ts
  packages/store/addon/-private/ts-interfaces/minimum-serializer-interface.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
  packages/store/addon/-private/ts-interfaces/record-instance.ts
  packages/store/addon/-private/ts-interfaces/store.ts
  packages/store/addon/-private/utils/promise-record.ts
  packages/store/types/@ember/array/-private/enumerable.d.ts
  packages/store/types/@ember/array/index.d.ts
  packages/store/types/@ember/object/promise-proxy-mixin.d.ts
  packages/store/types/@ember/object/proxy.d.ts
  packages/store/types/@ember/runloop/-private/backburner.d.ts
  packages/store/types/@ember/runloop/index.d.ts
  tsconfig.json
Labels: target:canary, changelog:chore, typescript

#7970 chore: remove unused evented infra
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: target:canary, changelog:cleanup

#7902 test for async hasMany does not trigger relationship fetch
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/relationships/has-many-test.js
Labels: Bug, target:canary, changelog:bugfix
