Repository warp-drive-data/warp-drive, pull requests merged in 2022-12, with the labels that each got.

#8335 fix: <Cache>.changedAttrs should be empty if no local mutations exist
  packages/record-data/addon/-private/record-data.ts
  tests/main/tests/unit/model-test.js
Labels: target:release, target:canary, target:lts, changelog:bugfix

#8323 fix: Only remove object(s) from record array if in collection #8318
  packages/store/addon/-private/record-arrays/identifier-array.ts
  tests/main/tests/integration/relationships/has-many-test.js
Labels: target:canary, target:lts, changelog:bugfix

#8336 fix: dont notify RecordArrayManager if deletion already accounted
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  tests/main/tests/integration/record-array-test.js
Labels: target:canary, target:lts, changelog:bugfix

#7900 fix: rollbackAttributes|unloadRecord during hasMany forEach should not error
  packages/store/addon/-private/record-arrays/identifier-array.ts
  tests/main/tests/unit/model/relationships/has-many-test.js
Labels: target:canary, changelog:bugfix

#7668 feat: allow .load()ing sync relationships
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  tests/main/tests/integration/references/belongs-to-test.js
Labels: target:canary, changelog:feat

#8340 test: show that pushing data in can move a record to committed and clean
  tests/main/tests/integration/records/edit-record-test.js
Labels: target:canary, changelog:test

#8341 fix: add meaningful error and proper rejection for id assertion during createRecord commit
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/store-service.ts
  tests/main/tests/integration/records/save-test.js
Labels: target:canary, changelog:bugfix

#8342 fix: assign preload data always
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/store-service.ts
  tests/main/tests/integration/records/load-test.js
Labels: target:canary, changelog:feat

#8343 test: show #5882 is no longer the case
  tests/main/tests/unit/model-test.js
Labels: target:canary, changelog:test

#8344 fix: improve object stringify and verbiage for relationship identifier errors
  packages/record-data/addon/-private/graph/-utils.ts
  tests/main/tests/integration/relationships/belongs-to-test.js
  tests/main/tests/integration/relationships/has-many-test.js
Labels: target:canary, changelog:bugfix

#8345 fix: give more meaningful error if id matches but is number instead of string
  packages/record-data/addon/-private/record-data.ts
Labels: target:canary, changelog:bugfix

#8346 fix: Schema.eachTransformedAttribute API should match Model.eachTransformedAttribute
  ember-data-types/q/ds-model.ts
  packages/store/addon/-private/legacy-model-support/shim-model-class.ts
  packages/store/addon/-private/store-service.ts
  tests/main/tests/integration/store/shim-model-test.js
Labels: target:canary, changelog:bugfix

#8347 feat: don't extend EmberObject/Service for Store
  packages/store/addon/-private/store-service.ts
  tests/main/tests/integration/application-test.js
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/record-data/store-wrapper-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/main/tests/unit/store/asserts-test.js
Labels: target:canary, changelog:feat

#8348 fix: don't use isEqual from @ember/utils for comparing cache values
  packages/record-data/addon/-private/record-data.ts
Labels: target:canary, changelog:bugfix

#8354 fix: improve error/deprecation messaging for inverse fields
  packages/model/src/-private/belongs-to.js
  packages/model/src/-private/has-many.js
Labels: target:canary, changelog:bugfix

#8357 chore: update package flags
  package.json
  packages/model/package.json
  packages/model/src/-private/legacy-relationships-support.ts
  packages/private-build-infra/addon/available-packages.ts
  packages/private-build-infra/addon/index.ts
  packages/store/package.json
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/network/fetch-manager.ts
  packages/store/src/-private/network/snapshot.ts
  packages/store/src/-private/store-service.ts
  patches/@embroider__macros@1.10.0.patch
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/docs/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, changelog:chore

#8358 feat: Store.notifications
  packages/model/src/-private/model.js
  packages/model/src/-private/record-state.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/legacy-model-support/record-reference.ts
  packages/store/src/-private/managers/record-data-store-wrapper.ts
  packages/store/src/-private/managers/record-notification-manager.ts
  packages/store/src/-private/store-service.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:feat

#8359 chore: rebrand RecordData types to Cache
  .eslintrc.js
  ember-data-types/q/cache-store-wrapper.ts
  ember-data-types/q/cache.ts
  packages/-ember-data/addon/-private/index.ts
  packages/graph/package.json
  packages/graph/src/-private/graph/-utils.ts
  packages/graph/src/-private/graph/graph.ts
  packages/graph/src/-private/graph/index.ts
  packages/graph/src/-private/graph/operations/merge-identifier.ts
  packages/graph/src/-private/graph/operations/replace-related-records.ts
  packages/json-api/src/-private.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/record-state.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/caches/record-data-for.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/managers/cache-store-wrapper.ts
  packages/store/src/-private/network/snapshot.ts
  packages/store/src/-private/store-service.ts
  tests/adapter-encapsulation/app/services/store.js
  tests/docs/fixtures/expected.js
  tests/main/tests/helpers/accessors.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/record-data/store-wrapper-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/serializer-encapsulation/app/services/store.js
  tsconfig.json
Labels: target:canary, changelog:chore
