Repository warp-drive-data/warp-drive, pull requests merged in 2022-08, with the labels that each got.

#8108 fix earlier versions of node-14
  packages/private-build-infra/src/utilities/require-module.js
Labels: target:beta, target:release, target:canary, changelog:bugfix

#8114 implement store portion of v2 cache
  ember-data-types/q/record-data-schemas.ts
  ember-data-types/q/record-data-store-wrapper.ts
  ember-data-types/q/record-data.ts
  ember-data-types/q/relationship-record-data.ts
  ember-data-types/q/schema-definition-service.ts
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/helpers/accessors.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model-test.js
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/legacy-data-fetch.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/record-state.ts
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/record-data/addon/-private/graph/-edge-definition.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/legacy-model-support/record-reference.ts
  packages/store/addon/-private/managers/record-data-store-wrapper.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
  packages/store/addon/-private/store-service.ts
  packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
  packages/unpublished-serializer-encapsulation-test-app/app/services/store.js
Labels: 🌲 Project Trim 🌲, target:canary, changelog:feat, changelog:doc, changelog:deprecation, 5.0 Roadmap

#8116 Clear subscriptions once unsubscribed, don't unnecessarily churn on subscriptions
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix

#8109 add optional polyfill
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/utils/uuid-polyfill.ts
Labels: target:beta, target:release, target:canary, changelog:bugfix

#8113 fix: account for multi-options-per-identifer possibility
  .github/workflows/main.yml
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/record-data/addon/-private/record-data.ts
  packages/serializer/addon/json-api.js
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/legacy-model-support/record-reference.ts
  packages/store/addon/-private/legacy-model-support/shim-model-class.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/network/snapshot.ts
  packages/unpublished-adapter-encapsulation-test-app/tests/integration/coalescing-test.js
  packages/unpublished-serializer-encapsulation-test-app/tests/integration/relationships-test.js
Labels: target:beta, target:release, changelog:bugfix

#8117 fix: move defaultValue into RecordData to better encapsulate and prevent eager instantiations
  ember-data-types/q/record-data-record-wrapper.ts
  ember-data-types/q/record-data.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model-test.js
  packages/model/addon/-private/attr.js
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
  packages/store/addon/-private/network/snapshot.ts
Labels: target:canary, changelog:cleanup

#8120 Typescript & encapsulation improvements in advance of cache v2
  .eslintrc.js
  ember-data-types/q/ember-data-json-api.ts
  ember-data-types/q/record-data-record-wrapper.ts
  ember-data-types/q/record-data.ts
  ember-data-types/q/relationship-record-data.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/many-array.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/network/snapshot.ts
  packages/store/addon/-private/store-service.ts
  tsconfig.json
Labels: 🌲 Project Trim 🌲, target:canary, changelog:cleanup, 5.0 Roadmap

#8118 fix: reopen deprecation should properly pass original arguments
  packages/model/addon/-private/model.js
Labels: target:canary, changelog:bugfix

#8124 [DOC] typo fix
  ember-data-types/q/schema-definition-service.ts
Labels: target:canary, changelog:doc

#8121 Documentation Upgrades
  README.md
  packages/-ember-data/addon/index.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/addon/debugging.ts
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
Labels: target:canary, changelog:doc

#8122 v2.1 cache
  ember-data-types/q/record-data.ts
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/integration/records/delete-record-test.js
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/relationships/inverse-relationships-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/adapter/addon/-private/build-url-mixin.ts
  packages/adapter/addon/index.ts
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/many-array.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/notify-changes.ts
  packages/model/addon/-private/record-state.ts
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/record-data/tests/integration/graph/edge-test.ts
  packages/serializer/addon/json-api.js
  packages/serializer/addon/json.js
  packages/serializer/addon/rest.js
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/legacy-model-support/record-reference.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/managers/record-data-manager.ts
  packages/store/addon/-private/managers/record-data-store-wrapper.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/network/snapshot.ts
  packages/store/addon/-private/record-arrays/record-array.ts
  packages/store/addon/-private/store-service.ts
  packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
  packages/unpublished-relationship-performance-test-app/app/templates/application.hbs
  packages/unpublished-serializer-encapsulation-test-app/app/services/store.js
Labels: 🌲 Project Trim 🌲, target:canary, changelog:feat, changelog:doc, changelog:deprecation, 5.0 Roadmap

#8130 chore: relationship cleanup
  .eslintrc.js
  packages/-ember-data/addon/-private/index.ts
  packages/-ember-data/addon/index.js
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/helpers/accessors.ts
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/relationships/many-to-many-test.js
  packages/-ember-data/tests/integration/relationships/one-to-one-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/record-state.ts
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/add-to-related-records.ts
  packages/record-data/addon/-private/graph/operations/remove-from-related-records.ts
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/record-data/addon/-private/relationships/state/has-many.ts
  packages/record-data/addon/-private/relationships/state/implicit.ts
  packages/record-data/tests/integration/graph/edge-removal/helpers.ts
  packages/record-data/tests/integration/graph/edge-removal/setup.ts
  packages/record-data/tests/integration/graph/operations-test.ts
  tsconfig.json
Labels: target:canary, changelog:chore

#8128 fix: backgroundReloads should not affect recordIsLoaded (#8125)
  packages/-ember-data/tests/integration/store-test.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/store-service.ts
Labels: target:canary, changelog:test, changelog:bugfix

#8135 feat: efficient manager
  packages/-ember-data/tests/integration/peek-all-test.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/managers/record-data-store-wrapper.ts
  packages/store/addon/-private/record-arrays/adapter-populated-record-array.ts
  packages/store/addon/-private/record-arrays/record-array.ts
  packages/store/addon/-private/store-service.ts
Labels: target:canary, changelog:perf

#8138 [DOC] typo in identifier initializer documentation
  ember-data-types/q/identifier.ts
Labels: target:canary, changelog:doc

#8140 perf: optimize factory.create
  packages/-ember-data/tests/unit/model-test.js
  packages/model/addon/-private/model.js
  packages/store/addon/-private/store-service.ts
Labels: target:canary, changelog:perf

#8139 perf: eliminate private backburner
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/unit/custom-class-support/custom-class-model-test.ts
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/many-array.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/graph/operations/update-relationship.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/tests/integration/graph/edge-test.ts
  packages/record-data/tests/integration/graph/operations-test.ts
  packages/store/addon/-private/backburner.js
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/managers/record-data-store-wrapper.ts
  packages/store/addon/-private/store-service.ts
  scripts/benchmark-push.js
Labels: target:canary, changelog:perf

#8141 perf: use Map instead of WeakCache
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/model/addon/-private/belongs-to.js
  packages/model/addon/-private/has-many.js
  packages/model/addon/-private/model.js
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/caches/record-data-for.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/legacy-model-support/shim-model-class.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
  packages/store/addon/-private/record-arrays/record-array.ts
  packages/store/addon/-private/store-service.ts
  packages/store/addon/-private/utils/weak-cache.ts
Labels: target:canary, changelog:perf

#8142 perf: cache access
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/integration/identifiers/scenarios-test.ts
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/record-array-test.js
  packages/-ember-data/tests/integration/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/unit/record-arrays/adapter-populated-record-array-test.js
  packages/-ember-data/tests/unit/record-arrays/record-array-test.js
  packages/-ember-data/tests/unit/system/snapshot-record-array-test.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/network/finders.js
  packages/store/addon/-private/network/request-cache.ts
  packages/store/addon/-private/network/snapshot-record-array.ts
  packages/store/addon/-private/record-arrays/adapter-populated-record-array.ts
  packages/store/addon/-private/record-arrays/record-array.ts
  packages/store/addon/-private/store-service.ts
  packages/store/addon/-private/utils/is-non-empty-string.ts
Labels: target:canary, changelog:perf

#8144 Backport add optional polyfill (#8109)
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/store/addon/-private/identifier-cache.ts
  packages/store/addon/-private/utils/uuid-polyfill.ts
Labels: changelog:bugfix, backport-release

#8145 fix earlier versions of node-14 (#8108)
  packages/private-build-infra/src/utilities/require-module.js
Labels: changelog:bugfix, backport-release

#8149 perf: optimize unload and relationships
  packages/-ember-data/tests/acceptance/relationships/has-many-test.js
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/records/create-record-test.js
  packages/-ember-data/tests/integration/relationships/one-to-many-test.js
  packages/-ember-data/tests/integration/relationships/promise-many-array-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/many-array.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/promise-many-array.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
  packages/record-data/addon/-private/graph/-utils.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/store-service.ts
Labels: target:canary, changelog:perf

#8151 chore: add release perf check
  .github/workflows/perf-over-release.yml
  scripts/perf-tracking/create-comment.js
Labels: target:canary, changelog:chore

#8148 Clear subscriptions once unsubscribed, don't unnecessarily churn on subscriptions
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
Labels: changelog:bugfix, backport-release

#8129 feat: deprecate v1 cache
  @types/ember-data-qunit-asserts/index.d.ts
  ember-data-types/q/record-data.ts
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/integration/record-array-manager-test.js
  packages/-ember-data/tests/integration/record-data/record-data-errors-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-state-test.ts
  packages/-ember-data/tests/integration/record-data/record-data-test.ts
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/record-data/unloading-record-data-test.js
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/records/relationship-changes-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/canary-features/addon/default-features.ts
  packages/canary-features/addon/index.ts
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/managers/record-data-manager.ts
  packages/store/addon/-private/record-arrays/identifier-array.ts
  packages/store/addon/-private/store-service.ts
  packages/unpublished-adapter-encapsulation-test-app/app/services/store.js
  packages/unpublished-serializer-encapsulation-test-app/app/services/store.js
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
Labels: 🌲 Project Trim 🌲, target:canary, changelog:feat, changelog:deprecation, 5.0 Roadmap
