Repository warp-drive-data/warp-drive, pull requests merged in 2022-07, with the labels that each got.

#8026 Deactivate Perf Benchmarks until Fixed
  .github/workflows/perf-check.yml
Labels: target:canary, changelog:chore

#8008 schedule watchTypeIfUnseen to prevent loop
  packages/-ember-data/tests/integration/debug-adapter-test.js
  packages/debug/addon/index.js
Labels: target:canary, target:lts, changelog:bugfix

#8040 bump some deps
  package.json
  packages/private-build-infra/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  yarn.lock
Labels: dependencies, target:canary, skip-changelog

#8042 fix: RecordState cleanup, drop requireESM and node12
  .eslintrc.js
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  package.json
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
  packages/-ember-data/tests/integration/records/delete-record-test.js
  packages/-ember-data/tests/integration/records/error-test.js
  packages/-ember-data/tests/integration/records/load-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/unit/model-test.js
  packages/-ember-data/tests/unit/private-test.js
  packages/adapter/node-tests/fixtures/addon/package/package.json
  packages/adapter/node-tests/fixtures/app/package/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/addon/-private/model.js
  packages/model/addon/-private/record-state.ts
  packages/model/node-tests/fixtures/addon/package/package.json
  packages/model/node-tests/fixtures/app/package/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/packages.js
  packages/private-build-infra/src/utilities/require-module.js
  packages/record-data/package.json
  packages/serializer/node-tests/fixtures/addon/package/package.json
  packages/serializer/node-tests/fixtures/app/package/package.json
  packages/serializer/package.json
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/ts-interfaces/record-data.ts
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
  yarn.lock
Labels: target:canary, changelog:bugfix

#7971 chore: remove the state machine
  packages/-ember-data/addon/-private/index.ts
  packages/-ember-data/addon/index.js
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/-ember-data/tests/acceptance/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
  packages/-ember-data/tests/integration/record-data/store-wrapper-test.ts
  packages/-ember-data/tests/integration/records/property-changes-test.js
  packages/-ember-data/tests/integration/records/save-test.js
  packages/-ember-data/tests/integration/references/has-many-test.js
  packages/-ember-data/tests/integration/references/record-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/adapters/rest-adapter/group-records-for-find-many-test.js
  packages/-ember-data/tests/unit/model/errors-test.js
  packages/-ember-data/tests/unit/states-test.js
  packages/-ember-data/tests/unit/store/async-leak-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/-ember-data/tests/unit/store/unload-test.js
  packages/model/addon/-private/attr.js
  packages/model/addon/-private/errors.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/record-state.ts
  packages/model/addon/-private/system/many-array.ts
  packages/record-data/addon/-private/record-data.ts
  packages/record-data/addon/-private/relationships/state/belongs-to.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/system/core-store.ts
  packages/store/addon/-private/system/fetch-manager.ts
  packages/store/addon/-private/system/model/internal-model.ts
  packages/store/addon/-private/system/model/states.js
  packages/store/addon/-private/system/record-array-manager.ts
  packages/store/addon/-private/system/references/belongs-to.ts
  packages/store/addon/-private/system/references/has-many.ts
  packages/store/addon/-private/system/references/record.ts
  packages/store/addon/-private/system/store/finders.js
  packages/store/addon/-private/system/store/record-data-store-wrapper.ts
  packages/unpublished-test-infra/src/testem/custom-dot-reporter.js
Labels: target:canary, changelog:cleanup

#7901 fix: waiter should be always on
  packages/-ember-data/tests/integration/adapter/queries-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/store/async-leak-test.js
  packages/store/addon/-private/system/core-store.ts
Labels: target:canary, changelog:bugfix

#8073 [DOC] update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: target:canary, changelog:chore

#8083 [BUGFIX] Serialize null array items as empty strings
  packages/-ember-data/tests/unit/utils/serialize-query-params-test.js
  packages/adapter/addon/-private/utils/serialize-query-params.ts
Labels: target:canary, target:lts, changelog:bugfix, target:lts-prev

#8089 fix: unpin yarn for consumers
  packages/-ember-data/package.json
  packages/adapter/node-tests/fixtures/addon/package/package.json
  packages/adapter/node-tests/fixtures/app/package/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/node-tests/fixtures/addon/package/package.json
  packages/model/node-tests/fixtures/app/package/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/node-tests/fixtures/addon/package/package.json
  packages/serializer/node-tests/fixtures/app/package/package.json
  packages/serializer/package.json
  packages/store/package.json
Labels: target:beta, target:release, target:canary, changelog:bugfix

#7607 test: defined post model individually per test
  packages/-ember-data/tests/integration/adapter/rest-adapter-test.js
Labels: target:canary, skip-changelog

#7634 [CHORE]: Modernized store-adapter-test
  packages/-ember-data/tests/integration/adapter/store-adapter-test.js
Labels: target:canary, changelog:chore

#8092 deprecation: Model.reopen/reopenClass and eager static fields lookups
  packages/-ember-data/tests/deprecations/deprecate-early-static-test.js
  packages/-ember-data/tests/deprecations/deprecate-reopen-class-test.js
  packages/-ember-data/tests/deprecations/deprecate-reopen-test.js
  packages/-ember-data/tests/integration/debug-adapter-test.js
  packages/-ember-data/tests/integration/records/error-test.js
  packages/-ember-data/tests/integration/records/unload-test.js
  packages/-ember-data/tests/integration/relationships/belongs-to-test.js
  packages/-ember-data/tests/integration/relationships/has-many-test.js
  packages/-ember-data/tests/integration/serializers/json-api-serializer-test.js
  packages/-ember-data/tests/integration/serializers/json-serializer-test.js
  packages/-ember-data/tests/integration/serializers/rest-serializer-test.js
  packages/-ember-data/tests/integration/store-test.js
  packages/-ember-data/tests/unit/many-array-test.js
  packages/-ember-data/tests/unit/model/relationships/has-many-test.js
  packages/-ember-data/tests/unit/model/rollback-attributes-test.js
  packages/-ember-data/tests/unit/store/adapter-interop-test.js
  packages/-ember-data/tests/unit/store/push-test.js
  packages/-ember-data/tests/unit/store/serializer-for-test.js
  packages/-ember-data/tests/unit/store/unload-test.js
  packages/-ember-data/tests/unit/utils-test.js
  packages/model/addon/-private/model-for-mixin.ts
  packages/model/addon/-private/model.js
  packages/private-build-infra/addon/current-deprecations.ts
  packages/private-build-infra/addon/deprecations.ts
Labels: target:canary, changelog:cleanup, 🔌 Project Unplug 🔌, changelog:deprecation
