Repository warp-drive-data/warp-drive, pull requests merged in 2022-10, with the labels that each got.

#8198 fix: thread config from host to nested deps
  packages/-ember-data/ember-cli-build.js
  packages/private-build-infra/src/addon-build-config-for-data-package.js
Labels: target:release, target:canary, changelog:bugfix, target:release-prev

#8199 [backport release-prev] fix: thread polyfillUUID config through nested deps
  packages/private-build-infra/src/addon-build-config-for-data-package.js
Labels: changelog:bugfix, backport-old-release

#8200 [Backport Release]: fix: thread polyfillUUID config through nested deps
  packages/private-build-infra/src/addon-build-config-for-data-package.js
Labels: changelog:bugfix, backport-release

#8201 feat: enhance debug logging abilities
  README.md
  packages/-ember-data/addon/index.js
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/node-tests/fixtures/expected.js
  packages/private-build-infra/addon/debugging.ts
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/store-service.ts
Labels: target:canary, changelog:feat

#8206 fix: fix MandatorySetter error for Proxied PromiseProxy, silence ember-concurrency deprecations
  packages/-ember-data/.npmignore
  packages/-ember-data/tests/acceptance/tracking-promise-flags-test.js
  packages/-ember-data/tests/integration/records/save-test.js
  packages/model/addon/-private/deprecated-promise-proxy.ts
  packages/store/addon/-private/proxies/promise-proxies.ts
Labels: target:release, target:canary, changelog:bugfix

#8211 fix: ManyReference.value should recompute when data is first received
  packages/-ember-data/tests/integration/references/autotracking-test.js
  packages/model/addon/-private/references/has-many.ts
Labels: target:release, target:canary, changelog:bugfix

#8213 fix: inspector type detection #8205
  packages/debug/addon/setup.js
Labels: target:release, target:canary, changelog:bugfix

#8215 fix: inspector type detection 2. attempt #8205
  packages/debug/addon/setup.js
Labels: target:release, target:canary, changelog:bugfix

#8214 fix: 4.7 backtracking render error
  .eslintrc.js
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  package.json
  packages/-ember-data/index.js
  packages/-ember-data/package.json
  packages/-ember-data/tests/acceptance/tracking-create-record-test.js
  packages/model/addon/-private/record-state.ts
  packages/model/addon/index.ts
  packages/model/index.js
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/record-arrays/identifier-array.ts
  packages/store/index.js
  packages/store/package.json
  packages/tracking/LICENSE.md
  packages/tracking/README.md
  packages/tracking/addon-main.js
  packages/tracking/babel.config.json
  packages/tracking/lib/transform-ext.js
  packages/tracking/package.json
  packages/tracking/rollup.config.mjs
  packages/tracking/src/-private.ts
  packages/tracking/src/.gitkeep
  packages/tracking/src/index.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/package.json
  root-tsconfig.json
  yarn.lock
Labels: target:release, target:canary, changelog:feat, changelog:bugfix

#8222 Invoke ember-auto-import analyzer
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/utilities/rollup-private-module.js
Labels: target:canary, changelog:chore

#8229 chore: fix asset-size check for pnpm
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/partner-tests.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  .yarnrc
  packages/unpublished-eslint-rules/package.json
  scripts/asset-size-tracking/src/create-comment-text.js
Labels: target:canary, skip-changelog, ci-assetsize, ci-perf

#8236 chore: bump pnpm version
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/partner-tests.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-adapter-encapsulation-test-app/package.json
  packages/unpublished-debug-encapsulation-test-app/package.json
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-model-encapsulation-test-app/package.json
  packages/unpublished-record-data-encapsulation-test-app/package.json
  packages/unpublished-relationship-performance-test-app/package.json
  packages/unpublished-serializer-encapsulation-test-app/package.json
  packages/unpublished-test-infra/package.json
Labels: dependencies, target:canary, skip-changelog

#8243 chore: build with ts directly
  package.json
  packages/-ember-data/ember-cli-build.js
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/index.js
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/index.js
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/utilities/rollup-private-module.js
  packages/record-data/ember-cli-build.js
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-fastboot-test-app/ember-cli-build.js
  packages/unpublished-fastboot-test-app/package.json
  packages/unpublished-test-infra/ember-cli-build.js
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
Labels: target:canary, changelog:chore

#8244 chore: remove uneeded dep on ember-cli-test-info
  packages/debug/package.json
  packages/record-data/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
Labels: target:canary, changelog:chore

#8247 chore: simplify addons
  package.json
  packages/canary-features/package.json
  packages/store/.ember-cli
  packages/store/.watchmanconfig
  packages/store/config/environment.js
  packages/store/ember-cli-build.js
  packages/store/package.json
  pnpm-lock.yaml
Labels: target:canary, changelog:chore

#8248 chore: move serializer blueprint tests to new location
  .eslintrc.js
  packages/serializer/.ember-cli
  packages/serializer/.watchmanconfig
  packages/serializer/config/environment.js
  packages/serializer/ember-cli-build.js
  packages/serializer/package.json
  pnpm-lock.yaml
  tests/blueprints/README.md
  tests/blueprints/node-tests/blueprints/serializer-test.js
  tests/blueprints/node-tests/blueprints/transform-test.js
  tests/blueprints/node-tests/fixtures/addon/package/package.json
  tests/blueprints/node-tests/fixtures/app/package/package.json
  tests/blueprints/node-tests/fixtures/serializer-test/application-default.js
  tests/blueprints/node-tests/fixtures/serializer-test/foo-default.js
  tests/blueprints/node-tests/fixtures/serializer-test/foo-mocha-0.12.js
  tests/blueprints/node-tests/fixtures/serializer-test/mocha-rfc232-addon.js
  tests/blueprints/node-tests/fixtures/serializer-test/mocha-rfc232.js
  tests/blueprints/node-tests/fixtures/serializer-test/rfc232-addon.js
  tests/blueprints/node-tests/fixtures/serializer-test/rfc232.js
  tests/blueprints/node-tests/fixtures/transform-test/default.js
  tests/blueprints/node-tests/fixtures/transform-test/mocha-0.12.js
  tests/blueprints/node-tests/fixtures/transform-test/mocha-rfc232-addon.js
  tests/blueprints/node-tests/fixtures/transform-test/mocha-rfc232.js
  tests/blueprints/node-tests/fixtures/transform-test/rfc232-addon.js
  tests/blueprints/node-tests/fixtures/transform-test/rfc232.js
  tests/blueprints/package.json
Labels: target:canary, changelog:chore

#8253 chore: bump ember-source, silence peer-dep issues
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/record-data-encapsulation/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, changelog:chore

#8261 feat: add identifier data to Reference public API
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:feat

#8264 fix: fast-push should adjust end based on start
  packages/store/addon/-private/managers/record-array-manager.ts
  tests/main/tests/unit/fast-push-test.js
Labels: target:canary, changelog:bugfix, ci-perf

#8269 chore: improve renovate experience
  .github/renovate.json
Labels: dependencies, target:canary, skip-changelog

#8275 chore: update node, pnpm, volta
  .github/actions/setup/action.yml
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-eslint-rules/package.json
  packages/unpublished-test-infra/package.json
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/docs/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/record-data-encapsulation/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8278 chore: cleanup pnpm configuration, polish test harness
  .github/actions/setup/action.yml
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/compat-tests.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  .npmrc
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  patches/@embroider__macros@1.9.0.patch
  pnpm-lock.yaml
  scripts/publish.js
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/main/package.json
  tests/main/tests/integration/application-test.js
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/record-data-encapsulation/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, changelog:chore

#8255 Convert existence checks to macros (take 2)
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/debug-macros.js
  packages/private-build-infra/src/debugging.js
  packages/private-build-infra/src/deprecations.js
  packages/private-build-infra/src/packages.js
  packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
  packages/private-build-infra/src/transforms/package.json
  packages/private-build-infra/src/utilities/require-module.js
Labels: target:canary, changelog:feat, 5.0 Roadmap

#8282 chore: Debug Flag Conversion to Macros
  packages/private-build-infra/src/debug-macros.js
  packages/private-build-infra/src/transforms/babel-plugin-convert-debug-flags-macros/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-deprecations/index.js
  packages/store/addon/-private/caches/identifier-cache.ts
  packages/store/addon/-private/managers/record-notification-manager.ts
  tests/main/ember-cli-build.js
Labels: target:canary, changelog:feat, 5.0 Roadmap, ci-assetsize

#8284 chore: macros for DEBUG, assertPolymorphicType, HAS_DEBUG_PACKAGE
  packages/model/addon/-private/debug/assert-polymorphic-type.js
  packages/model/addon/-private/legacy-data-fetch.js
  packages/model/addon/-private/legacy-relationships-support.ts
  packages/model/addon/-private/model.js
  packages/model/addon/-private/references/belongs-to.ts
  packages/model/addon/-private/references/has-many.ts
  packages/model/addon/-private/relationship-meta.ts
  packages/model/index.js
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/debug-macros.js
  packages/private-build-infra/src/features.js
  packages/private-build-infra/src/stripped-build-plugins.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-debug-env/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-logging/index.js
  packages/record-data/addon/-private/coerce-id.ts
  packages/record-data/addon/-private/debug/assert-polymorphic-type.js
  packages/record-data/addon/-private/graph/operations/add-to-related-records.ts
  packages/record-data/addon/-private/graph/operations/replace-related-record.ts
  packages/record-data/addon/-private/graph/operations/replace-related-records.ts
  packages/record-data/index.js
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/index.js
  packages/unpublished-test-infra/addon-test-support/deprecated-test.js
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/ember-cli-build.js
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/full-data-asset-size-app/ember-cli-build.js
  tests/graph/ember-cli-build.js
  tests/main/ember-cli-build.js
  tests/main/tests/unit/debug-test.js
  tests/main/tests/unit/utils-test.js
  tests/model-encapsulation/ember-cli-build.js
Labels: target:canary, changelog:feat, 5.0 Roadmap, ci-assetsize
