Repository warp-drive-data/warp-drive, pull requests merged in 2022-11, with the labels that each got.

#8291 Update changelog for 4.8.0
  CHANGELOG.md
  RELEASE.md
  lerna.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/canary-features/package.json
  packages/debug/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/record-data/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-eslint-rules/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  scripts/publish.js
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/docs/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/record-data-encapsulation/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, skip-changelog

#8298 Fix peer deps during publish
  .gitignore
  RELEASE.md
  package.json
  pnpm-lock.yaml
  scripts/publish.js
Labels: target:canary, changelog:bugfix

#8301 assert missing crypto.randomUUID
  packages/store/addon/-private/caches/identifier-cache.ts
Labels: target:canary, changelog:doc

#8304 chore: fix root version and remove lint-changed
  package.json
  pnpm-lock.yaml
  scripts/lint-changed-js.js
Labels: target:canary, skip-changelog

#8306 fix: dont skip LiveArray remove if pending queue is not empty
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  packages/store/addon/-private/managers/record-array-manager.ts
  tests/main/tests/integration/peek-all-test.js
Labels: target:release, target:canary, changelog:bugfix, ci-perf

#8307 fix: use join vs run for deleteRecord destroy of new records
  packages/store/addon/-private/store-service.ts
  tests/main/tests/acceptance/relationships/has-many-test.js
Labels: target:release, target:canary, changelog:bugfix, ci-perf

#8308 fix: prepack addon tree for embroider
  .gitignore
  packages/tracking/addon-main.js
  packages/tracking/package.json
  pnpm-lock.yaml
Labels: target:release, target:canary, changelog:bugfix

#8314 fix: tracking package should not declare exports while v1
  .eslintignore
  .github/workflows/compat-tests.yml
  package.json
  packages/tracking/package.json
  pnpm-lock.yaml
  tests/embroider-basic-compat/.template-lintrc.js
  tests/embroider-basic-compat/README.md
  tests/embroider-basic-compat/app/app.ts
  tests/embroider-basic-compat/app/config/environment.d.ts
  tests/embroider-basic-compat/app/helpers/.gitkeep
  tests/embroider-basic-compat/app/index.html
  tests/embroider-basic-compat/app/models/.gitkeep
  tests/embroider-basic-compat/app/resolver.ts
  tests/embroider-basic-compat/app/router.ts
  tests/embroider-basic-compat/app/routes/.gitkeep
  tests/embroider-basic-compat/app/styles/app.css
  tests/embroider-basic-compat/app/templates/.gitkeep
  tests/embroider-basic-compat/app/templates/application.hbs
  tests/embroider-basic-compat/config/environment.js
  tests/embroider-basic-compat/config/optional-features.json
  tests/embroider-basic-compat/config/targets.js
  tests/embroider-basic-compat/ember-cli-build.js
  tests/embroider-basic-compat/package.json
  tests/embroider-basic-compat/testem.js
  tests/embroider-basic-compat/tests/acceptance/.gitkeep
  tests/embroider-basic-compat/tests/acceptance/visit-test.js
  tests/embroider-basic-compat/tests/helpers/.gitkeep
  tests/embroider-basic-compat/tests/index.html
  tests/embroider-basic-compat/tests/test-helper.js
Labels: target:release, target:canary, changelog:bugfix

#8316 docs: fix typo in README.md
  README.md
Labels: target:canary, changelog:doc

#8324 add @ember-data/tracking to Advanced Installation
  README.md
Labels: target:canary, changelog:doc
