Repository warp-drive-data/warp-drive, pull requests merged in 2023-04, with the labels that each got.

#8518 feat: enable request cache without hydration, better error handling by Fetch Handler
  ember-data-types/cache/cache.ts
  ember-data-types/cache/document.ts
  ember-data-types/cache/validation-error.ts
  ember-data-types/q/cache.ts
  ember-data-types/q/ds-model.ts
  ember-data-types/q/record-data-json-api.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/request/src/-private/types.ts
  packages/request/src/fetch.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/store-service.ts
  tests/main/app/cache-handler/store-package-setup-test.ts
  tests/main/public/assets/users/1.json
  tests/main/public/assets/users/list.json
  tests/main/tests/integration/cache-handler/meta-package-setup-test.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
Labels: target:canary, changelog:feat

#8529 tests: add tests for meta documents
  ember-data-types/q/cache-store-wrapper.ts
  ember-data-types/q/schema-service.ts
  packages/json-api/src/-private/cache.ts
  packages/request/src/-private/types.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/managers/cache-store-wrapper.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/store-service.ts
  tests/docs/fixtures/expected.js
  tests/json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/json-api/tests/integration/cache/meta-documents-test.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tsconfig.json
Labels: target:canary, changelog:test

#8531 feat: stable document identity
  .eslintrc.js
  ember-data-types/q/identifier.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/model.js
  packages/request/src/-private/types.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/store-service.ts
  packages/unpublished-test-infra/addon-test-support/todo.js
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
Labels: target:canary, changelog:feat

#8533 Feat: README files for Debug, Adapter and Serializer
  LICENSE.md
  packages/-ember-data/LICENSE.md
  packages/adapter/LICENSE.md
  packages/adapter/README.md
  packages/adapter/ember-data-logo-dark.svg
  packages/adapter/ember-data-logo-light.svg
  packages/adapter/package.json
  packages/debug/LICENSE.md
  packages/debug/README.md
  packages/debug/package.json
  packages/graph/LICENSE.md
  packages/graph/package.json
  packages/json-api/LICENSE.md
  packages/json-api/README.md
  packages/json-api/package.json
  packages/legacy-compat/LICENSE.md
  packages/legacy-compat/package.json
  packages/model/LICENSE.md
  packages/model/package.json
  packages/private-build-infra/LICENSE.md
  packages/request/LICENSE.md
  packages/request/package.json
  packages/serializer/LICENSE.md
  packages/serializer/README.md
  packages/serializer/ember-data-logo-dark.svg
  packages/serializer/ember-data-logo-light.svg
  packages/serializer/package.json
  packages/store/LICENSE.md
  packages/store/package.json
  packages/tracking/LICENSE.md
  packages/tracking/package.json
Labels: target:canary, changelog:doc

#8534 feat: Store and Graph READMEs + Store Overview
  packages/graph/README.md
  packages/model/package.json
  packages/store/README.md
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/index.ts
Labels: target:canary, changelog:doc

#8537 feat: documentation for Model, the RequestStateService + some docs fixes
  packages/graph/src/-private.ts
  packages/json-api/src/index.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/model/README.md
  packages/model/src/-private/model.js
  packages/model/src/-private/record-state.ts
  packages/model/src/index.ts
  packages/store/README.md
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/store-service.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:doc

#8538 chore: mark legacy docs as legacy
  packages/adapter/src/error.js
  packages/adapter/src/json-api.ts
  packages/adapter/src/rest.ts
  packages/serializer/src/json-api.js
  packages/serializer/src/json.js
  packages/serializer/src/rest.js
Labels: target:canary, changelog:doc

#8540 chore: updated/added some test coverage for RecordArray
  packages/-ember-data/addon/setup-container.ts
  pnpm-lock.yaml
  tests/main/app/app.ts
  tests/main/app/resolver.ts
  tests/main/package.json
  tests/main/tests/integration/record-array-test.js
  tests/main/tests/test-helper.js
Labels: target:canary, changelog:chore

#8539 feat: Rich Documents
  packages/request/src/-private/context.ts
  packages/request/src/-private/manager.ts
  packages/request/src/-private/types.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/document.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/cache-handler/meta-package-setup-test.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
Labels: target:canary, changelog:feat

#8542 feat: full-relationship definitions when scaffolding with blueprints
  packages/graph/src/-private/graph/graph.ts
  packages/model/blueprints/model/HELP.md
  packages/model/blueprints/model/index.js
  packages/model/src/-private/belongs-to.js
  tests/blueprints/tests/model-test.js
Labels: target:canary, changelog:feat

#8544 feat: error documents
  packages/json-api/src/-private/cache.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/document.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
Labels: target:canary, changelog:chore, changelog:feat

#8547 feat: Future.abort, additional tests and minor fixes
  packages/request/src/-private/context.ts
  packages/request/src/-private/future.ts
  packages/request/src/-private/types.ts
  packages/request/src/-private/utils.ts
  packages/store/src/-private/cache-handler.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/request/tests/integration/abort-test.ts
Labels: target:canary, changelog:feat

#8548 docs: updates to deprecation guides for remaining 4.x deprecations
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  packages/request/README.md
  packages/request/src/-private/manager.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/managers/cache-store-wrapper.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:doc

#8555 fix: fix polymorphic assertions when deprecated code is removed, improve polymorphic dx
  ember-data-types/q/schema-service.ts
  packages/graph/src/-private/debug/assert-polymorphic-type.js
  packages/graph/src/-private/graph/-edge-definition.ts
  packages/graph/src/-private/graph/graph.ts
  packages/graph/src/-private/graph/operations/replace-related-record.ts
  packages/model/src/-private/debug/assert-polymorphic-type.js
  packages/model/src/-private/model.js
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/references/belongs-to-test.js
  tests/main/tests/integration/references/has-many-test.js
  tests/main/tests/integration/relationships/belongs-to-test.js
  tests/main/tests/integration/relationships/has-many-test.js
  tests/main/tests/integration/relationships/inverse-relationships-test.js
  tests/main/tests/integration/relationships/polymorphic-mixins-belongs-to-test.js
  tests/main/tests/integration/relationships/polymorphic-mixins-has-many-test.js
  tests/main/tests/unit/system/relationships/polymorphic-relationship-payloads-test.js
  tsconfig.json
Labels: target:release, target:canary, changelog:bugfix

#8570 Fix: don't clear RecordArray if remaining record does not match the removed record
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/record-array-test.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix

#8572 [backport / beta] Fix: don't clear RecordArray if remaining record does not match the removed record
  README.md
  packages/-ember-data/addon/index.js
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/record-array-test.js
Labels: changelog:bugfix, backport-beta

#8571 [backport / release] Fix: don't clear RecordArray if remaining record does not match the removed record
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/record-array-test.js
Labels: changelog:bugfix, backport-release

#8573 [backport / lts-4-8] Fix: don't clear RecordArray if remaining record does not match the removed record
  packages/store/addon/-private/managers/record-array-manager.ts
  tests/main/tests/integration/record-array-test.js
Labels: changelog:bugfix, backport-lts
