Repository warp-drive-data/warp-drive, pull requests merged in 2023-07, with the labels that each got.

#8660 DX: Nicer backtracking errors
  packages/model/src/-private/record-state.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/tracking/addon-main.js
  packages/tracking/babel.config.js
  packages/tracking/babel.config.json
  packages/tracking/package.json
  packages/tracking/rollup.config.mjs
  packages/tracking/src/-private.ts
  pnpm-lock.yaml
  tests/main/tests/end-user-dx/meaningful-backtracking-errors-test.js
Labels: target:beta, target:canary, target:lts, changelog:feat, backport-lts

#8670 chore: add ROADMAP and update CONTRIBUTING
  CONTRIBUTING.md
  RELEASE.md
  ROADMAP.md
  contributing/become-a-contributor.md
  contributing/issues.md
  contributing/linking-to-applications.md
  contributing/rfc-process.md
  contributing/submitting-prs.md
Labels: target:canary, changelog:chore

#8671 Typo correction in ROADMAP.md
  ROADMAP.md
Labels: Documentation, target:canary, skip-changelog

#8672 chore: update roadmap for 5.3
  ROADMAP.md
Labels: target:canary, changelog:chore

#8677 chore: use ember-cli-htmlbars and update ember-cli-dependency-checker
  .github/renovate.json
  package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/fastboot/types/global.d.ts
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/main/tests/acceptance/record-array-test.js
  tests/main/tests/acceptance/relationships/belongs-to-test.js
  tests/main/tests/acceptance/relationships/has-many-test.js
  tests/main/tests/acceptance/relationships/tracking-record-state-test.js
  tests/main/tests/acceptance/tracking-create-record-test.js
  tests/main/tests/acceptance/tracking-model-id-test.js
  tests/main/tests/helpers/create-tracking-context.js
  tests/main/tests/helpers/watch-property.js
  tests/main/tests/integration/references/autotracking-test.js
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8678 chore: bump webpack
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8680 chore: bump @embroider/addon-dev
  packages/adapter/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  pnpm-lock.yaml
Labels: dependencies, target:canary, skip-changelog

#8679 chore: bump ember-auto-import
  package.json
  packages/-ember-data/package.json
  packages/debug/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8673 DX: Nicer backtracking errors
  packages/model/src/-private/record-state.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/tracking/addon-main.js
  packages/tracking/babel.config.js
  packages/tracking/babel.config.json
  packages/tracking/package.json
  packages/tracking/rollup.config.mjs
  packages/tracking/src/-private.ts
  pnpm-lock.yaml
  tests/main/tests/end-user-dx/meaningful-backtracking-errors-test.js
Labels: target:canary, changelog:feat

#8684 fix: unloadAll(void) should not destroy the notification manager
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/records/unload-test.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix

#8685 fix: unloadAll(void) should not destroy the notification manager (backports #8684)
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/records/unload-test.js
Labels: changelog:bugfix, backport-release

#8686 fix: unloadAll(void) should not destroy the notification manager (backports #8684)
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/records/unload-test.js
Labels: changelog:bugfix, backport-lts

#8696 chore: run pnpm update
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/builders/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8697 chore: use latest versions of transforms
  package.json
  packages/active-record/babel.config.json
  packages/active-record/package.json
  packages/adapter/babel.config.js
  packages/adapter/package.json
  packages/graph/babel.config.js
  packages/graph/package.json
  packages/json-api/babel.config.js
  packages/json-api/package.json
  packages/legacy-compat/babel.config.js
  packages/legacy-compat/package.json
  packages/model/babel.config.js
  packages/model/package.json
  packages/request-utils/babel.config.json
  packages/request-utils/package.json
  packages/request/babel.config.js
  packages/request/package.json
  packages/rest/babel.config.json
  packages/rest/package.json
  packages/serializer/babel.config.js
  packages/serializer/package.json
  packages/store/babel.config.js
  packages/store/package.json
  packages/tracking/babel.config.js
  packages/tracking/package.json
  pnpm-lock.yaml
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/main/tests/integration/store-test.js
  tests/main/tests/unit/promise-proxies-test.js
Labels: dependencies, target:canary, skip-changelog

#8703 fix: @ember-data/debug should declare its peer-dependency on @ember-data/store
  packages/debug/package.json
Labels: target:beta, target:release, target:canary, changelog:bugfix, backport-lts, lts-4-12

#8705 fix: make implicit relationship teardown following delete of related record safe
  packages/graph/src/-private/graph/graph.ts
  tests/graph/tests/integration/graph/unload-test.ts
Labels: target:beta, target:release, target:canary, changelog:bugfix, backport-lts, lts-4-12

#8704 fix: de-dupe coalescing when includes or adapterOptions is present but still use findRecord
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  tests/adapter-encapsulation/tests/integration/coalescing-test.js
Labels: target:beta, target:release, target:canary, changelog:bugfix, backport-lts, lts-4-12

#8708 fix: catch errors during didCommit in DEBUG
  packages/graph/src/-private/graph/graph.ts
  packages/model/src/-private/many-array.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/record-array-manager-test.js
  tests/main/tests/integration/records/new-record-unload-test.js
  tests/main/tests/integration/records/save-test.js
  tests/main/tests/integration/records/unload-test.js
Labels: target:beta, target:release, target:canary, changelog:bugfix, backport-lts, lts-4-12

#8499 chore: refactor model hook support to live in the model package
  ember-data-types/q/ds-model.ts
  packages/-ember-data/addon/-private/index.ts
  packages/adapter/src/-private/utils/serialize-into-hash.ts
  packages/adapter/src/index.ts
  packages/adapter/src/json-api.ts
  packages/adapter/src/rest.ts
  packages/graph/src/-private/graph/index.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/legacy-compat/src/legacy-network-handler/serializer-response.ts
  packages/model/rollup.config.mjs
  packages/model/src/-private.ts
  packages/model/src/-private/hooks.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model.js
  packages/model/src/-private/schema-provider.ts
  packages/model/src/-private/util.ts
  packages/model/src/hooks.ts
  packages/model/src/index.ts
  packages/store/package.json
  packages/store/rollup.config.mjs
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/legacy-model-support/schema-definition-service.ts
  packages/store/src/-private/store-service.ts
  tests/adapter-encapsulation/app/services/store.js
  tests/graph/app/services/store.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/serializer-encapsulation/app/services/store.js
  tsconfig.json
Labels: target:canary, changelog:chore, ci-assetsize

#8713 Notify on length when notifying that many-array has changed
  packages/model/addon/-private/system/many-array.js
Labels: changelog:bugfix, backport-lts-prev

#8716 feat: filterEmpty for query params
  packages/request-utils/src/index.ts
Labels: target:canary, changelog:feat

#8717 Switch from local and @types/ember types to ember-source types
  @types/@ember/array/-private/enumerable.d.ts
  @types/@ember/array/-private/mutable-enumerable.d.ts
  @types/@ember/array/-private/native-array.d.ts
  @types/@ember/array/index.d.ts
  @types/@ember/array/mutable.d.ts
  @types/@ember/array/proxy.d.ts
  @types/@ember/debug/index.d.ts
  @types/@ember/object/compat.d.ts
  @types/@ember/object/promise-proxy-mixin.d.ts
  @types/@ember/object/proxy.d.ts
  @types/@ember/runloop/-private/backburner.d.ts
  @types/@ember/runloop/index.d.ts
  @types/@ember/utils/index.d.ts
  @types/@ember/version.d.ts
  @types/ember/index.d.ts
  package.json
  packages/adapter/src/-private/build-url-mixin.ts
  packages/adapter/src/rest.ts
  packages/model/src/-private/errors.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/promise-belongs-to.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-deprecation.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-warning.ts
  pnpm-lock.yaml
  tests/main/tests/integration/model-errors-test.ts
Labels: target:canary, changelog:chore, typescript

#8724 chore: rename CacheStoreWrapper => CacheCapabilitiesManager to reflect its role
  ember-data-types/q/cache-store-wrapper.ts
  packages/-ember-data/addon/-private/index.ts
  packages/graph/src/-private/graph/-utils.ts
  packages/graph/src/-private/graph/graph.ts
  packages/graph/src/-private/graph/index.ts
  packages/json-api/src/-private/cache.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/managers/cache-capabilities-manager.ts
  packages/store/src/-private/store-service.ts
  tests/docs/fixtures/expected.js
  tests/graph/app/services/store.ts
  tests/json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/json-api/tests/integration/cache/meta-documents-test.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/helpers/accessors.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/record-data/store-wrapper-test.ts
  tsconfig.json
Labels: target:canary, changelog:doc

#8727 chore: fix peers and get perf-test-app running again
  package.json
  packages/-ember-data/package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tests/dummy/config/environment.js
  pnpm-lock.yaml
  tests/adapter-encapsulation/config/environment.js
  tests/blueprints/package.json
  tests/builders/config/environment.js
  tests/builders/package.json
  tests/debug-encapsulation/config/environment.js
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/config/environment.js
  tests/fastboot/config/environment.js
  tests/full-data-asset-size-app/config/environment.js
  tests/graph/config/environment.js
  tests/json-api-encapsulation/config/environment.js
  tests/json-api/config/environment.js
  tests/main/config/environment.js
  tests/model-encapsulation/config/environment.js
  tests/performance/config/environment.js
  tests/performance/ember-cli-build.js
  tests/performance/package.json
  tests/request/config/environment.js
  tests/serializer-encapsulation/config/environment.js
Labels: target:canary, changelog:chore

#8734 feat: Implement Strict Types and Id Deprecations
  packages/model/src/-private/belongs-to.js
  packages/model/src/-private/has-many.js
  packages/model/src/-private/util.ts
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  packages/serializer/package.json
  packages/serializer/rollup.config.mjs
  packages/serializer/src/-private.ts
  packages/serializer/src/-private/utils.ts
  packages/serializer/src/json-api.js
  packages/serializer/src/json.js
  packages/serializer/src/rest.js
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/utils/coerce-id.ts
  packages/store/src/-private/utils/normalize-model-name.ts
  pnpm-lock.yaml
  tests/main/tests/integration/backwards-compat/non-dasherized-lookups-test.js
  tests/main/tests/integration/client-id-generation-test.js
  tests/main/tests/integration/record-array-test.js
  tests/main/tests/integration/references/record-test.js
Labels: target:canary, changelog:deprecation

#8736 chore: refactor IdentityCache to make resource more opaque
  .eslintrc.js
  ember-data-types/q/identifier.ts
  packages/debug/addon/index.js
  packages/graph/src/-private/graph/-edge-definition.ts
  packages/graph/src/-private/graph/graph.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/serializer/src/index.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/caches/resource-utils.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/json-api/tests/integration/cache/meta-documents-test.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/ember-cli-build.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/identifiers/polymorphic-scenarios-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
  tests/main/tests/integration/record-array-test.js
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/records/rematerialize-test.js
  tests/main/tests/integration/store-test.js
  tests/performance/ember-cli-build.js
  tests/performance/package.json
  tsconfig.json
Labels: target:canary, changelog:cleanup, ci-perf

#8739 chore: migrate store/graph to strict types config
  .eslintrc.js
  ember-data-types/q/record-data-schemas.ts
  packages/graph/src/-private/coerce-id.ts
  packages/graph/src/-private/debug/assert-polymorphic-type.ts
  packages/graph/src/-private/graph/-edge-definition.ts
  packages/graph/src/-private/graph/-utils.ts
  packages/graph/src/-private/graph/operations/replace-related-records.ts
  packages/graph/src/-private/relationships/state/belongs-to.ts
  packages/graph/src/-private/relationships/state/has-many.ts
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/utils/coerce-id.ts
  packages/store/src/-private/utils/is-non-empty-string.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/serializer-encapsulation/tests/integration/push-payload-test.js
  tsconfig.json
Labels: target:canary, changelog:chore

#8744 add sortQueryParams, update roadmap with link to checklist
  ROADMAP.md
  packages/request-utils/src/index.ts
Labels: target:canary, changelog:feat

#8740 feat: saveRecord builders
  docs-generator/yuidoc.json
  ember-data-types/request.ts
  packages/active-record/package.json
  packages/active-record/src/-private/builders/-utils.ts
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/active-record/src/request.ts
  packages/json-api/src/-private/builders/-types.ts
  packages/json-api/src/-private/builders/-utils.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/json-api/src/request.ts
  packages/request-utils/src/index.ts
  packages/rest/package.json
  packages/rest/src/-private/builders/-types.ts
  packages/rest/src/-private/builders/-utils.ts
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/rest/src/request.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/builders/package.json
  tests/builders/tests/test-helper.js
  tests/builders/tests/unit/build-base-url-test.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:feat

#8741 feat: JSON:API serialization utils
  ember-data-types/cache/cache.ts
  ember-data-types/q/cache.ts
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/serialize.ts
Labels: target:canary, changelog:feat

#8745 chore: readme overviews for builders
  packages/active-record/README.md
  packages/active-record/ember-data-logo-dark.svg
  packages/active-record/ember-data-logo-light.svg
  packages/json-api/README.md
  packages/rest/README.md
  packages/rest/ember-data-logo-dark.svg
  packages/rest/ember-data-logo-light.svg
Labels: target:canary, changelog:doc

#8746 docs: more documentation for builders
  packages/request-utils/README.md
  packages/request-utils/ember-data-logo-dark.svg
  packages/request-utils/ember-data-logo-light.svg
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/request.ts
Labels: target:canary, changelog:doc

#8749 fix: ensure we are not allowing embroider to do anything
  tests/embroider-basic-compat/ember-cli-build.js
Labels: target:canary, target:lts, changelog:chore, lts-4-12

#8750 Backport into release
  packages/debug/package.json
  packages/graph/src/-private/graph/graph.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/model/src/-private/many-array.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  tests/adapter-encapsulation/tests/integration/coalescing-test.js
  tests/graph/tests/integration/graph/unload-test.ts
  tests/main/tests/integration/record-array-manager-test.js
  tests/main/tests/integration/records/new-record-unload-test.js
  tests/main/tests/integration/records/save-test.js
  tests/main/tests/integration/records/unload-test.js
Labels: changelog:bugfix, backport-release

#8751 Forward fixes from 3.12.x into main
  packages/debug/package.json
  packages/graph/src/-private/graph/graph.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/model/src/-private/many-array.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  tests/adapter-encapsulation/tests/integration/coalescing-test.js
  tests/graph/tests/integration/graph/unload-test.ts
  tests/main/tests/integration/record-array-manager-test.js
  tests/main/tests/integration/records/new-record-unload-test.js
  tests/main/tests/integration/records/save-test.js
  tests/main/tests/integration/records/unload-test.js
Labels: changelog:bugfix

#8747 feat: implement legacy imports deprecation
  packages/-ember-data/addon/-private/index.ts
  packages/-ember-data/addon/adapter.ts
  packages/-ember-data/addon/adapters/errors.ts
  packages/-ember-data/addon/adapters/json-api.ts
  packages/-ember-data/addon/adapters/rest.ts
  packages/-ember-data/addon/attr.ts
  packages/-ember-data/addon/index.js
  packages/-ember-data/addon/model.ts
  packages/-ember-data/addon/relationships.ts
  packages/-ember-data/addon/serializer.ts
  packages/-ember-data/addon/serializers/embedded-records-mixin.ts
  packages/-ember-data/addon/serializers/json-api.ts
  packages/-ember-data/addon/serializers/json.ts
  packages/-ember-data/addon/serializers/rest.ts
  packages/-ember-data/addon/setup-container.ts
  packages/-ember-data/addon/store.ts
  packages/-ember-data/addon/transform.ts
  packages/-ember-data/app/adapters/-json-api.js
  packages/-ember-data/app/initializers/ember-data.js
  packages/-ember-data/app/instance-initializers/ember-data.js
  packages/-ember-data/app/serializers/-default.js
  packages/-ember-data/app/serializers/-json-api.js
  packages/-ember-data/app/serializers/-rest.js
  packages/-ember-data/app/services/store.js
  packages/-ember-data/app/transforms/boolean.js
  packages/-ember-data/app/transforms/date.js
  packages/-ember-data/app/transforms/number.js
  packages/-ember-data/app/transforms/string.js
  packages/-ember-data/index.js
  packages/adapter/src/rest.ts
  packages/graph/src/-private/graph/operations/update-relationship.ts
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  packages/serializer/src/transform.js
  packages/serializer/src/transform.ts
  tests/docs/fixtures/expected.js
  tests/main/app/services/store.js
  tests/main/app/transforms/boolean.js
  tests/main/app/transforms/date.js
  tests/main/app/transforms/number.js
  tests/main/app/transforms/string.js
Labels: target:canary, changelog:deprecation

#8755 chore: simplify file structure in graph package
  packages/graph/src/-private.ts
  packages/graph/src/-private/-edge-definition.ts
  packages/graph/src/-private/-operations.ts
  packages/graph/src/-private/-state.ts
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/debug/assert-polymorphic-type.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/index.ts
  packages/graph/src/-private/operations/add-to-related-records.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/graph/src/-private/operations/remove-from-related-records.ts
  packages/graph/src/-private/operations/replace-related-record.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/graph/src/-private/operations/update-relationship.ts
  packages/graph/src/-private/state/belongs-to.ts
  packages/graph/src/-private/state/has-many.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/store-service.ts
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/graph/tests/integration/graph/operations-test.ts
  tests/graph/tests/integration/graph/unload-test.ts
  tests/main/tests/helpers/accessors.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
Labels: target:canary, changelog:chore

#8756 feat: simpler resource edge
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/edges/resource.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/index.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/graph/src/-private/state/belongs-to.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/references/belongs-to.ts
  tests/graph/tests/integration/graph/edge-removal/helpers.ts
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/graph/tests/integration/graph/unload-test.ts
  tests/main/tests/helpers/accessors.ts
Labels: target:canary, changelog:perf, ci-perf

#8757 feat: simpler collection edge
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/edges/collection.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/add-to-related-records.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/graph/src/-private/operations/remove-from-related-records.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/graph/src/-private/state/has-many.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/references/has-many.ts
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/graph/tests/integration/graph/operations-test.ts
Labels: target:canary, changelog:perf, ci-perf

#8758 chore: refactor implicit edge to match resource and collection pattern
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/edges/collection.ts
  packages/graph/src/-private/edges/implicit.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/json-api/src/-private/cache.ts
  tests/graph/tests/integration/graph/edge-removal/helpers.ts
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/main/tests/helpers/accessors.ts
Labels: target:canary, changelog:chore

#8760 chore: refactor metas into separate cache
  packages/graph/src/-private/graph.ts
Labels: target:canary, changelog:perf, ci-perf

#8761 perf: reduce allocations during graph population
  packages/graph/src/-private/operations/update-relationship.ts
  packages/store/src/-private/caches/identifier-cache.ts
  tests/main/tests/integration/records/delete-record-test.js
  tests/main/tests/integration/relationships/has-many-test.js
Labels: target:canary, changelog:perf, ci-perf
