Repository warp-drive-data/warp-drive, pull requests merged in 2023-10, with the labels that each got.

#8946 feat (private): implement resource relationships for SchemaRecord
  ember-data-types/q/ember-data-json-api.ts
  packages/schema-record/src/record.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/schema-record/tests/reads/resource-test.ts
Labels: :dart: canary, :label: feat

#8948 feat(private): reactive simple fields
  packages/schema-record/src/record.ts
  packages/tracking/package.json
  packages/tracking/rollup.config.mjs
  packages/tracking/src/-private.ts
  packages/tracking/src/index.ts
  pnpm-lock.yaml
  tests/schema-record/tests/-utils/reactive-context.ts
  tests/schema-record/tests/reactivity/basic-fields-test.ts
  tests/schema-record/tests/reactivity/derivation-test.ts
  tests/schema-record/tests/reactivity/resource-test.ts
  tests/schema-record/tests/test-helper.js
Labels: :dart: canary, :label: feat

#8949 feat:prepare for universal reactivity
  .eslintrc.js
  packages/adapter/rollup.config.mjs
  packages/adapter/src/index.ts
  packages/adapter/src/rest.ts
  packages/graph/rollup.config.mjs
  packages/json-api/rollup.config.mjs
  packages/model/package.json
  packages/model/rollup.config.mjs
  packages/model/src/-private/has-many.js
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model-for-mixin.ts
  packages/model/src/-private/model.d.ts
  packages/model/src/-private/model.js
  packages/model/src/-private/promise-belongs-to.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/record-state.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/schema-record/src/record.ts
  packages/store/package.json
  packages/store/rollup.config.mjs
  packages/store/src/-private/document.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/legacy-model-support/record-reference.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  packages/tracking/package.json
  packages/tracking/rollup.config.mjs
  packages/tracking/src/-private.ts
  packages/tracking/src/index.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/fastboot/types/fastboot-test-app/index.d.ts
  tests/main/tests/acceptance/relationships/tracking-record-state-test.js
  tests/main/tests/acceptance/tracking-create-record-test.js
  tests/main/tests/end-user-dx/meaningful-backtracking-errors-test.js
  tests/main/tests/helpers/create-tracking-context.js
  tests/main/tests/unit/model/relationships/belongs-to-test.js
  tests/main/tests/unit/model/relationships/has-many-test.js
  tests/recommended-json-api/app/components/book-list.ts
  tests/recommended-json-api/app/components/book-search.ts
  tests/recommended-json-api/app/components/infinite-books.ts
  tests/recommended-json-api/app/utils/pagination-links.ts
  tsconfig.json
Labels: :dart: canary, :label: feat, ci-assetsize, ci-perf, 🔌 Project Unplug 🔌

#8952 test: derivation reactivity
  tests/schema-record/tests/reactivity/derivation-test.ts
Labels: :dart: canary, :label: test

#8954 docs: typo in hasChangedRelationships description
  packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: doc

#8960 internal: fix test settledness
  tests/main/tests/integration/records/delete-record-test.js
Labels: :dart: canary, :label: chore

#8961 chore: run tests nicely
  .github/actions/setup/action.yml
  .github/workflows/main.yml
  .gitignore
  package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/src/testem/custom-dot-reporter.js
  packages/unpublished-test-infra/src/testem/testem.js
  patches/qunit@2.19.4.patch
  patches/testem@3.10.1.patch
  pnpm-lock.yaml
  tests/main/bin/calculate-test-jobs
  tests/main/package.json
  tests/main/testem.js
  tests/main/tests/index.html
  tests/main/tests/test-helper.js
Labels: :dart: canary, :label: chore

#8963 chore: scaffold additional contributing materials
  contributing/assets/ember-data-architecture.png
  contributing/become-a-contributor.md
  contributing/project-architecture.md
  contributing/setting-up-the-project.md
  contributing/terminology.md
Labels: :dart: canary, :label: doc

#8966 feat: Add links to the CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: :dart: canary, :label: doc

#8972 chore: use new test runner for request tests
  .eslintrc.js
  packages/diagnostic/src/internals/diagnostic.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/holodeck/server/CERT.md
  packages/holodeck/server/index.js
  packages/holodeck/server/localhost-cert.pem
  packages/holodeck/server/localhost-key.pem
  packages/holodeck/server/localhost-privkey.pem
  packages/holodeck/server/localhost.pem
  packages/unpublished-test-infra/src/testem/custom-dot-reporter.js
  packages/unpublished-test-infra/src/testem/testem.js
  pnpm-lock.yaml
  tests/request/.mock-cache/409aab98/GET-0-users/1/res.body.br
  tests/request/.mock-cache/409aab98/GET-0-users/1/res.meta.json
  tests/request/.mock-cache/b111b348/GET-0-users/1/res.body.br
  tests/request/.mock-cache/b111b348/GET-0-users/1/res.meta.json
  tests/request/.mock-cache/c6767456/GET-0-users/1/res.body.br
  tests/request/.mock-cache/c6767456/GET-0-users/1/res.meta.json
  tests/request/ember-cli-build.js
  tests/request/package.json
  tests/request/testem.js
  tests/request/tests/index.html
  tests/request/tests/integration/abort-test.ts
  tests/request/tests/integration/custom-abort-test.ts
  tests/request/tests/integration/error-propagation-test.ts
  tests/request/tests/integration/fetch-handler-test.ts
  tests/request/tests/integration/graceful-dev-errors-test.ts
  tests/request/tests/integration/graceful-dev-handler-errors-test.ts
  tests/request/tests/integration/immutability-test.ts
  tests/request/tests/integration/request-manager-test.ts
  tests/request/tests/integration/response-currying-test.ts
  tests/request/tests/integration/response-test.ts
  tests/request/tests/integration/service-test.ts
  tests/request/tests/integration/setup-test.ts
  tests/request/tests/integration/stateful-handler-test.ts
  tests/request/tests/integration/streams-test.ts
  tests/request/tests/test-helper.js
Labels: :dart: canary, :label: chore

#8974 chore: remove uneeded json-api-encapsulation test app
  pnpm-lock.yaml
  tests/json-api-encapsulation/.ember-cli
  tests/json-api-encapsulation/.gitignore
  tests/json-api-encapsulation/.template-lintrc.js
  tests/json-api-encapsulation/.watchmanconfig
  tests/json-api-encapsulation/README.md
  tests/json-api-encapsulation/app/app.js
  tests/json-api-encapsulation/app/components/.gitkeep
  tests/json-api-encapsulation/app/controllers/.gitkeep
  tests/json-api-encapsulation/app/helpers/.gitkeep
  tests/json-api-encapsulation/app/index.html
  tests/json-api-encapsulation/app/models/.gitkeep
  tests/json-api-encapsulation/app/resolver.js
  tests/json-api-encapsulation/app/router.js
  tests/json-api-encapsulation/app/routes/.gitkeep
  tests/json-api-encapsulation/app/styles/app.css
  tests/json-api-encapsulation/app/templates/application.hbs
  tests/json-api-encapsulation/app/templates/components/.gitkeep
  tests/json-api-encapsulation/config/environment.js
  tests/json-api-encapsulation/config/optional-features.json
  tests/json-api-encapsulation/config/targets.js
  tests/json-api-encapsulation/ember-cli-build.js
  tests/json-api-encapsulation/package.json
  tests/json-api-encapsulation/public/robots.txt
  tests/json-api-encapsulation/testem.js
  tests/json-api-encapsulation/tests/helpers/.gitkeep
  tests/json-api-encapsulation/tests/index.html
  tests/json-api-encapsulation/tests/integration/.gitkeep
  tests/json-api-encapsulation/tests/integration/smoke-test.js
  tests/json-api-encapsulation/tests/test-helper.js
  tests/json-api-encapsulation/tests/unit/.gitkeep
  tests/json-api-encapsulation/vendor/.gitkeep
Labels: :dart: canary, :label: chore

#8978 chore: rename model-encapsulation tests, remove smoke-test
  package.json
  pnpm-lock.yaml
  tests/ember-data__model/.gitignore
  tests/ember-data__model/.template-lintrc.js
  tests/ember-data__model/.watchmanconfig
  tests/ember-data__model/README.md
  tests/ember-data__model/app/app.js
  tests/ember-data__model/app/components/.gitkeep
  tests/ember-data__model/app/controllers/.gitkeep
  tests/ember-data__model/app/helpers/.gitkeep
  tests/ember-data__model/app/index.html
  tests/ember-data__model/app/models/.gitkeep
  tests/ember-data__model/app/resolver.js
  tests/ember-data__model/app/router.js
  tests/ember-data__model/app/routes/.gitkeep
  tests/ember-data__model/app/styles/app.css
  tests/ember-data__model/app/templates/application.hbs
  tests/ember-data__model/app/templates/components/.gitkeep
  tests/ember-data__model/config/environment.js
  tests/ember-data__model/config/optional-features.json
  tests/ember-data__model/config/targets.js
  tests/ember-data__model/ember-cli-build.js
  tests/ember-data__model/package.json
  tests/ember-data__model/public/robots.txt
  tests/ember-data__model/testem.js
  tests/ember-data__model/tests/helpers/.gitkeep
  tests/ember-data__model/tests/index.html
  tests/ember-data__model/tests/integration/.gitkeep
  tests/ember-data__model/tests/integration/model-for-test.js
  tests/ember-data__model/tests/test-helper.js
  tests/ember-data__model/tests/unit/.gitkeep
  tests/ember-data__model/vendor/.gitkeep
  tests/model-encapsulation/README.md
  tests/model-encapsulation/tests/integration/smoke-test.js
Labels: :dart: canary, :label: chore

#8979 chore: rename serializer-encapsulation tests, remove smoke-test
  pnpm-lock.yaml
  tests/ember-data__serializer/.ember-cli
  tests/ember-data__serializer/.gitignore
  tests/ember-data__serializer/.template-lintrc.js
  tests/ember-data__serializer/.watchmanconfig
  tests/ember-data__serializer/README.md
  tests/ember-data__serializer/app/app.js
  tests/ember-data__serializer/app/components/.gitkeep
  tests/ember-data__serializer/app/controllers/.gitkeep
  tests/ember-data__serializer/app/helpers/.gitkeep
  tests/ember-data__serializer/app/index.html
  tests/ember-data__serializer/app/models/.gitkeep
  tests/ember-data__serializer/app/resolver.js
  tests/ember-data__serializer/app/router.js
  tests/ember-data__serializer/app/routes/.gitkeep
  tests/ember-data__serializer/app/services/store.js
  tests/ember-data__serializer/app/styles/app.css
  tests/ember-data__serializer/app/templates/application.hbs
  tests/ember-data__serializer/app/templates/components/.gitkeep
  tests/ember-data__serializer/config/environment.js
  tests/ember-data__serializer/config/optional-features.json
  tests/ember-data__serializer/config/targets.js
  tests/ember-data__serializer/ember-cli-build.js
  tests/ember-data__serializer/package.json
  tests/ember-data__serializer/public/robots.txt
  tests/ember-data__serializer/testem.js
  tests/ember-data__serializer/tests/helpers/.gitkeep
  tests/ember-data__serializer/tests/index.html
  tests/ember-data__serializer/tests/integration/.gitkeep
  tests/ember-data__serializer/tests/integration/create-record-test.js
  tests/ember-data__serializer/tests/integration/delete-record-test.js
  tests/ember-data__serializer/tests/integration/errors-test.js
  tests/ember-data__serializer/tests/integration/normalize-test.js
  tests/ember-data__serializer/tests/integration/push-payload-test.js
  tests/ember-data__serializer/tests/integration/relationships-test.js
  tests/ember-data__serializer/tests/integration/requests-test.js
  tests/ember-data__serializer/tests/integration/serialize-test.js
  tests/ember-data__serializer/tests/integration/update-record-test.js
  tests/ember-data__serializer/tests/test-helper.js
  tests/ember-data__serializer/tests/unit/.gitkeep
  tests/ember-data__serializer/vendor/.gitkeep
  tests/serializer-encapsulation/README.md
  tests/serializer-encapsulation/tests/integration/smoke-test.js
Labels: :dart: canary, :label: chore

#8980 chore: rename graph-test-app to ember-data__graph
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  tests/ember-data__graph/README.md
  tests/ember-data__graph/app/app.ts
  tests/ember-data__graph/app/config/environment.d.ts
  tests/ember-data__graph/app/index.html
  tests/ember-data__graph/app/resolver.ts
  tests/ember-data__graph/app/router.ts
  tests/ember-data__graph/app/services/store.ts
  tests/ember-data__graph/app/styles/app.css
  tests/ember-data__graph/app/templates/.gitkeep
  tests/ember-data__graph/app/templates/application.hbs
  tests/ember-data__graph/config/environment.js
  tests/ember-data__graph/config/optional-features.json
  tests/ember-data__graph/config/targets.js
  tests/ember-data__graph/ember-cli-build.js
  tests/ember-data__graph/package.json
  tests/ember-data__graph/testem.js
  tests/ember-data__graph/tests/.gitkeep
  tests/ember-data__graph/tests/index.html
  tests/ember-data__graph/tests/integration/graph.ts
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/duplicate-data-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/setup.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/graph-test.ts
  tests/ember-data__graph/tests/integration/graph/order-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/polymorphism/implicit-keys-test.ts
  tests/ember-data__graph/tests/integration/graph/unload-test.ts
  tests/ember-data__graph/tests/setup-test.ts
  tests/ember-data__graph/tests/test-helper.js
  tests/graph/README.md
  tests/json-api/package.json
  tsconfig.root.json
Labels: :dart: canary, :label: chore

#8981 chore: rename adapter-encapsulation-test-app to ember-data__adapter
  pnpm-lock.yaml
  tests/adapter-encapsulation/README.md
  tests/adapter-encapsulation/tests/integration/smoke-test.js
  tests/ember-data__adapter/.ember-cli
  tests/ember-data__adapter/.gitignore
  tests/ember-data__adapter/.template-lintrc.js
  tests/ember-data__adapter/.watchmanconfig
  tests/ember-data__adapter/README.md
  tests/ember-data__adapter/app/app.js
  tests/ember-data__adapter/app/components/.gitkeep
  tests/ember-data__adapter/app/controllers/.gitkeep
  tests/ember-data__adapter/app/helpers/.gitkeep
  tests/ember-data__adapter/app/index.html
  tests/ember-data__adapter/app/models/.gitkeep
  tests/ember-data__adapter/app/resolver.js
  tests/ember-data__adapter/app/router.js
  tests/ember-data__adapter/app/routes/.gitkeep
  tests/ember-data__adapter/app/services/store.js
  tests/ember-data__adapter/app/styles/app.css
  tests/ember-data__adapter/app/templates/application.hbs
  tests/ember-data__adapter/app/templates/components/.gitkeep
  tests/ember-data__adapter/config/environment.js
  tests/ember-data__adapter/config/optional-features.json
  tests/ember-data__adapter/config/targets.js
  tests/ember-data__adapter/ember-cli-build.js
  tests/ember-data__adapter/package.json
  tests/ember-data__adapter/public/robots.txt
  tests/ember-data__adapter/testem.js
  tests/ember-data__adapter/tests/helpers/.gitkeep
  tests/ember-data__adapter/tests/index.html
  tests/ember-data__adapter/tests/integration/.gitkeep
  tests/ember-data__adapter/tests/integration/belongs-to-test.js
  tests/ember-data__adapter/tests/integration/coalescing-test.js
  tests/ember-data__adapter/tests/integration/generate-id-test.js
  tests/ember-data__adapter/tests/integration/has-many-test.js
  tests/ember-data__adapter/tests/integration/mutations-test.js
  tests/ember-data__adapter/tests/integration/queries-test.js
  tests/ember-data__adapter/tests/integration/reload-test.js
  tests/ember-data__adapter/tests/test-helper.js
  tests/ember-data__adapter/tests/unit/.gitkeep
  tests/ember-data__adapter/vendor/.gitkeep
Labels: :dart: canary, :label: chore

#8982 chore: rename json-api-test-app to ember-data__json-api
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  tests/ember-data__json-api/README.md
  tests/ember-data__json-api/app/app.ts
  tests/ember-data__json-api/app/config/environment.d.ts
  tests/ember-data__json-api/app/index.html
  tests/ember-data__json-api/app/resolver.ts
  tests/ember-data__json-api/app/router.ts
  tests/ember-data__json-api/app/styles/app.css
  tests/ember-data__json-api/app/templates/.gitkeep
  tests/ember-data__json-api/app/templates/application.hbs
  tests/ember-data__json-api/config/environment.js
  tests/ember-data__json-api/config/optional-features.json
  tests/ember-data__json-api/config/targets.js
  tests/ember-data__json-api/ember-cli-build.js
  tests/ember-data__json-api/package.json
  tests/ember-data__json-api/testem.js
  tests/ember-data__json-api/tests/.gitkeep
  tests/ember-data__json-api/tests/index.html
  tests/ember-data__json-api/tests/integration/-smoke.ts
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/serialize-test.ts
  tests/ember-data__json-api/tests/test-helper.js
  tests/json-api/README.md
  tests/main/tests/unit/adapters/json-api-adapter/json-api-test.js
Labels: :dart: canary, :label: chore

#8983 chore: rename request-test-app to ember-data__request
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  tests/builders/package.json
  tests/ember-data__request/.mock-cache/409aab98/GET-0-users/1/res.body.br
  tests/ember-data__request/.mock-cache/409aab98/GET-0-users/1/res.meta.json
  tests/ember-data__request/.mock-cache/b111b348/GET-0-users/1/res.body.br
  tests/ember-data__request/.mock-cache/b111b348/GET-0-users/1/res.meta.json
  tests/ember-data__request/.mock-cache/c6767456/GET-0-users/1/res.body.br
  tests/ember-data__request/.mock-cache/c6767456/GET-0-users/1/res.meta.json
  tests/ember-data__request/README.md
  tests/ember-data__request/app/app.ts
  tests/ember-data__request/app/config/environment.d.ts
  tests/ember-data__request/app/index.html
  tests/ember-data__request/app/resolver.ts
  tests/ember-data__request/app/router.ts
  tests/ember-data__request/app/styles/app.css
  tests/ember-data__request/app/templates/.gitkeep
  tests/ember-data__request/app/templates/application.hbs
  tests/ember-data__request/config/environment.js
  tests/ember-data__request/config/optional-features.json
  tests/ember-data__request/config/targets.js
  tests/ember-data__request/ember-cli-build.js
  tests/ember-data__request/holodeck.mjs
  tests/ember-data__request/package.json
  tests/ember-data__request/public/assets/demo-fetch.json
  tests/ember-data__request/testem.js
  tests/ember-data__request/tests/.gitkeep
  tests/ember-data__request/tests/index.html
  tests/ember-data__request/tests/integration/abort-test.ts
  tests/ember-data__request/tests/integration/custom-abort-test.ts
  tests/ember-data__request/tests/integration/error-propagation-test.ts
  tests/ember-data__request/tests/integration/fetch-handler-test.ts
  tests/ember-data__request/tests/integration/graceful-dev-errors-test.ts
  tests/ember-data__request/tests/integration/graceful-dev-handler-errors-test.ts
  tests/ember-data__request/tests/integration/immutability-test.ts
  tests/ember-data__request/tests/integration/request-manager-test.ts
  tests/ember-data__request/tests/integration/response-currying-test.ts
  tests/ember-data__request/tests/integration/response-test.ts
  tests/ember-data__request/tests/integration/service-test.ts
  tests/ember-data__request/tests/integration/setup-test.ts
  tests/ember-data__request/tests/integration/stateful-handler-test.ts
  tests/ember-data__request/tests/integration/streams-test.ts
  tests/ember-data__request/tests/test-helper.js
  tests/request/README.md
  tsconfig.root.json
Labels: :dart: canary, :label: chore

#8984 chore: remove unneeded debug-encapsulation tests
  .github/workflows/deprecations-check.yml
  .github/workflows/encapsulation-tests.yml
  package.json
  tests/debug-encapsulation/.ember-cli
  tests/debug-encapsulation/.gitignore
  tests/debug-encapsulation/.template-lintrc.js
  tests/debug-encapsulation/.watchmanconfig
  tests/debug-encapsulation/README.md
  tests/debug-encapsulation/app/app.js
  tests/debug-encapsulation/app/components/.gitkeep
  tests/debug-encapsulation/app/controllers/.gitkeep
  tests/debug-encapsulation/app/helpers/.gitkeep
  tests/debug-encapsulation/app/index.html
  tests/debug-encapsulation/app/models/.gitkeep
  tests/debug-encapsulation/app/resolver.js
  tests/debug-encapsulation/app/router.js
  tests/debug-encapsulation/app/routes/.gitkeep
  tests/debug-encapsulation/app/styles/app.css
  tests/debug-encapsulation/app/templates/application.hbs
  tests/debug-encapsulation/app/templates/components/.gitkeep
  tests/debug-encapsulation/config/environment.js
  tests/debug-encapsulation/config/optional-features.json
  tests/debug-encapsulation/config/targets.js
  tests/debug-encapsulation/ember-cli-build.js
  tests/debug-encapsulation/package.json
  tests/debug-encapsulation/public/robots.txt
  tests/debug-encapsulation/testem.js
  tests/debug-encapsulation/tests/helpers/.gitkeep
  tests/debug-encapsulation/tests/index.html
  tests/debug-encapsulation/tests/integration/.gitkeep
  tests/debug-encapsulation/tests/integration/smoke-test.js
  tests/debug-encapsulation/tests/test-helper.js
  tests/debug-encapsulation/tests/unit/.gitkeep
  tests/debug-encapsulation/vendor/.gitkeep
Labels: :label: cleanup, :label: chore

#8986 chore: rename schema tests to warp-drive__* variants
  .eslintignore
  package.json
  pnpm-lock.yaml
  tests/warp-drive__schema-record/README.md
  tests/warp-drive__schema-record/app/app.ts
  tests/warp-drive__schema-record/app/config/environment.d.ts
  tests/warp-drive__schema-record/app/index.html
  tests/warp-drive__schema-record/app/resolver.ts
  tests/warp-drive__schema-record/app/router.ts
  tests/warp-drive__schema-record/app/services/store.ts
  tests/warp-drive__schema-record/app/styles/app.css
  tests/warp-drive__schema-record/app/templates/.gitkeep
  tests/warp-drive__schema-record/app/templates/application.hbs
  tests/warp-drive__schema-record/config/environment.js
  tests/warp-drive__schema-record/config/optional-features.json
  tests/warp-drive__schema-record/config/targets.js
  tests/warp-drive__schema-record/ember-cli-build.js
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/testem.js
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/.gitkeep
  tests/warp-drive__schema-record/tests/index.html
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reactivity/resource-test.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  tests/warp-drive__schema-record/tests/test-helper.js
  tests/warp-drive__schema/input/schema.json
  tests/warp-drive__schema/input/schemas/user.ts
Labels: :dart: canary, :label: chore

#8987 chore: test-harness improvements
  packages/diagnostic/src/styles/dom-reporter.css
Labels: :dart: canary, :label: chore

#8989 chore(private): concurrent mode
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/-types/report.ts
  packages/diagnostic/src/index.ts
  packages/diagnostic/src/internals/config.ts
  packages/diagnostic/src/internals/delegating-reporter.ts
  packages/diagnostic/src/internals/diagnostic.ts
  packages/diagnostic/src/internals/run.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/diagnostic/src/styles/dom-reporter.css
  packages/holodeck/README.md
  packages/holodeck/client/index.ts
  packages/holodeck/client/mock.ts
  tests/ember-data__request/tests/integration/fetch-handler-test.ts
  tests/ember-data__request/tests/integration/service-test.ts
  tests/ember-data__request/tests/integration/stateful-handler-test.ts
  tests/ember-data__request/tests/test-helper.js
Labels: :dart: canary, :label: chore

#8992 chore: rollup v4
  packages/active-record/package.json
  packages/adapter/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  pnpm-lock.yaml
Labels: :label: dependencies

#8993 chore: fix development test command
  package.json
Labels: :dart: canary, :label: chore

#8994 chore: fix recursive pnpm on node 18.18
  packages/holodeck/bin/cmd/run.js
  packages/holodeck/bin/cmd/spawn.js
  tests/main/package.json
Labels: :dart: canary, :label: chore

#8995 chore: add @warp-drive/diagnostic docs
  packages/diagnostic/README.md
Labels: :dart: canary, :label: chore

#9000 feat(private): native test runner
  .eslintignore
  .github/actions/setup/action.yml
  .gitignore
  package.json
  packages/diagnostic/README.md
  packages/diagnostic/bin/.gitkeep
  packages/diagnostic/package.json
  packages/diagnostic/server/browsers/index.js
  packages/diagnostic/server/bun/fetch.js
  packages/diagnostic/server/bun/launch-browser.js
  packages/diagnostic/server/bun/port.js
  packages/diagnostic/server/bun/socket-handler.js
  packages/diagnostic/server/default-setup.js
  packages/diagnostic/server/index.js
  packages/diagnostic/server/launcher.html
  packages/diagnostic/server/reporters/default.js
  packages/diagnostic/server/utils/const.js
  packages/diagnostic/server/utils/debug.js
  packages/diagnostic/server/utils/platform.js
  packages/diagnostic/server/utils/port.js
  packages/diagnostic/server/utils/time.js
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/-utils.ts
  packages/diagnostic/src/emitters/diagnostic.ts
  packages/diagnostic/src/emitters/testem.ts
  packages/diagnostic/src/internals/config.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/diagnostic/src/runners/dom.ts
  packages/diagnostic/test/diagnostic.js
  packages/diagnostic/test/example-tests.js
  packages/diagnostic/test/index.html
  pnpm-lock.yaml
  tests/ember-data__graph/diagnostic.js
  tests/ember-data__graph/ember-cli-build.js
  tests/ember-data__graph/package.json
  tests/ember-data__graph/testem.js
  tests/ember-data__graph/tests/index.html
  tests/ember-data__graph/tests/test-helper.js
  tests/ember-data__json-api/diagnostic.js
  tests/ember-data__json-api/ember-cli-build.js
  tests/ember-data__json-api/package.json
  tests/ember-data__json-api/testem.js
  tests/ember-data__json-api/tests/index.html
  tests/ember-data__json-api/tests/test-helper.js
  tests/main/package.json
Labels: :dart: canary, :label: chore

#9003 decycle property lookups on promise proxies to fix usage in ember-concurrency
  packages/store/addon/-private/system/promise-proxies.js
Labels: :label: bug

#9006 chore (internal): convert builder and request tests to use diagnostic+runner
  .eslintrc.js
  packages/active-record/README.md
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/active-record/src/request.ts
  packages/diagnostic/README.md
  packages/diagnostic/server/bun/socket-handler.js
  packages/diagnostic/server/default-setup.js
  packages/diagnostic/server/index.js
  packages/diagnostic/server/reporters/default.js
  packages/model/src/-private/model.d.ts
  packages/rest/README.md
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/rest/src/request.ts
  pnpm-lock.yaml
  tests/builders/README.md
  tests/builders/diagnostic.js
  tests/builders/ember-cli-build.js
  tests/builders/package.json
  tests/builders/testem.js
  tests/builders/tests/index.html
  tests/builders/tests/integration/create-record-test.ts
  tests/builders/tests/integration/delete-record-test.ts
  tests/builders/tests/integration/update-record-test.ts
  tests/builders/tests/test-helper.js
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/builders/tests/unit/build-base-url-test.ts
  tests/builders/tests/unit/build-query-params-test.ts
  tests/builders/tests/unit/filter-empty-test.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/builders/tests/unit/parse-cache-control-test.ts
  tests/builders/tests/unit/rest-builder-test.ts
  tests/ember-data__request/diagnostic.js
  tests/ember-data__request/ember-cli-build.js
  tests/ember-data__request/holodeck.mjs
  tests/ember-data__request/package.json
  tests/ember-data__request/tests/index.html
  tests/ember-data__request/tests/integration/response-currying-test.ts
  tests/ember-data__request/tests/integration/response-test.ts
  tests/ember-data__request/tests/test-helper.js
  tests/main/holodeck.mjs
Labels: :dart: canary, :label: chore

#9008 chore: update eslint plugin name
  packages/eslint-plugin-ember-data/package.json
Labels: :dart: canary, :label: chore

#9012 fix: make willCommit slightly safer when race conditions occur
  ember-data-types/q/ds-model.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/legacy-compat/src/legacy-network-handler/serializer-response.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/model.d.ts
  packages/model/src/-private/record-state.ts
  packages/store/src/-private/legacy-model-support/schema-definition-service.ts
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/records/concurrent-save-test.ts
  tests/main/tests/integration/records/delete-record-test.js
Labels: :label: bug, backport-lts

#9014 fix: make willCommit slightly safer when race conditions occur
  packages/json-api/src/-private/cache.ts
  tests/main/tests/integration/records/concurrent-save-test.ts
Labels: :dart: canary, :dart: lts, :label: bug

#9009 chore(internal) add @warp-drive/diagnostic/ember
  packages/diagnostic/README.md
  packages/diagnostic/addon-main.cjs
  packages/diagnostic/package.json
  packages/diagnostic/rollup.config.mjs
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/-utils.ts
  packages/diagnostic/src/ember.ts
  packages/diagnostic/src/index.ts
  packages/diagnostic/src/internals/config.ts
  packages/diagnostic/src/internals/diagnostic.ts
  packages/diagnostic/src/internals/run.ts
  packages/unpublished-test-infra/addon-test-support/asserts/index.ts
  pnpm-lock.yaml
  tests/builders/package.json
  tests/builders/tests/integration/create-record-test.ts
  tests/builders/tests/integration/delete-record-test.ts
  tests/builders/tests/integration/update-record-test.ts
  tests/builders/tests/test-helper.js
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/builders/tests/unit/rest-builder-test.ts
  tests/ember-data__adapter/package.json
  tests/ember-data__adapter/tests/integration/belongs-to-test.js
  tests/ember-data__adapter/tests/integration/coalescing-test.js
  tests/ember-data__adapter/tests/integration/generate-id-test.js
  tests/ember-data__adapter/tests/integration/has-many-test.js
  tests/ember-data__adapter/tests/integration/mutations-test.js
  tests/ember-data__adapter/tests/integration/queries-test.js
  tests/ember-data__adapter/tests/integration/reload-test.js
  tests/ember-data__adapter/tests/test-helper.js
  tests/ember-data__graph/package.json
  tests/ember-data__graph/tests/.gitkeep
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/duplicate-data-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/setup.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/graph-test.ts
  tests/ember-data__graph/tests/integration/graph/order-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/polymorphism/implicit-keys-test.ts
  tests/ember-data__graph/tests/integration/graph/unload-test.ts
  tests/ember-data__graph/tests/test-helper.js
  tests/ember-data__json-api/package.json
  tests/ember-data__json-api/tests/test-helper.js
  tests/ember-data__model/package.json
  tests/ember-data__model/tests/test-helper.js
  tests/ember-data__request/package.json
  tests/ember-data__request/tests/integration/service-test.ts
  tests/ember-data__request/tests/integration/stateful-handler-test.ts
  tests/ember-data__request/tests/test-helper.js
Labels: :dart: canary, :label: chore

#9016 chore: make type-only files strict
  .eslintrc.js
  @types/require/index.d.ts
  ember-data-types/q/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/store/src/-private/network/request-cache.ts
  tests/warp-drive__schema/package.json
  tsconfig.json
Labels: :dart: canary, :label: chore

#9018 doc(README): remove typo
  README.md
Labels: :dart: canary, :label: doc

#9019 chore: make model types strict
  .eslintrc.js
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/model-for-mixin.ts
  packages/model/src/-private/notify-changes.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/record-state.ts
  packages/store/src/-private/network/request-cache.ts
  tsconfig.json
Labels: :dart: canary, :label: chore

#9021 chore: cleanup ember-data/-private types
  .eslintrc.js
  .github/workflows/main.yml
  ember-data-types/q/ds-model.ts
  packages/-ember-data/addon/-private/core.ts
  packages/-ember-data/addon/-private/index.ts
  packages/-ember-data/addon/index.ts
  packages/-ember-data/addon/version.d.ts
  packages/adapter/src/-private/build-url-mixin.ts
  packages/adapter/src/-private/utils/continue-on-reject.ts
  packages/adapter/src/-private/utils/determine-body-promise.ts
  packages/model/src/-private/model.d.ts
  packages/serializer/src/-private/transforms/boolean.ts
  packages/serializer/src/-private/transforms/date.ts
  packages/serializer/src/-private/transforms/number.ts
  packages/serializer/src/-private/transforms/string.ts
  packages/serializer/src/-private/transforms/transform.ts
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  tsconfig.json
Labels: :dart: canary, :label: chore

#9024 chore: cleanup more types
  packages/adapter/src/-private/utils/continue-on-reject.ts
  packages/adapter/src/-private/utils/fetch.ts
  packages/adapter/src/-private/utils/serialize-query-params.ts
  packages/adapter/src/index.ts
  packages/adapter/src/json-api.ts
Labels: :dart: canary, :label: chore

#9027 chore: improve types for store package
  packages/store/src/-private/store-service.ts
  packages/store/src/-types/q/store.ts
Labels: :dart: canary, :label: chore

#9046 chore: reduce number of things turbo builds for build
  .gitignore
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/core-types/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  turbo.json
Labels: :dart: canary, :label: chore

#9049 chore: incremental tsc builds
  packages/-ember-data/package.json
  packages/-ember-data/tsconfig.json
  packages/active-record/package.json
  packages/active-record/tsconfig.json
  packages/adapter/package.json
  packages/adapter/tsconfig.json
  packages/core-types/package.json
  packages/core-types/tsconfig.json
  packages/diagnostic/package.json
  packages/diagnostic/tsconfig.json
  packages/graph/package.json
  packages/graph/tsconfig.json
  packages/holodeck/package.json
  packages/holodeck/tsconfig.json
  packages/json-api/package.json
  packages/json-api/tsconfig.json
  packages/legacy-compat/package.json
  packages/legacy-compat/tsconfig.json
  packages/model/package.json
  packages/model/tsconfig.json
  packages/request-utils/package.json
  packages/request-utils/tsconfig.json
  packages/request/package.json
  packages/request/tsconfig.json
  packages/rest/package.json
  packages/rest/tsconfig.json
  packages/serializer/package.json
  packages/serializer/tsconfig.json
  packages/store/package.json
  packages/store/tsconfig.json
  packages/tracking/package.json
  packages/tracking/tsconfig.json
Labels: :dart: canary, :label: chore

#9050 chore: use composite mode for tsc
  packages/-ember-data/tsconfig.json
  packages/active-record/tsconfig.json
  packages/adapter/tsconfig.json
  packages/core-types/tsconfig.json
  packages/diagnostic/tsconfig.json
  packages/graph/tsconfig.json
  packages/holodeck/tsconfig.json
  packages/json-api/tsconfig.json
  packages/legacy-compat/tsconfig.json
  packages/model/tsconfig.json
  packages/request-utils/tsconfig.json
  packages/request/tsconfig.json
  packages/rest/tsconfig.json
  packages/serializer/tsconfig.json
  packages/store/tsconfig.json
  packages/tracking/tsconfig.json
Labels: :dart: canary, :label: chore

#9055 Fix ESLint for VSCode
  .vscode/settings.json
  config/eslint/base.cjs
  config/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  pnpm-lock.yaml
  scripts/validate-deps.js
Labels: :dart: canary, :label: chore

#9058 Switch from eslint-plugin-prettier to running prettier directly
  .github/renovate.json
  .github/workflows/compat-tests.yml
  .github/workflows/main.yml
  .prettierignore
  .prettierrc.js
  .vscode/settings.json
  @types/ember-data-qunit-asserts/index.d.ts
  config/eslint/base.cjs
  config/eslint/ignore.cjs
  config/eslint/isolation.cjs
  config/eslint/typescript.cjs
  config/package.json
  config/rollup/external.js
  docs-generator/yuidoc.json
  package.json
  packages/-ember-data/tsconfig.json
  packages/active-record/babel.config.json
  packages/active-record/tsconfig.json
  packages/adapter/tsconfig.json
  packages/core-types/tsconfig.json
  packages/debug/addon/index.js
  packages/diagnostic/babel.config.json
  packages/diagnostic/src/styles/dom-reporter.css
  packages/diagnostic/tsconfig.json
  packages/graph/src/-private/debug/assert-polymorphic-type.ts
  packages/graph/tsconfig.json
  packages/holodeck/babel.config.json
  packages/holodeck/bin/cmd/pm2.js
  packages/holodeck/bin/cmd/spawn.js
  packages/holodeck/bin/holodeck.js
  packages/holodeck/server/index.js
  packages/holodeck/tsconfig.json
  packages/json-api/tsconfig.json
  packages/legacy-compat/tsconfig.json
  packages/model/src/-private/debug/assert-polymorphic-type.ts
  packages/model/src/-private/model.d.ts
  packages/request-utils/babel.config.json
  packages/request-utils/tsconfig.json
  packages/request/src/-private/debug.ts
  packages/request/tsconfig.json
  packages/rest/babel.config.json
  packages/rest/tsconfig.json
  packages/schema-record/tsconfig.json
  packages/serializer/tsconfig.json
  packages/store/tsconfig.json
  packages/tracking/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/copy-declarations.mjs
  scripts/explain.mjs
  tests/fastboot/public/api/people.json
  tests/main/public/assets/users/list.json
  turbo.json
Labels: :dart: canary, :label: chore

#9059 docs: The comprehensive guide to relationships
  guides/relationships.md
  guides/relationships/configuration/0-one-to-none.md
  guides/relationships/configuration/1-one-to-one.md
  guides/relationships/configuration/2-one-to-many.md
  guides/relationships/configuration/3-many-to-none.md
  guides/relationships/configuration/4-many-to-one.md
  guides/relationships/configuration/5-many-to-many.md
  guides/relationships/features/inverses.md
  guides/relationships/terminology.md
Labels: :dart: canary, :label: doc

#9061 Git-ignore .prettier-cache
  .gitignore
Labels: :dart: canary, :label: chore

#9062 Extract qunit ESLint config
  config/eslint/qunit.cjs
  config/package.json
  packages/-ember-data/.eslintrc.cjs
  pnpm-lock.yaml
Labels: :dart: canary, :label: chore

#9054 Initial lint config for tests/blueprints
  .prettierignore
  config/eslint/ignore.cjs
  config/eslint/mocha.cjs
  config/eslint/qunit.cjs
  config/package.json
  pnpm-lock.yaml
  tests/blueprints/.eslintrc.cjs
  tests/blueprints/package.json
  tests/blueprints/tests/adapter-test.js
  tests/blueprints/tests/model-test.js
  tests/blueprints/tests/serializer-test.js
  tests/blueprints/tests/transform-test.js
Labels: :dart: canary, :label: chore

#9068 docs: unroll details sections
  packages/request/README.md
  packages/request/src/-private/manager.ts
Labels: :dart: canary, :label: doc

#9070 docs: fix note notation to make use of github formatting
  packages/adapter/README.md
  packages/debug/README.md
  packages/diagnostic/README.md
  packages/json-api/README.md
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/index.ts
  packages/serializer/README.md
  packages/store/README.md
  packages/store/src/index.ts
Labels: :dart: canary, :label: doc

#9069 feat: Improve extensibility
  package.json
  packages/-ember-data/addon/store.ts
  packages/json-api/src/-private/builders/-utils.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/json-api/src/request.ts
  packages/request-utils/src/index.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/store-extension-test.ts
Labels: :dart: canary, :label: feat

#9071 chore: refactor relationships guide
  guides/index.md
  guides/relationships.md
  guides/relationships/configuration/0-one-to-none.md
  guides/relationships/configuration/1-one-to-one.md
  guides/relationships/configuration/2-one-to-many.md
  guides/relationships/configuration/3-many-to-none.md
  guides/relationships/configuration/4-many-to-one.md
  guides/relationships/configuration/5-many-to-many.md
  guides/relationships/features/inverses.md
  guides/relationships/index.md
  guides/relationships/terminology.md
  guides/terminology.md
Labels: :dart: canary, :label: doc

#9072 feat: advanced JSON:API queries & basic request example
  guides/index.md
  guides/requests/examples/0-basic-usage.md
  guides/requests/index.md
  packages/adapter/src/rest.ts
  packages/core-types/src/cache.ts
  packages/json-api/src/-private/builders/-utils.ts
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/serialize.ts
  packages/legacy-compat/src/legacy-network-handler/minimum-serializer-interface.ts
  packages/model/src/-private/promise-many-array.ts
  packages/request-utils/src/index.ts
  packages/request/src/-private/manager.ts
  packages/request/src/-private/types.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-types/q/cache-store-wrapper.ts
  packages/store/src/-types/q/schema-service.ts
  packages/tracking/src/-private.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/adapter/rest-adapter/-ajax-mocks.js
Labels: :dart: canary, :label: feat, :label: doc

#9078 docs: add compatibility table to readme
  README.md
Labels: :dart: canary, :label: chore

#9079 chore: bump ember-compatibility-helpers
  package.json
  patches/ember-compatibility-helpers@1.2.6.patch
  pnpm-lock.yaml
Labels: :label: dependencies, :dependabot:
