Repository warp-drive-data/warp-drive, pull requests merged in 2023-11, with the labels that each got.

#9082 Remove remaining @types/ember* packages
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/recommended-json-api/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: chore

#9084 Add import types
  packages/diagnostic/package.json
  packages/holodeck/package.json
Labels: :dart: canary, :label: chore

#9085 Add type-checking to tests/warp-drive__schema-record
  .github/workflows/main.yml
  config/package.json
  package.json
  packages/schema-record/package.json
  pnpm-lock.yaml
  tests/warp-drive__schema-record/app/app.ts
  tests/warp-drive__schema-record/app/services/store.ts
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  tests/warp-drive__schema-record/tsconfig.json
  turbo.json
Labels: :dart: canary, :label: chore

#9086 Add ESLint config for tests/warp-drive__schema-record
  config/eslint/qunit.cjs
  package.json
  pnpm-lock.yaml
  tests/warp-drive__schema-record/.eslintrc.cjs
  tests/warp-drive__schema-record/app/services/store.ts
  tests/warp-drive__schema-record/config/environment.js
  tests/warp-drive__schema-record/ember-cli-build.js
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/testem.js
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reactivity/resource-test.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  turbo.json
Labels: :dart: canary, :label: chore

#9089 Add type-checking for packages/unpublished-test-infra
  @types/ember-data-qunit-asserts/index.d.ts
  packages/diagnostic/package.json
  packages/unpublished-test-infra/addon-test-support/asserts/assert-all-deprecations.ts
  packages/unpublished-test-infra/addon-test-support/asserts/assert-notification.ts
  packages/unpublished-test-infra/addon-test-support/asserts/index.ts
  packages/unpublished-test-infra/addon-test-support/test.ts
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tsconfig.json
  pnpm-lock.yaml
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
Labels: :dart: canary, :label: chore

#9093 feat(internal): implement legacy mode toggle
  packages/schema-record/.eslintrc.cjs
  packages/schema-record/src/hooks.ts
  packages/schema-record/src/record.ts
  packages/schema-record/src/schema.ts
  packages/schema-record/tsconfig.json
  tests/warp-drive__schema-record/tests/legacy/mode-test.ts
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reactivity/resource-test.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  tests/warp-drive__schema-record/tsconfig.json
Labels: :dart: canary, :label: chore

#9095 feat (internal): support legacy model behaviors in SchemaRecord legacy mode
  config/eslint/qunit.cjs
  config/rollup/external.js
  packages/core-types/rollup.config.mjs
  packages/core-types/src/symbols.ts
  packages/legacy-compat/rollup.config.mjs
  packages/model/rollup.config.mjs
  packages/model/src/-private.ts
  packages/model/src/-private/belongs-to.js
  packages/model/src/-private/has-many.js
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/model-methods.ts
  packages/model/src/-private/model.js
  packages/model/src/-private/notify-changes.ts
  packages/model/src/-private/record-state.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/model/src/migration-support.ts
  packages/schema-record/package.json
  packages/schema-record/rollup.config.mjs
  packages/schema-record/src/-base-fields.ts
  packages/schema-record/src/record.ts
  packages/schema-record/src/schema.ts
  packages/store/src/-private/store-service.ts
  packages/unpublished-test-infra/addon-test-support/asserts/assert-assertion.ts
  pnpm-lock.yaml
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/legacy/mode-test.ts
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  tests/warp-drive__schema-record/tsconfig.json
Labels: :dart: canary, :label: feat

#9097 fix: allow decorator syntax in code comments during yui doc processing
  docs-generator/compile-docs.js
  packages/graph/src/-private/-edge-definition.ts
  packages/json-api/src/-private/builders/-utils.ts
Labels: :dart: canary, :label: bug

#9120 fix: make emergent unsupported behaviors safer in prod
  .eslintignore
  .gitignore
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/store/src/-private/caches/instance-cache.ts
  tests/main/tests/integration/emergent-behavior/recovery/belongs-to-test.ts
  tests/main/tests/integration/emergent-behavior/recovery/has-many-test.ts
  tests/main/tests/integration/references/belongs-to-test.js
Labels: :label: test, :label: bug, backport-lts
