Repository warp-drive-data/warp-drive, pull requests merged in 2023-02, with the labels that each got.

#8412 cleanup: Switch all uses of `@ember/error` to native Error
  packages/adapter/rollup.config.mjs
  packages/adapter/src/error.js
  packages/graph/rollup.config.mjs
  packages/json-api/rollup.config.mjs
  packages/model/index.js
  packages/model/rollup.config.mjs
  tests/main/tests/unit/adapter-errors-test.js
Labels: target:beta, target:release, target:canary, changelog:cleanup, 🔌 Project Unplug 🔌

#8422 fix @ember/error and @ember/string deprecations
  packages/-ember-data/package.json
  packages/adapter/addon/error.js
  packages/adapter/package.json
  packages/debug/package.json
  packages/model/index.js
  packages/model/package.json
  packages/serializer/package.json
  packages/store/index.js
  packages/store/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/main/package.json
  tests/main/tests/unit/adapter-errors-test.js
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/record-data-encapsulation/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: changelog:cleanup, backport-release

#8423 cleanup: move @ember/string to ember-data peer-dependencies
  @types/@ember/owner.ts
  package.json
  packages/-ember-data/package.json
  packages/store/src/-private/store-service.ts
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/request/tests/integration/service-test.ts
  tests/serializer-encapsulation/package.json
Labels: target:canary, changelog:cleanup

#8399 fix: deprecated record-array rejectBy use optional value if supplied
  packages/store/src/-private/record-arrays/identifier-array.ts
  tests/main/tests/unit/record-arrays/record-array-test.js
Labels: target:canary, changelog:bugfix

#8400 fix: deprecated record-array reject use callback
  packages/store/src/-private/record-arrays/identifier-array.ts
  tests/main/tests/unit/record-arrays/record-array-test.js
Labels: target:canary, changelog:bugfix

#8425 force macros to unified version
  package.json
  patches/@embroider__macros@1.9.0.patch
  pnpm-lock.yaml
Labels: target:canary, skip-changelog

#8410 fix: add better embroider test and fix embroider compat
  packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
  tests/embroider-basic-compat/app/models/user.ts
  tests/embroider-basic-compat/tests/acceptance/visit-test.js
Labels: target:release, target:canary, target:lts, changelog:test, changelog:bugfix

#8428 fix: embroider compat
  packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
  packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/store-service.ts
Labels: changelog:bugfix, backport-lts

#8427 fix: embroider compat
  packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
  packages/store/addon/-private/legacy-model-support/schema-definition-service.ts
  packages/store/addon/-private/network/fetch-manager.ts
  packages/store/addon/-private/store-service.ts
  tests/embroider-basic-compat/app/models/user.ts
  tests/embroider-basic-compat/ember-cli-build.js
  tests/embroider-basic-compat/tests/acceptance/visit-test.js
Labels: changelog:bugfix, backport-release

#8426 fix: use macroCondition with all strippable checks
  packages/private-build-infra/src/transforms/babel-plugin-convert-existence-checks-to-macros/index.js
  packages/private-build-infra/src/transforms/babel-plugin-transform-has-debug-package/index.js
  packages/store/src/-private/legacy-model-support/schema-definition-service.ts
  packages/store/src/-private/network/fetch-manager.ts
  packages/store/src/-private/store-service.ts
Labels: target:release, target:canary, target:lts, changelog:perf, ci-assetsize

#8429 chore: ci speedups
  .github/actions/setup/action.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/compat-tests.yml
  .github/workflows/encapsulation-tests.yml
  .github/workflows/infra-tests.yml
  .github/workflows/main.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  package.json
  tsconfig.json
  tsconfig.root.json
  tsconfig.tsbuildinfo
Labels: target:canary, changelog:chore

#8432 fix: ensure classic computed chains support
  .gitignore
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/record-state.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/tracking/src/-private.ts
  tests/main/tests/acceptance/record-array-test.js
  tsconfig.tsbuildinfo
Labels: target:release, target:canary, target:lts, changelog:bugfix

#8433 fix: ensure classic computed chains support (#8432)
  .gitignore
  packages/model/addon/-private/many-array.ts
  packages/model/addon/-private/record-state.ts
  packages/private-build-infra/addon/current-deprecations.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/managers/record-array-manager.ts
  packages/store/addon/-private/record-arrays/identifier-array.ts
  packages/tracking/src/-private.ts
  tests/main/tests/acceptance/record-array-test.js
Labels: changelog:bugfix, backport-release

#8435 fix: de-cycle ember-concurrency access of promise
  packages/store/src/-private/proxies/promise-proxies.ts
Labels: target:release, target:canary, target:lts, changelog:bugfix

#8436 perf: fix: eliminate SSR/Test memory leak
  packages/graph/src/-private/graph/graph.ts
  packages/graph/src/-private/graph/index.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/model.js
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/caches/record-data-for.ts
  packages/store/src/-private/index.ts
  pnpm-lock.yaml
  tests/main/package.json
  tests/main/tests/unit/model-test.js
Labels: target:release, target:canary, target:lts, changelog:bugfix, changelog:perf

#8438 Backport EmberConcurrency and Memory Leak Fixes
  packages/model/addon/-private/model.js
  packages/record-data/addon/-private/graph/graph.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/caches/record-data-for.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/proxies/promise-proxies.ts
  pnpm-lock.yaml
  tests/main/package.json
  tests/main/tests/unit/model-test.js
Labels: changelog:bugfix, backport-lts, changelog:perf

#8439 Backport EmberConcurrency and Memory Leak fixes
  packages/model/addon/-private/model.js
  packages/record-data/addon/-private/graph/graph.ts
  packages/record-data/addon/-private/graph/index.ts
  packages/record-data/addon/-private/record-data.ts
  packages/store/addon/-private/caches/instance-cache.ts
  packages/store/addon/-private/caches/record-data-for.ts
  packages/store/addon/-private/index.ts
  packages/store/addon/-private/proxies/promise-proxies.ts
  pnpm-lock.yaml
  tests/main/package.json
  tests/main/tests/unit/model-test.js
Labels: changelog:bugfix, backport-release, changelog:perf

#8440 Correction made to the Model.relatedTypes documentation
  packages/model/src/-private/model.js
Labels: target:canary, changelog:doc
