Repository warp-drive-data/warp-drive, pull requests merged in 2023-09, with the labels that each got.

#8819 fix: `JSONAPISerializer.shouldSerializeHasMany` relation param type
  packages/serializer/src/json.js
Labels: target:canary, changelog:doc

#8812 fix typo
  tests/main/tests/integration/adapter/record-persistence-test.js
Labels: target:canary, changelog:chore

#8807 feat: implement graph diffing
  .eslintignore
  @types/ember-data-qunit-asserts/index.d.ts
  ember-data-types/q/record-data-schemas.ts
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/-edge-definition.ts
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/debug/assert-polymorphic-type.ts
  packages/graph/src/-private/edges/collection.ts
  packages/graph/src/-private/edges/resource.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/add-to-related-records.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/graph/src/-private/operations/remove-from-related-records.ts
  packages/graph/src/-private/operations/replace-related-record.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/references/has-many.ts
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  packages/store/src/-private/caches/identifier-cache.ts
  packages/unpublished-test-infra/addon-test-support/deprecated-test.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-better.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/assert-notification.ts
  packages/unpublished-test-infra/addon-test-support/qunit-asserts/index.ts
  packages/unpublished-test-infra/addon-test-support/setup-notifications.ts
  packages/unpublished-test-infra/addon-test-support/test-in-debug.ts
  packages/unpublished-test-infra/addon-test-support/version.d.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/graph/ember-cli-build.js
  tests/graph/package.json
  tests/graph/tests/integration/graph/diff-preservation-test.ts
  tests/graph/tests/integration/graph/duplicate-data-test.ts
  tests/graph/tests/integration/graph/edge-removal/helpers.ts
  tests/graph/tests/integration/graph/edge-removal/setup.ts
  tests/graph/tests/integration/graph/edge-test.ts
  tests/graph/tests/integration/graph/operations-test.ts
  tests/graph/tests/integration/graph/order-preservation-test.ts
  tests/main/tests/integration/adapter/rest-adapter-test.js
  tests/main/tests/integration/records/unload-test.js
  tests/main/tests/integration/relationships/has-many-test.js
  tests/main/tests/integration/relationships/many-to-many-test.js
  tests/main/tests/integration/snapshot-test.js
  tests/main/tests/test-helper.js
  tests/main/tests/unit/model/relationships/belongs-to-test.js
  tests/main/tests/unit/model/relationships/has-many-test.js
  tsconfig.json
Labels: target:canary, Relationship Refactor, changelog:perf, ci-perf

#8823 fix: graph instantiation should not be required
  packages/-ember-data/addon/store.ts
  tests/adapter-encapsulation/app/services/store.js
  tests/graph/app/services/store.ts
  tests/serializer-encapsulation/app/services/store.js
Labels: target:canary, changelog:chore

#8824 feat: relationshipRollback, serializePatch
  .eslintrc.js
  ember-data-types/cache/cache.ts
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/json-api/README.md
  packages/json-api/package.json
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/serialize.ts
  packages/json-api/src/request.ts
  packages/request-utils/src/index.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/managers/cache-manager.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/json-api/package.json
  tests/json-api/tests/integration/serialize-test.ts
  tests/json-api/tests/test-helper.js
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/relationships/rollback-test.ts
  tsconfig.json
Labels: target:canary, changelog:feat

#8825 feat: more docs for builders
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/request.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/request.ts
  packages/rest/src/-private/builders/query.ts
  tests/docs/fixtures/expected.js
Labels: target:canary, changelog:doc

#8826 fix createRecord error when no adapter is present
  packages/store/src/-private/store-service.ts
  tests/adapter-encapsulation/tests/integration/generate-id-test.js
Labels: target:canary, changelog:bugfix

#8828 fix: set headers after setResponse in Fetch handler
  packages/request/src/fetch.ts
Labels: target:canary, changelog:bugfix

#8829 chore: eliminate dead build code
  packages/-ember-data/index.js
  packages/debug/index.js
  packages/private-build-infra/package.json
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/private-build-infra/src/utilities/rollup-private-module.js
  pnpm-lock.yaml
Labels: target:canary, changelog:chore

#8830 chore: cleanup actions/setup usage
  .github/actions/prepare-build/action copy.yml
  .github/actions/prepare-build/action.yml
  .github/workflows/alpha-release.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/beta-release.yml
  .github/workflows/compat-tests.yml
  .github/workflows/deprecations-check.yml
  .github/workflows/docs-and-blueprint-tests.yml
  .github/workflows/encapsulation-tests.yml
  .github/workflows/infra-tests.yml
  .github/workflows/main.yml
  .github/workflows/partner-tests.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
Labels: target:canary, changelog:chore

#8831 fix: cleanup build deps and add @ember/string to REST/ActiveRecord builder peer-deps
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/active-record/rollup.config.mjs
  packages/json-api/rollup.config.mjs
  packages/legacy-compat/package.json
  packages/legacy-compat/rollup.config.mjs
  packages/request-utils/rollup.config.mjs
  packages/rest/package.json
  packages/rest/rollup.config.mjs
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/graph/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, changelog:bugfix

#8842 fix: handle Immutable Response objects
  packages/request/src/-private/context.ts
  packages/request/src/fetch.ts
Labels: target:canary, changelog:bugfix

#8843 chore: run pnpm update, dedupe
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/builders/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/recommended-json-api/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8844 chore: fixup deps in new app
  pnpm-lock.yaml
  tests/recommended-json-api/package.json
Labels: dependencies, target:canary, skip-changelog

#8848 feat: add request options documentation parts to find-record builder
  packages/active-record/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/request-utils/src/index.ts
  packages/rest/src/-private/builders/find-record.ts
Labels: target:canary, changelog:doc

#8850 Overwrite addMixin
  packages/model/src/-private/promise-many-array.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
Labels: target:canary, changelog:bugfix

#8858 chore: update required labels
  .github/renovate.json
  .github/workflows/enforce-pr-labels-beta.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .github/workflows/enforce-pr-labels-lts-prev.yml
  .github/workflows/enforce-pr-labels-lts.yml
  .github/workflows/enforce-pr-labels-old-release.yml
  .github/workflows/enforce-pr-labels-release.yml
  contributing/submitting-prs.md
Labels: target:canary, changelog:chore

#8859 chore: update target labels
  .github/renovate.json
  .github/workflows/enforce-pr-labels-beta.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .github/workflows/enforce-pr-labels-lts-prev.yml
  .github/workflows/enforce-pr-labels-lts.yml
  .github/workflows/enforce-pr-labels-old-release.yml
  .github/workflows/enforce-pr-labels-release.yml
  contributing/submitting-prs.md
  package.json
Labels: :dart: canary, :label: chore

#8861 chore: remove runloop usage
  tests/main/tests/integration/relationships/one-to-many-test.js
Labels: :dart: canary, :label: chore

#8864 test: confirm records unload properly for #8863
  tests/main/tests/integration/records/unload-test.js
Labels: :dart: canary, :dart: lts, :label: test

#8865 test: confirm records unload properly for #8863
  tests/main/tests/integration/records/unload-test.js
Labels: :label: test, backport-lts

#8866 Add tests for parse-cache-control
  packages/request-utils/src/index.ts
  tests/builders/tests/unit/parse-cache-control-test.ts
Labels: :dart: canary, :label: test

#8868 Add tests for filter-empty request util
  packages/request-utils/src/index.ts
  tests/builders/tests/unit/filter-empty-test.ts
Labels: :dart: canary, :label: test

#8849 feat: docs, tests and fixes for create/update/deleteRecord builders
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/model.d.ts
  packages/model/src/-private/record-state.ts
  packages/request/src/-private/types.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/store/src/-private/cache-handler.ts
  pnpm-lock.yaml
  tests/builders/app/models/user-setting.ts
  tests/builders/app/services/store.ts
  tests/builders/package.json
  tests/builders/tests/integration/create-record-test.ts
  tests/builders/tests/integration/delete-record-test.ts
  tests/builders/tests/integration/update-record-test.ts
  tests/builders/tests/test-helper.js
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/builders/tests/unit/rest-builder-test.ts
  tests/docs/fixtures/expected.js
  tests/request/tests/integration/immutability-test.ts
Labels: :dart: canary, :label: test, :label: feat

#8876 fix: Fetch handler should account for empty body
  packages/request/src/fetch.ts
Labels: :dart: canary, :label: bug

#8878 test: add basic test for Fetch handler
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/mock-server/.gitignore
  packages/mock-server/LICENSE.md
  packages/mock-server/README.md
  packages/mock-server/client/index.js
  packages/mock-server/ember-data-logo-dark.svg
  packages/mock-server/ember-data-logo-light.svg
  packages/mock-server/package.json
  packages/mock-server/server/index.js
  packages/mock-server/server/localhost-cert.pem
  packages/mock-server/server/localhost-privkey.pem
  packages/request/src/-private/types.ts
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  pnpm-lock.yaml
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/builders/tests/unit/rest-builder-test.ts
  tests/request/.mock-cache/b2776322/GET-0-users/1/res.body.br
  tests/request/.mock-cache/b2776322/GET-0-users/1/res.meta.json
  tests/request/mock-server.mjs
  tests/request/package.json
  tests/request/tests/integration/fetch-handler-test.ts
  tests/request/tests/test-helper.js
  tsconfig.root.json
Labels: :dart: canary, :label: test

#8892 doc: Fix paths in transform deprecations
  packages/-ember-data/app/transforms/boolean.js
  packages/-ember-data/app/transforms/date.js
  packages/-ember-data/app/transforms/number.js
  packages/-ember-data/app/transforms/string.js
Labels: :dart: release, :dart: canary, :label: bug

#8891 chore: add tests for sort-order
  tests/main/tests/integration/relationships/has-many-sort-order-test.js
Labels: :dart: canary, :label: test

#8912 chore: docs for holodeck
  packages/holodeck/README.md
Labels: :dart: canary, :label: chore

#8913 chore: fix flaky test
  tests/main/tests/acceptance/relationships/has-many-test.js
Labels: :dart: canary, :label: test

#8911 chore: remove unneeded type cast
  tests/request/tests/integration/fetch-handler-test.ts
Labels: :dart: canary, :label: chore

#8923 chore: prepare files for new eslint plugin
  .eslintrc.js
  package.json
  packages/eslint-plugin-ember-data/package.json
  packages/eslint-plugin-ember-data/src/index.js
  packages/eslint-plugin-ember-data/src/rules/.gitkeep
  packages/unpublished-eslint-rules/package.json
  pnpm-lock.yaml
Labels: :dart: canary, :label: chore

#8925 feat: implement postQuery builder
  ember-data-types/request.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/request.ts
  tests/builders/tests/unit/json-api-builder-test.ts
Labels: :dart: canary, :label: feat

#8927 fix: live-array delete sync should not clear the set on length match
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/records/unload-all-test.js
Labels: :dart: canary, :label: bug

#8928 chore: bump ember-cli-babel@8.1.0
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  patches/ember-cli-babel@8.0.0.patch
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/builders/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/recommended-json-api/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: :label: dependencies, :dart: canary

#8926 fix: unloadAll should cleanup live-array membership
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/records/unload-all-test.js
Labels: :label: bug, backport-lts

#8929 fix: live-array delete sync should not clear the set on length match
  packages/store/src/-private/managers/record-array-manager.ts
  tests/main/tests/integration/records/unload-all-test.js
Labels: :label: bug, backport-release

#8930 chore: get last request for any record on instantiation
  packages/model/src/-private/record-state.ts
Labels: :dart: canary, :label: chore

#8934 fix: JSONAPISerializer should not reify empty records
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  tests/main/tests/integration/relationships/has-many-test.js
Labels: :dart: release, :dart: canary, :dart: lts, :label: bug

#8933 fix: JSONAPISerializer should not reify empty records
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/serializer/src/json-api.js
  tests/main/tests/integration/identifiers/lid-reflection-test.ts
  tests/main/tests/integration/relationships/has-many-test.js
Labels: :label: bug, backport-lts

#8935 feat: (private) implement basic field support for schema-record
  .eslintrc.js
  ember-data-types/q/identifier.ts
  ember-data-types/q/record-data-schemas.ts
  packages/graph/src/-private/-edge-definition.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-data-fetch.js
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/model/src/-private/attr.js
  packages/model/src/-private/belongs-to.js
  packages/model/src/-private/has-many.js
  packages/model/src/-private/model.d.ts
  packages/model/src/-private/model.js
  packages/request/src/index.ts
  packages/schema-record/package.json
  packages/schema-record/src/index.ts
  packages/schema-record/tsconfig.json
  packages/serializer/src/-private/embedded-records-mixin.js
  packages/serializer/src/json-api.js
  packages/serializer/src/json.js
  packages/serializer/src/rest.js
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  pnpm-lock.yaml
  tests/json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/json-api/tests/integration/serialize-test.ts
  tests/main/tests/integration/record-data/store-wrapper-test.ts
  tests/main/tests/integration/serializers/json-serializer-test.js
  tests/main/tests/integration/serializers/rest-serializer-test.js
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/main/tests/unit/debug-test.js
  tests/schema-record/app/models/user-setting.ts
  tests/schema-record/app/services/store.ts
  tests/schema-record/config/environment.js
  tests/schema-record/package.json
  tests/schema-record/tests/reads/basic-fields-test.ts
  tsconfig.json
  tsconfig.root.json
Labels: :dart: canary, :label: feat

#8942 test: show stateful / DI based handler pattern
  tests/request/tests/integration/stateful-handler-test.ts
Labels: :dart: canary, :label: test
