Repository warp-drive-data/warp-drive, pull requests merged in 2023-05, with the labels that each got.

#8588 chore: update various deps
  package.json
  packages/-ember-data/package.json
  packages/debug/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, skip-changelog

#8589 chore: bump build deps
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, skip-changelog

#8590 chore: bump webpack
  package.json
  packages/-ember-data/package.json
  packages/debug/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: target:canary, skip-changelog

#8591 chore: remove unneeded glob
  package.json
  packages/private-build-infra/package.json
  pnpm-lock.yaml
Labels: target:canary, skip-changelog

#8594 fix: restore Store extends EmberObject :(
  packages/store/src/-private/store-service.ts
Labels: target:beta, target:release, target:canary, changelog:bugfix, lts-4-12

#8576 LegacyHandler providing frozen options to Adapters
  packages/request/src/-private/context.ts
  tests/adapter-encapsulation/tests/integration/queries-test.js
Labels: target:beta, target:release, target:canary, changelog:bugfix, lts-4-12

#8597 fix: dont share promise cache for all fields
  packages/model/src/-private/legacy-relationships-support.ts
  tests/main/tests/integration/relationships/belongs-to-test.js
Labels: target:beta, target:release, target:canary, changelog:bugfix, lts-4-12

#8566 Avoid unnecessary identity notification when record is saved
  .gitignore
  ember-data-types/cache/cache.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/adapter/rest-adapter-test.js
  tests/main/tests/integration/record-data/record-data-errors-test.ts
  tests/main/tests/integration/record-data/record-data-state-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/references/autotracking-test.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, lts-4-12

#8598 fix: docs generation should maintain a stable relative path
  docs-generator/compile-docs.js
  tests/docs/index.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:doc, changelog:bugfix

#8601 docs: fix forgotten references to FetchManager
  packages/store/README.md
  packages/store/src/index.ts
Labels: target:beta, target:release, target:canary, changelog:doc, lts-4-12

#8608 chore: Update webpack
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: target:beta, target:release, target:canary, skip-changelog, lts-4-12

#8621 There are cases where payload is an object, and normalizeErrorRespons…
  packages/adapter/src/rest.ts
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, lts-4-12, lts-4-8
