Repository warp-drive-data/warp-drive, pull requests merged in 2023-08, with the labels that each got.

#8779 chore: add test to demonstrate create props work as expected
  packages/-ember-data/tests/unit/store/create-record-test.js
Labels: changelog:test, backport-lts-prev

#8780 chore: add test to demonstrate create props work as expected
  tests/main/tests/unit/store/create-record-test.js
Labels: target:canary, changelog:test

#8797 Drop support for `ember-cli-mocha` and `ember-mocha` when generating test blueprints
  packages/adapter/blueprints/adapter-test/mocha-files/__root__/__path__/__test__.js
  packages/adapter/blueprints/adapter-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/model/blueprints/model-test/mocha-files/__root__/__path__/__test__.js
  packages/model/blueprints/model-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/private-build-infra/src/utilities/test-framework-detector.js
  packages/serializer/blueprints/serializer-test/mocha-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/serializer-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/transform-test/mocha-files/__root__/__path__/__test__.js
  packages/serializer/blueprints/transform-test/mocha-rfc-232-files/__root__/__path__/__test__.js
  tests/blueprints/fixtures/adapter-test/foo-mocha-0.12.js
  tests/blueprints/fixtures/adapter-test/mocha-rfc232-addon.js
  tests/blueprints/fixtures/adapter-test/mocha-rfc232.js
  tests/blueprints/fixtures/model-test/foo-mocha-0.12.js
  tests/blueprints/fixtures/model-test/mocha-rfc232-addon.js
  tests/blueprints/fixtures/model-test/mocha-rfc232.js
  tests/blueprints/fixtures/serializer-test/foo-mocha-0.12.js
  tests/blueprints/fixtures/serializer-test/mocha-rfc232-addon.js
  tests/blueprints/fixtures/serializer-test/mocha-rfc232.js
  tests/blueprints/fixtures/transform-test/mocha-0.12.js
  tests/blueprints/fixtures/transform-test/mocha-rfc232-addon.js
  tests/blueprints/fixtures/transform-test/mocha-rfc232.js
  tests/blueprints/tests/adapter-test.js
  tests/blueprints/tests/model-test.js
  tests/blueprints/tests/serializer-test.js
  tests/blueprints/tests/transform-test.js
Labels: target:canary, changelog:cleanup

#8794 Fix check for new records in JSONAPISerializer.serializeHasMany
  packages/serializer/src/json-api.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix

#8798 feat: implement a simple LifetimeService utility, improve document reconstruction
  ember-data-types/cache/document.ts
  packages/json-api/src/-private/cache.ts
  packages/request-utils/src/index.ts
  packages/request/src/fetch.ts
Labels: target:canary, changelog:feat

#8799 chore: bump overrides
  package.json
  pnpm-lock.yaml
Labels: dependencies, target:canary, skip-changelog

#8801 chore: resolve deprecation in fastboot app
  tests/fastboot/app/services/store.ts
Labels: target:canary, changelog:chore

#8802 chore: fix fastboot-testing deprecation
  tests/fastboot/config/fastboot-testing.js
Labels: target:canary, changelog:chore

#8800 chore: update ember-cli-babel to 8.x
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  patches/ember-cli-babel@8.0.0.patch
  patches/ember-compatibility-helpers@1.2.6.patch
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/builders/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: dependencies, target:canary, skip-changelog

#8791 fix: clear relationships properly when unloading new records
  packages/graph/src/-private/graph.ts
  packages/json-api/src/-private/cache.ts
  tests/graph/ember-cli-build.js
  tests/graph/tests/integration/graph/edge-removal/abstract-edge-removal-test.ts
  tests/main/tests/index.html
  tests/main/tests/integration/records/new-record-unload-test.js
Labels: target:beta, target:release, target:canary, target:lts, changelog:bugfix, lts-4-12

#8805 perf: stash idea around faster lookup
  ember-data-types/q/fetch-manager.ts
  ember-data-types/q/identifier.ts
  packages/graph/src/-private/operations/update-relationship.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/utils/identifier-debug-consts.ts
Labels: target:canary, changelog:perf, ci-perf

#8763 chore: simpler graph transactions
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/update-relationship.ts
Labels: target:canary, changelog:perf, ci-perf
