Repository warp-drive-data/warp-drive, pull requests merged in 2024-07, with the labels that each got.

#9511 Add @ember/string v4 to peerDependencies
  packages/request-utils/package.json
Labels: :dart: canary, :label: bug

#9509 chore: cleanup CacheHandler factoring
  packages/request/src/-private/manager.ts
  packages/store/src/-private.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/cache-handler/handler.ts
  packages/store/src/-private/cache-handler/types.ts
  packages/store/src/-private/cache-handler/utils.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: chore

#9512 Fix typos in README.md
  packages/experiments/src/data-worker/README.md
Labels: :dart: canary, :label: doc

#9503 feat: request deduping & <Request /> invalidate subscriptions
  packages/diagnostic/src/-define.ts
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/index.ts
  packages/diagnostic/src/internals/config.ts
  packages/diagnostic/src/internals/run.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/ember/README.md
  packages/ember/src/-private/request.gts
  packages/holodeck/server/index.js
  packages/request-utils/src/index.ts
  packages/request/src/-private/context.ts
  packages/request/src/-private/future.ts
  packages/request/src/-private/manager.ts
  packages/request/src/-private/types.ts
  packages/request/src/-private/utils.ts
  packages/store/src/-private/cache-handler/handler.ts
  packages/store/src/-private/cache-handler/types.ts
  packages/store/src/-private/cache-handler/utils.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/index.ts
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/src/test-support/asserts/assert-notification.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/package.json
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/request-dedupe-test.ts
  tests/main/tsconfig.json
  tests/warp-drive__ember/.mock-cache/08aa54ba/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/08aa54ba/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/08aa54ba/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/08aa54ba/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/494b610c/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/494b610c/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/494b610c/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/494b610c/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/8a4a94fe/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/8a4a94fe/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/8a4a94fe/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/8a4a94fe/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-2-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-2-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-3-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-3-users/1/res.meta.json
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
  tests/warp-drive__ember/tests/integration/request-component-subscription-test.gts
Labels: :dart: canary, :label: feat

#9515 chore: dont crash for non-existent asset requests
  packages/diagnostic/server/bun/fetch.js
Labels: :dart: canary, :label: chore
