Repository warp-drive-data/warp-drive, pull requests merged in 2024-05, with the labels that each got.

#9389 Backport request, request-utils, store cache-handler changes to 4.12
  .eslintrc.js
  .gitignore
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/find-record.ts
  packages/legacy-compat/src/builders/query.ts
  packages/legacy-compat/src/builders/save-record.ts
  packages/legacy-compat/src/builders/utils.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/request-utils/LICENSE.md
  packages/request-utils/README.md
  packages/request-utils/addon-main.js
  packages/request-utils/babel.config.json
  packages/request-utils/ember-data-logo-dark.svg
  packages/request-utils/ember-data-logo-light.svg
  packages/request-utils/package.json
  packages/request-utils/rollup.config.mjs
  packages/request-utils/rollup/external.cjs
  packages/request-utils/src/.gitkeep
  packages/request-utils/src/index.ts
  packages/request/src/-private/debug.ts
  packages/request/src/-private/types.ts
  packages/request/src/-private/utils.ts
  packages/request/src/fetch.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/main/tests/integration/legacy-compat/find-all-test.ts
  tests/main/tests/integration/legacy-compat/find-record-test.ts
  tests/main/tests/integration/legacy-compat/query-test.ts
  tests/request/tests/integration/abort-test.ts
  tsconfig.root.json
Labels: :label: feat, backport-lts

#9391 fix: dont fall-through after shouldAttempt on refresh
  packages/ember/src/-private/request.gts
Labels: :dart: canary, :label: bug

#9390 docs: fix readme links in @warp-drive/ember
  packages/ember/README.md
Labels: :dart: canary, :label: doc

#9392 Fix some typos after reading code
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/schema/src/parser/compile/json-schema-spec.ts
  packages/store/src/-private/store-service.ts
Labels: code-review, :dart: canary, :label: chore

#9393 Update types on typescript guide part 4
  guides/typescript/4-typing-requests.md
Labels: :dart: canary, :label: doc, typescript

#9385 fix: Make IS_MAYBE_MIRAGE simplified
  packages/request/src/fetch.ts
Labels: :dart: canary, :label: chore

#9395 Update strategy.json to mirror publish @warp-drive/schema-record
  release/strategy.json
Labels: :dart: canary, :label: chore

#9398 chore: dont --compile during prepack
  packages/codemods/package.json
  packages/schema/package.json
Labels: :dart: canary, :label: chore

#9399 types: limit traversal depth on include path generation
  packages/core-types/src/record.ts
  packages/core-types/src/record.type-test.ts
Labels: :dart: canary, :label: chore, typescript

#9400 feat: add expectId util
  packages/legacy-compat/src/utils.ts
Labels: :dart: canary, :label: feat

#9401 feat: preserve lids returned by the API in legacy normalization
  packages/serializer/src/-private/embedded-records-mixin.js
  packages/serializer/src/json.js
Labels: :dart: canary, :label: feat

#9396 fix: Resolve promise types for props passed to `store.createRecord()`
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/store-service.type-test.ts
Labels: :dart: canary, :label: feat, typescript

#9403 feat: deprecate store extending EmberObject
  packages/private-build-infra/virtual-packages/deprecations.d.ts
  packages/private-build-infra/virtual-packages/deprecations.js
  packages/store/src/-private/store-service.ts
  tests/docs/fixtures/expected.js
  tests/main/ember-cli-build.js
Labels: :dart: canary, :label: deprecation

#9441 Fix: @attr defaultValue() results should persist after init (#9355)
  packages/json-api/src/-private/cache.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
Labels: :label: bug, backport-lts-prev

#9443 feat: universal consts
  packages/core-types/src/-private.ts
  packages/core-types/src/request.ts
  packages/request/src/-private/manager.ts
  packages/request/src/-private/promise-cache.ts
Labels: :dart: canary, :dart: lts, :label: feat, :dart: lts-prev

#9444 feat: rename LifetimesService => CachePolicy for clarity
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/core-types/src/request.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/request-utils/src/index.ts
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/store/src/-private.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/index.ts
  tests/docs/fixtures/expected.js
  tests/example-json-api/app/services/store.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
Labels: :dart: canary, :label: feat

#9450 feat: improve typing around Model and createRecord
  packages/-ember-data/package.json
  packages/-ember-data/src/store.ts
  packages/adapter/src/json-api.ts
  packages/adapter/src/rest.ts
  packages/debug/src/data-adapter.ts
  packages/model/src/-private/errors.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model-methods.ts
  packages/model/src/-private/model.ts
  packages/model/src/-private/model.type-test.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/model/src/-private/type-utils.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/store-service.type-test.ts
  tests/fastboot/app/models/person.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/identifiers/lid-reflection-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
Labels: :dart: canary, :label: feat, typescript

#9453 feat: update SchemaService to reflect RFC updates
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/schema-provider.ts
  packages/model/src/migration-support.ts
  packages/schema-record/src/managed-array.ts
  packages/schema-record/src/managed-object.ts
  packages/schema-record/src/record.ts
  packages/schema-record/src/schema.ts
  packages/store/src/-types/q/schema-service.ts
  tests/ember-data__json-api/tests/utils/schema.ts
  tests/ember-data__model/tests/utils/schema.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/utils/schema.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
Labels: :dart: canary, :label: feat

#9455 fix: config version lookup needs to be project location aware
  packages/build-config/src/-private/utils/features.ts
  packages/build-config/vite.config.mjs
Labels: :dart: canary, :label: bug

#9454 Allow RequestState.abort to be used with on modifier
  packages/ember/src/-private/request-state.ts
Labels: :dart: canary, :label: bug

#9456 fix: visibilitychange => hidden should update unavailableStart
  packages/ember/src/-private/request.gts
Labels: :dart: canary, :label: bug

#9457 feat: the big list of versions
  README.md
Labels: :dart: canary, :label: chore

#9407 feat: v2 addons
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  pnpm-lock.yaml
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: feat
