Repository warp-drive-data/warp-drive, pull requests merged in 2024-10, with the labels that each got.

#9542 Update the paths in the canary tsconfig example
  guides/typescript/1-configuration.md
Labels: :dart: canary, :label: doc

#9543 Improvement: Setting Up The Project
  contributing/setting-up-the-project.md
  packages/holodeck/server/ensure-cert.js
  packages/holodeck/server/index.js
Labels: :dart: canary, :label: chore

#9556 chore: bump @eslint/js and fix violation
  config/package.json
  packages/graph/src/-private/graph.ts
  pnpm-lock.yaml
Labels: :dart: canary, :label: chore

#9540 fix: ensure SchemaRecord immutability
  packages/schema-record/src/-private/managed-array.ts
  packages/schema-record/src/hooks.ts
  packages/schema-record/src/record.ts
  tests/warp-drive__schema-record/tests/writes/array-test.ts
  tests/warp-drive__schema-record/tests/writes/object-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-array-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-object-test.ts
Labels: :dart: canary, :label: feat

#9566 fix: attr should support transforms with union serialized types
  packages/eslint-plugin-ember-data/package.json
  packages/model/src/-private/attr.ts
  packages/model/src/-private/attr.type-test.ts
  packages/serializer/package.json
  packages/serializer/src/-private/transforms/boolean.ts
  packages/serializer/src/-private/transforms/boolean.type-test.ts
  packages/serializer/tsconfig.json
  pnpm-lock.yaml
  tests/main/app/models/foo.js
  tests/main/app/models/foo.ts
Labels: :dart: canary, :label: bug, typescript

#9579 fix: use an explicit re-export file for the data-adapter
  packages/debug/package.json
  packages/debug/src/_app_/data-adapter.js
  packages/debug/vite.config.mjs
Labels: :dart: canary, :label: bug

#9580 fix: cleanup stale config documentation
  packages/-ember-data/README.md
  packages/-ember-data/src/index.ts
Labels: :dart: canary, :label: doc

#9583 feat|doc|fix: cleanup includes story
  guides/requests/examples/0-basic-usage.md
  guides/typescript/5-typing-includes.md
  guides/typescript/index.md
  packages/adapter/src/json-api.ts
  packages/adapter/src/rest.ts
  packages/core-types/src/params.ts
  packages/core-types/src/record.ts
  packages/core-types/src/record.type-test.ts
  packages/store/src/-private/store-service.ts
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: bug

#9586 Fix `until` in deprecation warning `ember-data:schema-service-updates` (must be 6.0 instead of 5.0)
  packages/model/src/-private/schema-provider.ts
  packages/schema-record/src/schema.ts
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: doc
