Repository warp-drive-data/warp-drive, pull requests merged in 2024-12, with the labels that each got.

#9618 Update community-resources.md
  guides/community-resources.md
Labels: :dart: canary, :label: doc

#9619 Support @ember/test-waiters v4
  packages/-ember-data/package.json
  packages/ember/package.json
  packages/legacy-compat/package.json
  packages/request/package.json
  pnpm-lock.yaml
  tests/ember-data__adapter/package.json
Labels: :dart: canary, :label: feat

#9620 Starwars
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/build-config/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/eslint-plugin-warp-drive/package.json
  packages/experiments/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/blueprints/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: chore

#9623 chore: updates to match v4 main
  .github/workflows/compat-tests.yml
  .github/workflows/docs-and-blueprint-tests.yml
  .github/workflows/enforce-pr-labels-canary.yml
  .vscode/settings.json
  config/eslint/typescript.js
  package.json
  packages/tracking/src/-private.ts
Labels: :dart: canary, :label: chore

#9625 Enable more workflows on v4-main
  .github/workflows/asset-size-check.yml
  .github/workflows/main.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
Labels: :dart: lts, :label: chore
