Repository warp-drive-data/warp-drive, pull requests merged in 2024-02, with the labels that each got.

#9220 feat: request infra improvements
  config/package.json
  docs-generator/yuidoc.json
  package.json
  packages/-ember-data/package.json
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/adapter/package.json
  packages/core-types/package.json
  packages/core-types/src/request.ts
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/src/index.ts
  packages/request/src/-private/context.ts
  packages/request/src/-private/debug.ts
  packages/request/src/fetch.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/schema-record/package.json
  packages/schema/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/index.ts
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/blueprints/package.json
  tests/builders/package.json
  tests/builders/tests/unit/active-record-builder-test.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/builders/tests/unit/rest-builder-test.ts
  tests/docs/fixtures/expected.js
  tests/docs/index.js
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__request/tests/integration/fetch-handler-test.ts
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/performance/package.json
  tests/recommended-json-api/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: release, :dart: canary, :dart: lts, :label: feat, lts-4-12

#9132 Add auth handler guides
  guides/requests/examples/0-basic-usage.md
  guides/requests/examples/1-auth.md
Labels: :dart: canary, :label: doc

#9221 fix: prevent rollbackRelationships from setting remoteState and localState to the same array reference
  packages/graph/src/-private/-diff.ts
  tests/main/tests/integration/relationships/rollback-test.ts
Labels: :dart: release, :dart: canary, :label: bug

#9222 fix: prevent rollbackRelationships from setting remoteState and localState to the same array reference
  packages/graph/src/-private/-diff.ts
  tests/main/tests/integration/relationships/rollback-test.ts
Labels: :label: bug, backport-release

#9223 feat: improve builder extensibility and add postQuery builder
  ember-data-types/request.ts
  package.json
  packages/-ember-data/addon/store.ts
  packages/json-api/src/-private/builders/-utils.ts
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/json-api/src/request.ts
  packages/request-utils/src/index.ts
  tests/builders/tests/unit/json-api-builder-test.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/store-extension-test.ts
Labels: :label: feat, backport-release

#9224 feat: improved lifetimes-service capabilities
  packages/-ember-data/app/transforms/boolean.js
  packages/-ember-data/app/transforms/date.js
  packages/-ember-data/app/transforms/number.js
  packages/-ember-data/app/transforms/string.js
  packages/request-utils/src/index.ts
  packages/store/src/-private/cache-handler.ts
  tests/docs/fixtures/expected.js
  tests/recommended-json-api/app/services/store.ts
Labels: :label: feat, backport-release

#9225 fix: backport various fixes to 5.3
  .vscode/settings.json
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/request-utils/src/index.ts
  packages/store/src/-private/caches/identifier-cache.ts
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
  tests/main/tests/integration/records/polymorphic-find-record-test.ts
  tests/main/tests/integration/relationships/has-many-test.js
Labels: :label: bug, backport-release

#9231 chore: additional release automation
  .github/workflows/beta-release.yml
  .github/workflows/release/promote-lts.yml
  .github/workflows/release/publish-beta.yml
  .github/workflows/release/publish-canary.yml
  .github/workflows/release/publish-lts.yml
  .github/workflows/release/publish-stable.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
  publish/core/publish/steps/confirm-strategy.ts
  publish/core/publish/steps/generate-strategy.ts
  publish/core/utils/package.ts
  publish/index.ts
  publish/strategy.json
  publish/utils/flags-config.ts
  release/core/promote/index.ts
  release/core/publish/index.ts
  release/core/publish/steps/bump-versions.ts
  release/core/publish/steps/confirm-strategy.ts
  release/core/publish/steps/generate-strategy.ts
  release/core/publish/steps/generate-tarballs.ts
  release/core/publish/steps/print-strategy.ts
  release/core/publish/steps/publish-packages.ts
  release/core/release-notes/index.ts
  release/core/release-notes/steps/confirm-changelogs.ts
  release/core/release-notes/steps/get-changes.ts
  release/core/release-notes/steps/submit-pr-to-branch.ts
  release/core/release-notes/steps/update-changelogs.ts
  release/core/utils/next-version.ts
  release/guide/canary.md
  release/help/-utils.ts
  release/help/docs.ts
  release/help/sections/about.ts
  release/help/sections/manual.ts
  release/index.ts
  release/strategy.json
  release/tsconfig.json
  release/utils/channel.ts
  release/utils/cmd.ts
  release/utils/flags-config.ts
  release/utils/git.ts
  release/utils/json-file.ts
  release/utils/package.ts
  release/utils/parse-args.ts
  release/utils/write.ts
Labels: :dart: beta, :dart: release, :dart: canary, :dart: lts, :label: chore, lts-4-12

#9233 chore: fix canary chron publishing & release changelog generation
  .github/workflows/release_publish-canary.yml
  .github/workflows/release_publish-lts.yml
  .github/workflows/release_publish-stable.yml
Labels: :dart: canary, :label: chore

#9237 chore: fix publishing of core-types when strategy is private
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: chore

#9238 chore: better "from" version default value population
  release/utils/flags-config.ts
Labels: :dart: canary, :label: chore

#9241 chore: manually run prepack
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: chore
