Repository warp-drive-data/warp-drive, pull requests merged in 2024-08, with the labels that each got.

#9520 [cleanup 4.6] Remove deprecated Ember.Error usage
  packages/-ember-data/tests/unit/adapter-errors-test.js
  packages/adapter/addon/error.js
  packages/model/addon/-private/model.js
  packages/model/index.js
  packages/store/index.js
Labels: :label: cleanup, backport-old-release

#9521 fix: Doc for query.ts
  packages/rest/src/-private/builders/query.ts
Labels: :dart: canary, :label: doc

#9522 [4.12 LTS] Fix CI
  .github/actions/setup/action.yml
  .github/workflows/asset-size-check.yml
  .github/workflows/deprecations-check.yml
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/model/package.json
  packages/private-build-infra/package.json
  packages/request-utils/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/docs/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: :label: chore, backport-lts

#9510 Backport #9511 to lts-4-12: Add @ember/string v4 to peerDependencies
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/adapter-encapsulation/package.json
  tests/blueprints/package.json
  tests/debug-encapsulation/package.json
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/graph/package.json
  tests/json-api-encapsulation/package.json
  tests/json-api/package.json
  tests/main/package.json
  tests/model-encapsulation/package.json
  tests/performance/package.json
  tests/request/package.json
  tests/serializer-encapsulation/package.json
Labels: :label: bug, backport-lts-prev

#9524 feat: persisted DataWorker and ImageWorker
  packages/experiments/README.md
  packages/experiments/src/data-worker/README.md
  packages/experiments/src/data-worker/cache-handler.ts
  packages/experiments/src/data-worker/worker.ts
  packages/experiments/src/document-storage/index.ts
  packages/experiments/src/image-worker.ts
  packages/experiments/src/image-worker/README.md
  packages/experiments/src/image-worker/fetch.ts
  packages/experiments/src/image-worker/types.ts
  packages/experiments/src/image-worker/worker.ts
  tests/warp-drive__experiments/.mock-cache/2102ca68/GET-0-users/1/res.body.br
  tests/warp-drive__experiments/.mock-cache/2102ca68/GET-0-users/1/res.meta.json
  tests/warp-drive__experiments/.mock-cache/9314a7d0/GET-0-users/1/res.body.br
  tests/warp-drive__experiments/.mock-cache/9314a7d0/GET-0-users/1/res.meta.json
  tests/warp-drive__experiments/tests/integration/data-worker/persisted-worker.ts
  tests/warp-drive__experiments/tests/integration/data-worker/serialization-test.ts
Labels: :dart: canary, :label: feat

#9519 Allow `ember-inflector` v5 as peerDependency & latest `ember-inflector` v4 version
  packages/request-utils/package.json
Labels: :dart: canary, :label: chore

#9530 feat: <:idle> state for Requests
  packages/build-config/src/-private/utils/get-env.ts
  packages/build-config/src/babel-macros.ts
  packages/build-config/src/env.ts
  packages/ember/src/-private/request.gts
  packages/holodeck/server/index.js
  pnpm-lock.yaml
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/9ef82bd7/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b6142c48/GET-3-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/f2060975/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/f2060975/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__ember/tests/integration/get-request-state-test.gts
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
  tests/warp-drive__ember/tests/integration/request-component-subscription-test.gts
  tests/warp-drive__ember/tests/integration/request-component-test.gts
  tests/warp-drive__ember/tests/test-helper.ts
Labels: :dart: canary, :label: feat, :label: bug
