Repository warp-drive-data/warp-drive, pull requests merged in 2024-03, with the labels that each got.

#9243 fix: keep core-type peer-deps
  packages/adapter/package.json
  packages/debug/package.json
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: bug

#9244 feat: improves consumer-facing store types
  packages/-ember-data/addon/store.ts
  packages/core-types/src/identifier.ts
  packages/core-types/src/record.ts
  packages/core-types/src/spec/raw.ts
  packages/core-types/src/symbols.ts
  packages/legacy-compat/src/legacy-network-handler/fetch-manager.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot-record-array.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/hooks.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model-methods.ts
  packages/model/src/-private/promise-belongs-to.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/schema-record/src/-base-fields.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/caches/cache-utils.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/legacy-model-support/record-reference.ts
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/utils/coerce-id.ts
  packages/store/src/-types/q/ds-model.ts
  packages/store/src/-types/q/record-instance.ts
  packages/store/src/-types/q/schema-service.ts
  packages/store/src/-types/q/store.ts
  tests/builders/app/services/store.ts
  tests/docs/fixtures/expected.js
  tests/ember-data__adapter/app/services/store.ts
  tests/ember-data__graph/app/services/store.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/setup.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/polymorphism/implicit-keys-test.ts
  tests/ember-data__serializer/app/services/store.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/identifiers/lid-reflection-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/recommended-json-api/app/services/store.ts
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/legacy/mode-test.ts
Labels: :dart: canary, :label: feat, typescript

#9246 normalization in json-api serializer preserves lid #7956
  packages/serializer/src/json-api.js
  tests/main/tests/integration/serializers/json-api-serializer-test.js
Labels: code-review, :label: feat

#9245 feat: add consumer types for Model APIs
  docs-generator/yui-docs-preprocessor.js
  packages/core-types/src/symbols.ts
  packages/model/package.json
  packages/model/rollup.config.mjs
  packages/model/src/-private.ts
  packages/model/src/-private/attr.js
  packages/model/src/-private/attr.ts
  packages/model/src/-private/attr.type-test.ts
  packages/model/src/-private/belongs-to.js
  packages/model/src/-private/belongs-to.ts
  packages/model/src/-private/belongs-to.type-test.ts
  packages/model/src/-private/has-many.js
  packages/model/src/-private/has-many.ts
  packages/model/src/-private/has-many.type-test.ts
  packages/model/src/-private/hooks.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model-for-mixin.ts
  packages/model/src/-private/model-methods.ts
  packages/model/src/-private/model.d.ts
  packages/model/src/-private/model.js
  packages/model/src/-private/model.type-test.ts
  packages/model/src/-private/notify-changes.ts
  packages/model/src/-private/promise-belongs-to.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/model/src/-private/schema-provider.ts
  packages/model/src/-private/util.ts
  packages/model/src/index.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/order-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/polymorphism/implicit-keys-test.ts
  tests/ember-data__graph/tests/integration/graph/unload-test.ts
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/integration/identifiers/lid-reflection-test.ts
  tests/main/tests/integration/record-data/record-data-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts
Labels: :dart: canary, :label: feat, typescript

#9248 feat: publish types as module defs
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: feat

#9249 chore: handle declare statements in module rewriting
  packages/graph/src/-private.ts
  packages/graph/src/-private/index.ts
  packages/model/src/-private/many-array.ts
  packages/store/src/-private.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/record-arrays/native-proxy-type-fix.ts
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: feat, typescript

#9250 feat: fix types for legacy decorator syntax
  packages/model/src/-private/belongs-to.ts
  packages/model/src/-private/has-many.ts
  packages/model/src/-private/model.type-test.ts
Labels: :dart: canary, :label: feat, typescript

#9251 fix: notify during replace if existing localState never previously calculated
  packages/graph/src/-private/operations/replace-related-records.ts
  tests/main/tests/integration/references/has-many-test.js
Labels: :dart: canary, :label: bug

#9252 fix: update line when removing declare statements
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: bug, typescript

#9256 feat: improve alpha types support
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/many-array.ts
  packages/model/src/-private/model-methods.ts
  packages/model/src/-private/promise-belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: feat, typescript

#9257 fix: use npm pack instead of pnpm pack to respect .npmignore rules
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: bug

#9258 fix: remove unused turbo key
  turbo.json
Labels: :dart: canary, :label: chore

#9254 Update IS_MAYBE_MIRAGE function to check for Mirage in development mode
  packages/request/src/fetch.ts
Labels: :dart: canary, :label: bug

#9259 Update setting-up-the-project.md
  contributing/setting-up-the-project.md
Labels: :dart: canary, :label: chore

#9240 feat: implement managed array for schemaRecord
  packages/core-types/src/cache.ts
  packages/schema-record/rollup.config.mjs
  packages/schema-record/src/managed-array.ts
  packages/schema-record/src/record.ts
  packages/schema-record/src/schema.ts
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/reactivity/array-test.ts
  tests/warp-drive__schema-record/tests/reads/array-test.ts
  tests/warp-drive__schema-record/tests/writes/array-test.ts
Labels: :dart: canary, :label: feat

#9263 fix: set localState to latest identifier in belongsTo when merging identifiers
  packages/graph/src/-private/operations/merge-identifier.ts
Labels: :dart: canary, :dart: lts, :label: bug, :dart: lts-prev

#9264 fix: set localState to latest identifier in belongsTo when merging identifiers (#9263)
  packages/graph/src/-private/graph/operations/merge-identifier.ts
Labels: :label: bug, backport-lts, backport-lts-prev

#9265 feat: Improve config handling for polyfillUUID
  README.md
  packages/adapter/addon-main.js
  packages/core-types/addon-main.cjs
  packages/graph/addon-main.cjs
  packages/graph/addon-main.js
  packages/json-api/addon-main.js
  packages/legacy-compat/addon-main.js
  packages/model/addon-main.js
  packages/private-build-infra/src/addon-build-config-for-data-package.js
  packages/request/addon-main.js
  packages/schema-record/addon-main.js
  packages/serializer/addon-main.js
  packages/store/addon-main.js
  packages/tracking/addon-main.cjs
Labels: :dart: canary, :label: bug

#9275 doc: don't mention unexisting ESA auth handler
  packages/request/README.md
Labels: :dart: canary, :label: doc

#9280 chore: handle dynamic imports with relative paths
  release/core/publish/steps/generate-tarballs.ts
Labels: :dart: canary, :label: chore

#9215 Docs: Add guide for incremental adoption
  guides/cookbook/incremental-adoption-guide.md
  guides/cookbook/index.md
  guides/index.md
  pnpm-lock.yaml
  tests/example-json-api/.eslintrc.cjs
  tests/example-json-api/README.md
  tests/example-json-api/app/adapters/application.js
  tests/example-json-api/app/app.ts
  tests/example-json-api/app/components/.gitkeep
  tests/example-json-api/app/components/book-list.hbs
  tests/example-json-api/app/components/book-list.ts
  tests/example-json-api/app/components/book-search.hbs
  tests/example-json-api/app/components/book-search.ts
  tests/example-json-api/app/components/infinite-books.hbs
  tests/example-json-api/app/components/infinite-books.ts
  tests/example-json-api/app/components/legacy-infinite-books.hbs
  tests/example-json-api/app/components/legacy-infinite-books.ts
  tests/example-json-api/app/components/page-link.hbs
  tests/example-json-api/app/config/environment.d.ts
  tests/example-json-api/app/helpers/.gitkeep
  tests/example-json-api/app/helpers/add.ts
  tests/example-json-api/app/helpers/and.ts
  tests/example-json-api/app/helpers/eq.ts
  tests/example-json-api/app/helpers/gt.ts
  tests/example-json-api/app/helpers/lt.ts
  tests/example-json-api/app/helpers/mod.ts
  tests/example-json-api/app/helpers/neq.ts
  tests/example-json-api/app/helpers/not.ts
  tests/example-json-api/app/helpers/or.ts
  tests/example-json-api/app/helpers/sub.ts
  tests/example-json-api/app/index.html
  tests/example-json-api/app/models/.gitkeep
  tests/example-json-api/app/models/author.ts
  tests/example-json-api/app/models/book.ts
  tests/example-json-api/app/models/genre.ts
  tests/example-json-api/app/resolver.ts
  tests/example-json-api/app/router.ts
  tests/example-json-api/app/routes/.gitkeep
  tests/example-json-api/app/routes/application.ts
  tests/example-json-api/app/services/request-manager.ts
  tests/example-json-api/app/services/store.js
  tests/example-json-api/app/styles/app.css
  tests/example-json-api/app/templates/.gitkeep
  tests/example-json-api/app/templates/application.hbs
  tests/example-json-api/app/utils/pagination-links.ts
  tests/example-json-api/config/environment.js
  tests/example-json-api/config/optional-features.json
  tests/example-json-api/config/targets.js
  tests/example-json-api/ember-cli-build.js
  tests/example-json-api/package.json
  tests/example-json-api/server/index.js
  tests/example-json-api/server/mocks/MOCK_DATA.json
  tests/example-json-api/server/mocks/book.js
  tests/example-json-api/testem.js
  tests/example-json-api/tests/.gitkeep
  tests/example-json-api/tests/index.html
  tests/example-json-api/tests/test-helper.js
  tests/example-json-api/tsconfig.json
  tests/recommended-json-api/app/services/store.ts
  tests/recommended-json-api/app/templates/application.hbs
Labels: :dart: canary, :label: doc

#9287 chore: bump deps for example-api app
  pnpm-lock.yaml
  tests/example-json-api/package.json
Labels: :dart: canary, :label: chore

#9289 chore: bump timeout for floating dep check in CI
  .github/workflows/compat-tests.yml
Labels: :dart: canary, :label: chore

#9291 chore: remove unused scripts
  ._eslintrc.js
  .github/workflows/partner-tests.yml
  contributing/linking-to-applications.md
  package.json
  scripts/-tarball-info.js
  scripts/packages-for-commit.js
  scripts/test-external-partner-project.js
Labels: :dart: canary, :label: chore

#9063 docs: add requests guide
  guides/requests/examples/1-auth.md
  guides/requests/index.md
  guides/requests/overview/0-intro.md
  guides/requests/overview/1-request-management.md
  guides/terminology.md
Labels: :dart: canary, :label: doc

#9304 feat: upates to 4.12 request package to support @warp-drive/ember
  packages/request/src/-private/context.ts
  packages/request/src/-private/future.ts
  packages/request/src/-private/manager.ts
  packages/request/src/-private/promise-cache.ts
  packages/request/src/-private/types.ts
  packages/request/src/-private/utils.ts
  packages/request/src/fetch.ts
  packages/request/src/index.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/request/tests/integration/graceful-dev-errors-test.ts
Labels: :label: feat, backport-lts

#9307 fix: mirage does not support anything
  packages/request/src/fetch.ts
Labels: :dart: canary, :label: bug

#9298 docs(request): remove duplicate line in readme
  packages/request/README.md
Labels: :dart: canary, :label: doc

#9299 doc: use store for save-record docs
  packages/active-record/src/-private/builders/save-record.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/rest/src/-private/builders/save-record.ts
Labels: :dart: canary, :label: doc

#9303 infra: setup mirror and types publishing
  packages/debug/ember-data-logo-dark.svg
  packages/debug/ember-data-logo-light.svg
  packages/graph/ember-data-logo-dark.svg
  packages/graph/ember-data-logo-light.svg
  packages/model/ember-data-logo-dark.svg
  packages/model/ember-data-logo-light.svg
  packages/private-build-infra/ember-data-logo-dark.svg
  packages/private-build-infra/ember-data-logo-light.svg
  packages/tracking/ember-data-logo-dark.svg
  packages/tracking/ember-data-logo-light.svg
  release/core/publish/index.ts
  release/core/publish/steps/generate-mirror-tarballs.ts
  release/core/publish/steps/generate-strategy.ts
  release/core/publish/steps/generate-tarballs.ts
  release/core/publish/steps/generate-types-tarballs.ts
  release/core/publish/steps/print-strategy.ts
  release/core/publish/steps/publish-packages.ts
  release/strategy.json
  release/utils/cmd.ts
  release/utils/package.ts
Labels: :dart: canary, :label: chore
