Repository warp-drive-data/warp-drive, pull requests merged in 2024-04, with the labels that each got.

#9316 Notify on length when notifying that many-array has changed
  packages/model/addon/-private/many-array.ts
Labels: :label: bug, backport-old-release

#9318 fix: be more specific in files in case .npmignore is ignored
  packages/-ember-data/package.json
Labels: :dart: canary, :label: bug

#9317 feat: ensure data utils work well with legacy relationship proxies
  packages/diagnostic/src/-define.ts
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/internals/run.ts
  packages/ember/src/-private/promise-state.ts
  packages/model/src/-private/promise-belongs-to.ts
  packages/model/src/-private/promise-many-array.ts
  tests/warp-drive__ember/tests/integration/get-promise-state-test.gts
Labels: :dart: canary, :label: feat, :dart: lts-prev

#9314 feat: improve lifetime handling of ad-hoc createRecord requests
  packages/core-types/src/request.ts
  packages/request-utils/src/index.ts
  packages/store/src/-private/cache-handler.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
Labels: :dart: canary, :label: feat, :dart: lts-prev

#9329 chore: update compat chart in README
  README.md
Labels: :dart: canary, :label: doc

#9328 chore: update READMEs with status and dist tag info
  README.md
  packages/-ember-data/README.md
  packages/active-record/README.md
  packages/adapter/README.md
  packages/core-types/README.md
  packages/debug/README.md
  packages/diagnostic/README.md
  packages/ember/README.md
  packages/graph/README.md
  packages/holodeck/README.md
  packages/json-api/README.md
  packages/legacy-compat/README.md
  packages/model/README.md
  packages/request-utils/README.md
  packages/request/README.md
  packages/rest/README.md
  packages/schema-record/README.md
  packages/schema-record/package.json
  packages/schema/README.md
  packages/serializer/README.md
  packages/store/README.md
  packages/tracking/README.md
  release/strategy.json
Labels: :dart: canary, :label: doc

#9330 chore: ensure latest tag is canary/beta tag for early stage packages
  release/core/promote/index.ts
  release/core/publish/steps/publish-packages.ts
Labels: :dart: canary, :label: chore

#9332 docs: add typescript guide
  guides/index.md
  guides/typescript/0-installation.md
  guides/typescript/1-configuration.md
  guides/typescript/2-why-brands.md
  guides/typescript/3-typing-models.md
  guides/typescript/index.md
Labels: :dart: canary, :label: doc, typescript

#9300 doc: remove reference to unexisting ESA auth handler
  guides/requests/index.md
Labels: :dart: canary, :label: doc

#9319 Add @ember-data/legacy-compat/builders
  packages/legacy-compat/.eslintrc.cjs
  packages/legacy-compat/package.json
  packages/legacy-compat/rollup.config.mjs
  packages/legacy-compat/src/builders.ts
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/find-record.ts
  packages/legacy-compat/src/builders/query.ts
  packages/legacy-compat/src/builders/save-record.ts
  packages/legacy-compat/src/builders/utils.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/store/src/-private.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/index.ts
  tests/docs/fixtures/expected.js
  tests/main/package.json
  tests/main/tests/integration/adapter/rest-adapter/-ajax-mocks.js
  tests/main/tests/integration/legacy-compat/find-all-test.ts
  tests/main/tests/integration/legacy-compat/find-record-test.ts
  tests/main/tests/integration/legacy-compat/query-test.ts
  tests/main/tests/integration/legacy-compat/save-record-test.ts
Labels: :dart: canary, :label: feat

#9277 feat: implement managed object for schemaRecord
  packages/schema-record/src/managed-object.ts
  packages/schema-record/src/record.ts
  packages/schema-record/src/schema.ts
  packages/store/src/-types/q/schema-service.ts
  tests/warp-drive__schema-record/tests/reads/object-test.ts
  tests/warp-drive__schema-record/tests/writes/object-test.ts
Labels: :dart: canary, :label: feat

#9352 feat: make setKeyInfoForResource public
  packages/store/src/-private.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-types/q/identifier.ts
  packages/store/src/index.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: feat

#9353 feat: utilies for migrating to stricter type and id usage
  packages/legacy-compat/package.json
  packages/legacy-compat/rollup.config.mjs
  packages/legacy-compat/src/utils.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/unit/legacy-compat/formatted-id-test.js
  tests/main/tests/unit/legacy-compat/formatted-type-test.js
  tests/main/tests/unit/legacy-compat/is-equiv-id-test.js
  tests/main/tests/unit/legacy-compat/is-equiv-type-test.js
Labels: :dart: canary, :label: feat

#9359 feat: type checked builders and inferred request types from builders
  guides/typescript/3-typing-models.md
  guides/typescript/4-typing-requests.md
  guides/typescript/index.md
  package.json
  packages/active-record/src/-private/builders/find-record.ts
  packages/active-record/src/-private/builders/query.ts
  packages/active-record/src/-private/builders/save-record.ts
  packages/core-types/src/record.ts
  packages/core-types/src/record.type-test.ts
  packages/core-types/src/request.ts
  packages/core-types/src/symbols.ts
  packages/ember/src/-private/request.gts
  packages/json-api/package.json
  packages/json-api/src/-private/builders/find-record.ts
  packages/json-api/src/-private/builders/find-record.type-test.ts
  packages/json-api/src/-private/builders/query.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/find-record.ts
  packages/legacy-compat/src/builders/query.ts
  packages/legacy-compat/src/builders/save-record.ts
  packages/rest/src/-private/builders/find-record.ts
  packages/rest/src/-private/builders/query.ts
  packages/rest/src/-private/builders/save-record.ts
  packages/schema-record/src/record.ts
  packages/store/src/-private/cache-handler.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/example-json-api/app/routes/application.ts
  tests/main/tests/integration/legacy-compat/query-test.ts
  tests/main/tests/integration/legacy-compat/save-record-test.ts
Labels: :dart: canary, :label: feat, typescript

#9363 feat: <Request /> autoRefresh
  packages/ember/README.md
  packages/ember/src/-private/await.gts
  packages/ember/src/-private/request.gts
  tests/warp-drive__ember/.mock-cache/733572b0/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/733572b0/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/73414455/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/73414455/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/8d3e369b/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/8d3e369b/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/b5fd3ed0/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/b5fd3ed0/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/b5fd3ed0/GET-1-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/b5fd3ed0/GET-1-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/ca4889d8/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/ca4889d8/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/ca4889d8/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/ca4889d8/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/ccc35947/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/ccc35947/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/ccc35947/GET-1-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/ccc35947/GET-1-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/db0753d2/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/db0753d2/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/eea0d109/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/eea0d109/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/f878a0f8/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/f878a0f8/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/.mock-cache/fbd61105/GET-0-users/2/res.body.br
  tests/warp-drive__ember/.mock-cache/fbd61105/GET-0-users/2/res.meta.json
  tests/warp-drive__ember/tests/integration/request-component-test.gts
Labels: :dart: canary, :label: feat

#9364 fix: restore old behavior in deprecation
  packages/graph/src/-private/operations/replace-related-record.ts
Labels: :dart: release, :dart: canary, :dart: lts, :label: bug

#9365 chore: remove unneeded infra tests
  .github/workflows/infra-tests.yml
  package.json
  packages/unpublished-test-infra/package.json
  packages/unpublished-test-infra/tests/dummy/app/app.js
  packages/unpublished-test-infra/tests/dummy/app/index.html
  packages/unpublished-test-infra/tests/dummy/app/resolver.js
  packages/unpublished-test-infra/tests/dummy/app/router.js
  packages/unpublished-test-infra/tests/dummy/app/routes/application/template.hbs
  packages/unpublished-test-infra/tests/dummy/app/styles/app.css
  packages/unpublished-test-infra/tests/dummy/app/templates/application.hbs
  packages/unpublished-test-infra/tests/dummy/config/environment.js
  packages/unpublished-test-infra/tests/dummy/config/optional-features.json
  packages/unpublished-test-infra/tests/dummy/config/targets.js
  packages/unpublished-test-infra/tests/dummy/public/.gitkeep
  packages/unpublished-test-infra/tests/index.html
  packages/unpublished-test-infra/tests/test-helper.js
  packages/unpublished-test-infra/tests/unit/.gitkeep
  packages/unpublished-test-infra/tests/unit/deprecations-stripped-test.js
Labels: :dart: canary, :label: chore

#9368 docs: Update ISSUE_TEMPLATE.md to follow latest pnpm
  .github/ISSUE_TEMPLATE.md
Labels: :dart: canary, :label: chore

#9369 fix: @warp-drive-ember, dont leak empty slot
  packages/ember/src/-private/await.gts
  packages/ember/src/-private/request.gts
Labels: :dart: canary, :label: bug

#9378 Update some docs to string ids
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: doc

#9379 fix: Automate uninstall process
  guides/typescript/0-installation.md
Labels: :dart: canary, :label: doc

#9386 Backport #9319 to lts-4-12: Add @ember-data/legacy-compat/builders
  packages/legacy-compat/package.json
  packages/legacy-compat/rollup.config.mjs
  packages/legacy-compat/src/builders.ts
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/find-record.ts
  packages/legacy-compat/src/builders/query.ts
  packages/legacy-compat/src/builders/save-record.ts
  packages/legacy-compat/src/builders/utils.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/request/src/index.ts
  packages/store/src/-private/index.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/graph/package.json
  tests/json-api/package.json
  tests/main/tests/integration/legacy-compat/find-all-test.ts
  tests/main/tests/integration/legacy-compat/find-record-test.ts
  tests/main/tests/integration/legacy-compat/query-test.ts
  tests/main/tests/integration/legacy-compat/save-record-test.ts
  tests/request/package.json
Labels: :label: feat, backport-lts
