Repository warp-drive-data/warp-drive, pull requests merged in 2024-06, with the labels that each got.

#9463 types: ManyArray => HasMany
  packages/model/src/index.ts
Labels: :dart: canary, :label: chore, typescript

#9464 feat: implement support for legacy hasMany and belongsTo relationship reads
  packages/model/src/-private/legacy-relationships-support.ts
  packages/schema-record/package.json
  packages/schema-record/src/record.ts
  packages/schema-record/tsconfig.json
  pnpm-lock.yaml
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/tests/legacy/reads/relationships-test.ts
Labels: :dart: canary, :label: feat

#9465 feat: implement edit & create cases for legacy relationships
  packages/schema-record/src/-private/compute.ts
  packages/schema-record/src/-private/managed-array.ts
  packages/schema-record/src/-private/managed-object.ts
  packages/schema-record/src/record.ts
  tests/warp-drive__schema-record/tests/-utils/reactive-context.ts
  tests/warp-drive__schema-record/tests/legacy/create/relationships-test.ts
  tests/warp-drive__schema-record/tests/legacy/edit/relationships-test.ts
  tests/warp-drive__schema-record/tests/legacy/reactivity/relationships-test.ts
Labels: :dart: canary, :label: feat

#9466 feat: make @id editable and reactive
  packages/schema-record/src/record.ts
  tests/warp-drive__schema-record/tests/legacy/create/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/legacy/reactivity/basic-fields-test.ts
Labels: :dart: canary, :label: feat

#9469 Fix exports for 'ember-data'
  packages/-ember-data/package.json
Labels: :dart: canary, :label: bug

#9473 npx: warp-drive retrofit types@canary 🪄
  packages/-warp-drive/package.json
  packages/-warp-drive/src/-private/shared/git.ts
  packages/-warp-drive/src/-private/shared/npm.ts
  packages/-warp-drive/src/-private/shared/parse-args.ts
  packages/-warp-drive/src/-private/shared/the-big-list.ts
  packages/-warp-drive/src/-private/shared/utils.ts
  packages/-warp-drive/src/-private/warp-drive/cmd.config.ts
  packages/-warp-drive/src/-private/warp-drive/commands/default-ts-config.js
  packages/-warp-drive/src/-private/warp-drive/commands/eject.ts
  packages/-warp-drive/src/-private/warp-drive/commands/retrofit.ts
  packages/-warp-drive/src/warp-drive.ts
  packages/-warp-drive/vite.config.mjs
  pnpm-lock.yaml
  release/strategy.json
Labels: :dart: canary, :label: feat

#9475 fix: dont install optional peers if not already present
  packages/-warp-drive/src/-private/warp-drive/commands/retrofit.ts
Labels: :dart: canary, :label: bug

#9474 Improve query types for legacy-compat/builders
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/find-record.ts
  packages/legacy-compat/src/builders/query.ts
  packages/store/src/types.ts
Labels: :dart: canary, :label: feat

#9476 chore: cleanup symbol usage
  guides/typescript/0-installation.md
  guides/typescript/2-why-brands.md
  guides/typescript/3-typing-models.md
  packages/core-types/src/record.ts
  packages/core-types/src/record.type-test.ts
  packages/json-api/src/-private/builders/find-record.type-test.ts
  packages/json-api/src/-private/builders/query.type-test.ts
  packages/model/src/-private/belongs-to.type-test.ts
  packages/model/src/-private/has-many.type-test.ts
  packages/model/src/-private/model.type-test.ts
  packages/model/src/-private/type-utils.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/store-service.type-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/setup.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/polymorphism/implicit-keys-test.ts
  tests/example-json-api/app/models/book.ts
  tests/fastboot/app/models/person.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  tests/main/tests/integration/identifiers/lid-reflection-test.ts
  tests/main/tests/integration/identifiers/polymorphic-scenarios-test.ts
  tests/main/tests/integration/legacy-compat/find-all-test.ts
  tests/main/tests/integration/legacy-compat/find-record-test.ts
  tests/main/tests/integration/legacy-compat/query-test.ts
  tests/main/tests/integration/legacy-compat/save-record-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test.ts
  tests/warp-drive__schema-record/tests/legacy/mode-test.ts
  tests/warp-drive__schema-record/tests/reads/array-test.ts
  tests/warp-drive__schema-record/tests/reads/object-test.ts
  tests/warp-drive__schema-record/tests/reads/schema-array-test.ts
  tests/warp-drive__schema-record/tests/reads/schema-object-test.ts
  tests/warp-drive__schema-record/tests/writes/array-test.ts
  tests/warp-drive__schema-record/tests/writes/object-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-array-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-object-test.ts
Labels: :dart: canary, :label: chore

#9477 fix: add deprecation and avoid breaking configs
  packages/-ember-data/addon-main.cjs
  packages/build-config/src/cjs-set-config.ts
  packages/build-config/src/index.ts
  packages/build-config/vite.config-cjs.mjs
Labels: :dart: canary, :label: chore

#9479 feat: support migration path for ember-inflector usage
  .npmrc
  packages/-ember-data/src/store.ts
  packages/build-config/src/deprecation-versions.ts
  packages/build-config/src/deprecations.ts
  packages/request-utils/package.json
  packages/request-utils/src/deprecation-support.ts
  packages/request-utils/vite.config.mjs
  pnpm-lock.yaml
  tests/builders/eslint.config.mjs
  tests/builders/package.json
  tests/builders/tests/test-helper.js
  tests/builders/tests/unit/inflection-deprecation-test.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: deprecation

#9472 fix: code snippet in json-api/request api docs
  packages/json-api/src/request.ts
Labels: :dart: canary, :label: doc

#9485 fix: update deprecation language for ember-inflector deprecation
  packages/build-config/src/deprecation-versions.ts
  packages/request-utils/src/deprecation-support.ts
Labels: :dart: beta, :dart: release, :dart: canary, :label: bug

#9486 chore: fixup dev deps
  packages/tracking/package.json
  pnpm-lock.yaml
Labels: :dart: canary, :label: chore

#9490 Add export point for direct export of blueprints
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/model/package.json
  packages/serializer/package.json
Labels: :dart: canary, :label: chore

#9491 Change import for blueprints inside of -ember-data
  packages/-ember-data/blueprints/adapter-test/index.js
  packages/-ember-data/blueprints/adapter/index.js
  packages/-ember-data/blueprints/model-test/index.js
  packages/-ember-data/blueprints/model/index.js
  packages/-ember-data/blueprints/serializer-test/index.js
  packages/-ember-data/blueprints/serializer/index.js
  packages/-ember-data/blueprints/transform-test/index.js
  packages/-ember-data/blueprints/transform/index.js
Labels: :dart: canary, :label: chore

#9492 fix: windows builds
  config/vite/config.js
  packages/build-config/src/-private/utils/features.ts
  packages/build-config/vite.config-cjs.mjs
  packages/build-config/vite.config.mjs
Labels: :dart: beta, :dart: release, :dart: canary, :label: bug

#9494 Use vite's built-in package.json loading to inline names and versions
  packages/-ember-data/addon-main.cjs
  packages/-ember-data/src/version.ts
  packages/core-types/addon-main.cjs
  packages/core-types/src/-private.ts
Labels: :dart: canary, :label: chore

#9495 fix: setup deprecation support as early as possible, restore inspector support
  packages/-ember-data/app/initializers/ember-data.js
  packages/-ember-data/src/store.ts
  packages/build-config/cjs-src/transforms/babel-plugin-transform-deprecations.js
  packages/build-config/cjs-src/transforms/babel-plugin-transform-features.js
  packages/build-config/cjs-src/transforms/babel-plugin-transform-logging.js
  packages/build-config/src/index.ts
  packages/debug/package.json
  packages/debug/src/data-adapter.ts
  packages/request-utils/src/deprecation-support.ts
  pnpm-lock.yaml
  tests/builders/tests/unit/inflection-deprecation-test.ts
  tests/embroider-basic-compat/package.json
  tests/fastboot/package.json
  tests/main/package.json
Labels: :dart: beta, :dart: release, :dart: canary, :label: bug

#9497 fix: dont trust ember-inflector
  packages/request-utils/src/deprecation-support.ts
Labels: :dart: beta, :dart: release, :dart: canary, :label: bug

#9499 feat: monorepo support for npx warp-drive
  packages/-warp-drive/package.json
  packages/-warp-drive/src/-private/shared/npm.ts
  packages/-warp-drive/src/-private/shared/repo.ts
  packages/-warp-drive/src/-private/shared/utils.ts
  packages/-warp-drive/src/-private/warp-drive/cmd.config.ts
  packages/-warp-drive/src/-private/warp-drive/commands/retrofit.ts
  pnpm-lock.yaml
Labels: :dart: canary, :label: feat

#9500 fix: attempt traversal to find project
  packages/-ember-data/addon-main.cjs
Labels: :dart: beta, :dart: release, :dart: canary, :label: bug
