Repository warp-drive-data/warp-drive, pull requests merged in 2024-11, with the labels that each got.

#9592 fix: add ember-source as explicit peer-dep for use of @ember/debug
  .github/workflows/main.yml
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/graph/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/store/src/-private/store-service.ts
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/main/package.json
Labels: :dart: canary, :label: bug

#9593 chore: cleanup glint impl
  package.json
  packages/ember/package.json
  pnpm-lock.yaml
  tests/main/package.json
  tests/main/tsconfig.json
  tests/warp-drive__ember/package.json
  tsconfig.json
Labels: :dart: canary, :label: chore

#9591 chore: fix ember 6 template registration
  pnpm-lock.yaml
  tests/main/eslint.config.mjs
  tests/main/package.json
  tests/main/tests/acceptance/relationships/has-many-test.js
  tests/main/tests/acceptance/relationships/tracking-record-state-test.js
  tests/main/tests/acceptance/tracking-create-record-test.js
  tests/main/tests/acceptance/tracking-model-id-test.js
  tests/main/tests/helpers/reactive-context.gts
  tests/main/tests/integration/model-errors-test.gts
Labels: :dart: canary, :label: chore

#9596 chore: Remove unused `--report-unused-disable-directives` flag
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/experiments/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  tests/blueprints/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: release, :label: chore

#9594 chore: fixup more ember6 template usage
  config/eslint/gts.js
  config/eslint/typescript.js
  pnpm-lock.yaml
  tests/main/tests/helpers/create-tracking-context.gjs
  tests/main/tests/integration/references/has-many-test.js
  tests/warp-drive__schema-record/ember-cli-build.js
  tests/warp-drive__schema-record/eslint.config.mjs
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/tests/-utils/reactive-context.gts
  tests/warp-drive__schema-record/tests/legacy/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/legacy/reactivity/relationships-test.ts
  tests/warp-drive__schema-record/tests/reactivity/array-test.ts
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reactivity/object-test.ts
  tests/warp-drive__schema-record/tests/reactivity/schema-array-test.ts
  tests/warp-drive__schema-record/tests/reactivity/schema-object-test.ts
  tests/warp-drive__schema-record/tsconfig.json
Labels: :dart: canary, :label: chore

#9590 docs: begin work on a more comprehensive manual
  README.md
  guides/community-resources.md
  guides/index.md
  guides/manual/0-index.md
  guides/manual/1-overview.md
  guides/manual/2-requests.md
  guides/manual/3-data.md
  guides/manual/4-caching.md
  guides/manual/5-presentation.md
  guides/manual/6-schemas.md
  logos/NCC-1701-a-blue.svg
  logos/NCC-1701-a-gold _100.svg
  logos/NCC-1701-a-gold.svg
  logos/NCC-1701-a-gold_base-64.txt
  logos/NCC-1701-a.svg
  logos/ember-data-logo-dark.svg
  logos/ember-data-logo-light.svg
  logos/github-header.svg
  logos/social1.png
  logos/social2.png
  logos/warp-drive-logo-dark.svg
  logos/warp-drive-logo-gold.svg
Labels: :dart: canary, :label: doc

#9595 Add vite test-app
  .github/workflows/compat-tests.yml
  package.json
  pnpm-lock.yaml
  tests/vite-basic-compat/.editorconfig
  tests/vite-basic-compat/.ember-cli
  tests/vite-basic-compat/.gitignore
  tests/vite-basic-compat/.template-lintrc.js
  tests/vite-basic-compat/README.md
  tests/vite-basic-compat/app/adapters/application.ts
  tests/vite-basic-compat/app/app.ts
  tests/vite-basic-compat/app/components/.gitkeep
  tests/vite-basic-compat/app/config/environment.d.ts
  tests/vite-basic-compat/app/config/environment.js
  tests/vite-basic-compat/app/controllers/.gitkeep
  tests/vite-basic-compat/app/helpers/.gitkeep
  tests/vite-basic-compat/app/models/user.ts
  tests/vite-basic-compat/app/router.ts
  tests/vite-basic-compat/app/routes/.gitkeep
  tests/vite-basic-compat/app/styles/app.css
  tests/vite-basic-compat/app/templates/application.gts
  tests/vite-basic-compat/babel.config.cjs
  tests/vite-basic-compat/config/ember-cli-update.json
  tests/vite-basic-compat/config/environment.js
  tests/vite-basic-compat/config/optional-features.json
  tests/vite-basic-compat/config/targets.js
  tests/vite-basic-compat/ember-cli-build.js
  tests/vite-basic-compat/eslint.config.mjs
  tests/vite-basic-compat/index.html
  tests/vite-basic-compat/package.json
  tests/vite-basic-compat/public/robots.txt
  tests/vite-basic-compat/testem.js
  tests/vite-basic-compat/tests/acceptance/visit-test.js
  tests/vite-basic-compat/tests/helpers/index.ts
  tests/vite-basic-compat/tests/index.html
  tests/vite-basic-compat/tests/integration/.gitkeep
  tests/vite-basic-compat/tests/test-helper.ts
  tests/vite-basic-compat/tests/unit/.gitkeep
  tests/vite-basic-compat/tsconfig.json
  tests/vite-basic-compat/types/ember-data/types/registries/model.d.ts
  tests/vite-basic-compat/types/index.d.ts
  tests/vite-basic-compat/vite.config.mjs
Labels: :dart: canary, :label: chore

#9608 fix: restore individual flag customizations for deprecation stripping
  packages/build-config/src/index.ts
  tests/embroider-basic-compat/ember-cli-build.js
  tests/embroider-basic-compat/tests/acceptance/visit-test.js
Labels: :dart: canary, :label: bug
