Repository warp-drive-data/warp-drive, pull requests merged in 2025-02, with the labels that each got.

#9656 fix: get perf test harness working again
  .github/workflows/perf-check.yml
  config/package.json
  config/rollup/external.js
  config/utils/glob.js
  config/vite/fix-module-output-plugin.js
  config/vite/keep-assets.js
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/build-config/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/ember/package.json
  packages/experiments/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/performance/ember-cli-build.js
  tests/performance/package.json
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/native-types/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: perf, ci-perf

#9653 doc: Add blog post on transformations and derivations
  guides/community-resources.md
Labels: :dart: canary, :label: doc

#9585 chore: stub out linksMode work
  packages/core-types/src/request.ts
  packages/core-types/src/schema/fields.ts
  packages/ember/src/-private/request.gts
  packages/graph/src/-private/-edge-definition.ts
  packages/graph/src/-private/debug/assert-polymorphic-type.ts
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/validate-document-fields.ts
  packages/model/src/-private/belongs-to.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/migration-support.ts
  packages/schema-record/src/record.ts
  packages/store/src/-private/cache-handler/handler.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-private/store-service.type-test.ts
  tests/main/tests/integration/relationships/links-mode/belongs-to-test.ts
  tests/warp-drive__schema-record/tests/legacy/reactivity/relationships-test.ts
  tests/warp-drive__schema-record/tests/legacy/reads/relationships-test.ts
  tests/warp-drive__schema-record/tests/reads/belongs-to-test.ts
  tests/warp-drive__schema-record/tsconfig.json
Labels: :dart: canary, :label: feat

#9647 chore: bump range for @ember/test-helpers to include 5.1
  package.json
  packages/-ember-data/package.json
  packages/diagnostic/README.md
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/unpublished-test-infra/package.json
  patches/@ember__test-helpers@5.1.0.patch
  pnpm-lock.yaml
  tests/blueprints/package.json
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/native-types/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: bug

#9654 perf: dont notify for attrs on insertions or committed changes that are referentially equal
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  packages/core-types/src/identifier.ts
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/notify-changes.ts
  packages/store/src/-private.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/debug/utils.ts
  packages/store/src/-private/managers/cache-capabilities-manager.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-types/q/cache-capabilities-manager.ts
  scripts/perf-tracking/browser-flags.mjs
  tests/main/ember-cli-build.js
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
Labels: :dart: canary, :label: perf, ci-perf

#9652 fix: treat uncommitted mutations as local operations when receiving remote updates
  packages/graph/src/-private/operations/replace-related-records.ts
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/test-helper.ts
Labels: :dart: canary, :label: bug

#9655 perf: reduce notifications on relationship remote state updates
  packages/core-types/src/spec/document.ts
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/json-api/src/-private/cache.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
  tests/main/tests/integration/relationships/not-overly-reactive-test.ts
  tests/main/tests/integration/relationships/rollback-test.ts
Labels: :dart: canary, :label: perf, ci-perf

#9673 perf: reduce notifications during first-load
  packages/build-config/src/debugging.ts
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/edges/collection.ts
  packages/graph/src/-private/edges/resource.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/add-to-related-records.ts
  packages/graph/src/-private/operations/merge-identifier.ts
  packages/graph/src/-private/operations/remove-from-related-records.ts
  packages/graph/src/-private/operations/replace-related-record.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/graph/src/-private/operations/update-relationship.ts
  packages/model/src/-private/references/has-many.ts
  packages/store/src/-private/managers/notification-manager.ts
  tests/docs/fixtures/expected.js
  tests/main/tests/integration/references/autotracking-test.js
  tests/main/tests/integration/relationships/rollback-test.ts
  tests/performance/app/routes/relationship-materialization-complex.js
  tests/performance/ember-cli-build.js
Labels: :dart: canary, :label: perf, ci-perf

#9677 chore: fixup deprecation-removed test variants
  packages/store/src/-private/managers/notification-manager.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
  tests/main/tests/unit/model/relationships/has-many-test.js
Labels: :dart: canary, :label: chore

#9680 chore: improve handling of rollback scenarios
  packages/graph/src/-private/-diff.ts
  tests/main/ember-cli-build.js
  tests/main/tests/integration/application-test.js
  tests/main/tests/integration/relationships/has-many-sort-order-test.js
  tests/main/tests/integration/relationships/rollback-test.ts
Labels: :dart: canary, :label: bug, ci-perf

#9681 Add perf info for re-materialization
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  packages/graph/src/-private/-diff.ts
  tests/performance/app/routes/relationship-materialization-complex.js
Labels: :dart: canary, :label: perf, ci-perf

#9683 feat: runtime logging activation
  packages/build-config/cjs-src/transforms/babel-plugin-transform-logging.js
  packages/build-config/src/-private/utils/logging.ts
  packages/build-config/src/babel-macros.ts
  packages/build-config/src/index.ts
  packages/build-config/src/runtime.ts
  packages/build-config/tsconfig.json
  packages/build-config/vite.config.mjs
  packages/request/src/index.ts
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: feat

#9685 Fix bug where race condition causes errors during Request refresh
  packages/ember/src/-private/request.gts
  tests/ember-data__graph/tests/test-helper.ts
  tests/warp-drive__ember/.mock-cache/73ae9a7c/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/73ae9a7c/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/73ae9a7c/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/73ae9a7c/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/tests/integration/request-component-test.gts
  tests/warp-drive__ember/tests/test-helper.ts
  tests/warp-drive__experiments/tests/test-helper.ts
Labels: :dart: canary, :label: bug

#9687 feat: add patchRecord util to JSON:API
  packages/json-api/src/-private/builders/save-record.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: feat

#9686 feat: immutable records should show only remote state, make builder types more useful
  packages/core-types/src/request.ts
  packages/json-api/src/-private/builders/save-record.ts
  packages/json-api/src/-private/cache.ts
  packages/schema-record/src/-private/compute.ts
  packages/schema-record/src/record.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/store-service.ts
  tests/warp-drive__schema-record/tests/edit-workflow-test.ts
Labels: :dart: canary, :label: feat, typescript

#9689 Fix: support all known http methods
  packages/core-types/src/request.ts
  packages/request/src/-private/debug.ts
Labels: :dart: canary, :label: bug

#9690 chore: fixup SchemaRecord readme
  packages/schema-record/README.md
Labels: :dart: canary, :label: doc

#9676 Feat: hasMany linksMode
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/validate-document-fields.ts
  packages/model/src/-private.ts
  packages/model/src/-private/legacy-relationships-support.ts
  packages/model/src/-private/model.type-test.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/references/has-many.ts
  packages/model/src/-private/type-utils.ts
  packages/model/src/index.ts
  packages/schema-record/src/-private/compute.ts
  packages/schema-record/src/-private/managed-array.ts
  packages/schema-record/src/-private/many-array-manager.ts
  packages/schema-record/src/record.ts
  packages/store/src/-private.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  packages/store/src/-private/record-arrays/many-array.ts
  tests/warp-drive__schema-record/tests/reads/has-many-test.ts
Labels: :dart: canary, :label: feat

#9692 fix: make serialize utils smarter
  packages/json-api/src/-private/serialize.ts
Labels: :dart: canary, :label: bug

#9693 chore: add env vars to turbo config
  turbo.json
Labels: :dart: canary, :label: chore

#9694 docs: small cleanup for SchemaRecord intro
  guides/manual/1-overview.md
  guides/manual/3-data.md
  packages/schema-record/README.md
Labels: :dart: canary, :label: doc

#9697 chore: [BREAKING to prior alpha/betas] prepare SchemaRecord for stable, lockdown exports
  packages/experiments/src/data-worker/README.md
  packages/schema-record/README.md
  packages/schema-record/package.json
  packages/schema-record/src/-private.ts
  packages/schema-record/src/-private/fields/compute.ts
  packages/schema-record/src/-private/fields/managed-array.ts
  packages/schema-record/src/-private/fields/managed-object.ts
  packages/schema-record/src/-private/fields/many-array-manager.ts
  packages/schema-record/src/-private/hooks.ts
  packages/schema-record/src/-private/record.ts
  packages/schema-record/src/-private/schema.ts
  packages/schema-record/src/-private/symbols.ts
  packages/schema-record/src/index.ts
  packages/schema-record/vite.config.mjs
  packages/store/src/-private/store-service.ts
  tests/main/tests/integration/cache-handler/request-dedupe-test.ts
  tests/warp-drive__ember/app/services/store.ts
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
  tests/warp-drive__ember/tests/integration/request-component-subscription-test.gts
  tests/warp-drive__ember/tests/integration/request-component-test.gts
  tests/warp-drive__experiments/app/services/store.ts
  tests/warp-drive__experiments/tests/integration/data-worker/basic-test.ts
  tests/warp-drive__experiments/tests/integration/data-worker/basic-worker.ts
  tests/warp-drive__experiments/tests/integration/data-worker/persisted-worker.ts
  tests/warp-drive__experiments/tests/integration/data-worker/serialization-test.ts
  tests/warp-drive__experiments/tests/integration/data-worker/user-schema.ts
  tests/warp-drive__schema-record/app/services/store.ts
  tests/warp-drive__schema-record/tests/edit-workflow-test.ts
  tests/warp-drive__schema-record/tests/legacy/mode-test.ts
  tests/warp-drive__schema-record/tests/legacy/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/legacy/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/array-test.ts
  tests/warp-drive__schema-record/tests/reactivity/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reactivity/derivation-test.ts
  tests/warp-drive__schema-record/tests/reactivity/object-test.ts
  tests/warp-drive__schema-record/tests/reactivity/resource-test.ts
  tests/warp-drive__schema-record/tests/reactivity/schema-array-test.ts
  tests/warp-drive__schema-record/tests/reactivity/schema-object-test.ts
  tests/warp-drive__schema-record/tests/reads/alias-test.ts
  tests/warp-drive__schema-record/tests/reads/array-test.ts
  tests/warp-drive__schema-record/tests/reads/basic-fields-test.ts
  tests/warp-drive__schema-record/tests/reads/belongs-to-test.ts
  tests/warp-drive__schema-record/tests/reads/derivation-test.ts
  tests/warp-drive__schema-record/tests/reads/has-many-test.ts
  tests/warp-drive__schema-record/tests/reads/object-test.ts
  tests/warp-drive__schema-record/tests/reads/resource-test.ts
  tests/warp-drive__schema-record/tests/reads/schema-array-test.ts
  tests/warp-drive__schema-record/tests/reads/schema-object-test.ts
  tests/warp-drive__schema-record/tests/writes/array-test.ts
  tests/warp-drive__schema-record/tests/writes/object-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-array-test.ts
  tests/warp-drive__schema-record/tests/writes/schema-object-test.ts
Labels: :dart: canary, :label: chore

#9698 fix: Don't notify changes for attributes not registered with the schema
  packages/json-api/src/-private/cache.ts
  packages/model/src/-private/model.ts
  tests/main/eslint.config.mjs
  tests/main/tests/acceptance/relationships/tracking-record-state-test.js
  tests/main/tests/acceptance/tracking-create-record-test.js
  tests/main/tests/helpers/create-tracking-context.gjs
  tests/main/tests/integration/cache/json-api-cache-2-test.ts
  tests/main/tests/unit/model-test.js
  tests/main/tests/unit/store/push-test.js
Labels: :dart: canary, :label: bug

#9703 Add perf test for replacing state with new state that matches local state
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  tests/performance/app/router.js
  tests/performance/app/routes/update-with-same-state.js
  tests/performance/app/templates/application.hbs
Labels: :dart: canary, :label: perf, ci-perf
