Repository warp-drive-data/warp-drive, pull requests merged in 2025-07, with the labels that each got.

#10045 feat: Traits!
  tests/warp-drive__schema-record/tests/schema/traits-test.ts
  warp-drive-packages/build-config/src/canary-features.ts
  warp-drive-packages/core/src/reactive/-private/schema.ts
  warp-drive-packages/core/src/store/-types/q/schema-service.ts
  warp-drive-packages/core/src/types/schema/fields.ts
Labels: :dart: canary, :label: feat

#10048 feat: sourceKey for api fields
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-write-test.ts
  warp-drive-packages/core/src/reactive/-private/fields/compute.ts
  warp-drive-packages/core/src/reactive/-private/fields/get-field-key.ts
  warp-drive-packages/core/src/reactive/-private/fields/many-array-manager.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/core/src/reactive/-private/schema.ts
  warp-drive-packages/core/src/store/-private/record-arrays/many-array.ts
  warp-drive-packages/core/src/store/-types/q/schema-service.ts
  warp-drive-packages/core/src/types/schema/fields.ts
  warp-drive-packages/json-api/src/-private/cache.ts
  warp-drive-packages/legacy/src/model/migration-support.ts
Labels: :dart: canary, :label: feat

#10046 Fix some docs inaccuracies
  guides/1-configuration/2-setup/1-universal.md
  guides/1-configuration/2-setup/2-ember.md
  guides/1-configuration/4-legacy-package-setup/2-setup/1-universal.md
  guides/1-configuration/4-legacy-package-setup/2-setup/2-ember.md
Labels: :dart: canary, :label: doc

#10052 feat: streamlined kind/mode logic
  tests/warp-drive__schema-record/ember-cli-build.js
  tests/warp-drive__schema-record/tests/test-helper.js
  warp-drive-packages/core/src/reactive/-private/default-mode.ts
  warp-drive-packages/core/src/reactive/-private/fields/compute.ts
  warp-drive-packages/core/src/reactive/-private/fields/managed-array.ts
  warp-drive-packages/core/src/reactive/-private/fields/managed-object.ts
  warp-drive-packages/core/src/reactive/-private/hooks.ts
  warp-drive-packages/core/src/reactive/-private/kind/alias-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/array-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/attribute-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/belongs-to-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/collection-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/derived-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/generic-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/has-many-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/hash-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/identity-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/local-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/object-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/resource-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/schema-array-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/schema-object-field.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/core/src/types/schema/fields.ts
Labels: :dart: canary, :label: feat

#10051 feat: allow hashFn usage for types
  tests/warp-drive__schema-record/tests/polaris/schema-array-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-array-field-write-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-read-test.ts
  warp-drive-packages/core/src/reactive/-private/default-mode.ts
  warp-drive-packages/core/src/reactive/-private/fields/managed-array.ts
  warp-drive-packages/core/src/reactive/-private/fields/managed-object.ts
  warp-drive-packages/core/src/reactive/-private/hooks.ts
  warp-drive-packages/core/src/reactive/-private/kind/array-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/has-many-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/schema-array-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/schema-object-field.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/core/src/reactive/-private/schema.ts
  warp-drive-packages/core/src/store/-types/q/schema-service.ts
  warp-drive-packages/core/src/types/schema/fields.ts
  warp-drive-packages/legacy/src/model/migration-support.ts
Labels: :dart: canary, :label: feat

#10032 fast-push exploration
  scripts/benchmark-push.js
  warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
Labels: :dart: canary, :label: perf, ci-perf

#10055 feat: polarismode createRecord, createRecord with lid
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/records/create-record-test.js
  tests/main/tests/integration/records/save-test.js
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/main/tests/unit/model-test.js
  tests/warp-drive__schema-record/tests/polaris/basic-fields-create-test.ts
  warp-drive-packages/core/src/graph/-private/-utils.ts
  warp-drive-packages/core/src/graph/-private/graph.ts
  warp-drive-packages/core/src/graph/-private/operations/replace-related-record.ts
  warp-drive-packages/core/src/graph/-private/operations/replace-related-records.ts
  warp-drive-packages/core/src/reactive/-private/hooks.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/core/src/store/-private/caches/cache-utils.ts
  warp-drive-packages/core/src/store/-private/caches/identifier-cache.ts
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/core/src/store/deprecated/store.ts
  warp-drive-packages/core/src/types/-private.ts
  warp-drive-packages/legacy/src/compat/builders/save-record.ts
  warp-drive-packages/legacy/src/model/-private/attr.ts
  warp-drive-packages/legacy/src/model/-private/hooks.ts
  warp-drive-packages/legacy/src/model/-private/legacy-relationships-support.ts
  warp-drive-packages/legacy/src/model/-private/model-methods.ts
  warp-drive-packages/legacy/src/model/-private/model.ts
  warp-drive-packages/legacy/src/model/-private/record-state.ts
  warp-drive-packages/legacy/src/store.ts
Labels: :dart: canary, :label: feat, :label: perf, ci-perf

#10062 feat: cleanup Snapshot and make it defer to modelFor for schema iteration
  tests/main/tests/integration/emergent-behavior/recovery/belongs-to-test.ts
  tests/main/tests/integration/emergent-behavior/recovery/has-many-test.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts
Labels: :dart: canary, :label: feat

#10063 test: add tests for deep-change mutations and rollback
  tests/warp-drive__schema-record/tests/polaris/kind/schema-object/deep-changes-test.ts
  warp-drive-packages/core/src/reactive/-private/fields/managed-array.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
Labels: :dart: canary, :label: test

#10066 feat: smoother checkout process
  tests/builders/tests/integration/create-record-test.ts
  tests/builders/tests/integration/delete-record-test.ts
  tests/builders/tests/integration/update-record-test.ts
  tests/warp-drive__schema-record/tests/edit-workflow-test.ts
  warp-drive-packages/core/src/reactive.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/core/src/reactive/-private/symbols.ts
  warp-drive-packages/core/src/types/-private.ts
  warp-drive-packages/core/src/types/cache.ts
  warp-drive-packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: feat

#10068 chore: improve isDocumentIdentifier and isRecordIdentifier checks
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  warp-drive-packages/core/src/store/-private/caches/identifier-cache.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: chore

#10070 types: rename IdentifierCache => CacheKeyManager
  ROADMAP.md
  contributing/key-concepts.md
  guides/3-caching.md
  packages/debug/src/data-adapter.ts
  tests/docs/fixtures/expected.js
  tests/ember-data__adapter/tests/integration/coalescing-test.js
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/duplicate-data-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/order-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/unload-test.ts
  tests/ember-data__json-api/tests/integration/cache/cache.patch-test.ts
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/serialize-test.ts
  tests/main/tests/integration/adapter/rest-adapter/find-record-test.js
  tests/main/tests/integration/cache-handler/meta-package-setup-test.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/cache/cache-capabilities-manager-test.ts
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  tests/main/tests/integration/identifiers/cache-test.ts
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
  tests/main/tests/integration/records/load-test.js
  tests/main/tests/integration/records/polymorphic-find-record-test.ts
  tests/main/tests/integration/records/rematerialize-test.js
  tests/main/tests/integration/references/record-test.js
  tests/main/tests/integration/relationships/rollback-test.ts
  tests/main/tests/integration/request-state-service-test.ts
  tests/main/tests/integration/snapshot-test.js
  tests/main/tests/unit/model/relationships/has-many-test.js
  tests/main/tests/unit/store/adapter-interop-test.js
  tests/main/tests/unit/store/push-test.js
  warp-drive-packages/core/src/graph/-private/operations/update-relationship.ts
  warp-drive-packages/core/src/index.ts
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/core/src/store/-private/cache-handler/handler.ts
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/managers/cache-capabilities-manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-private/record-arrays/legacy-many-array.ts
  warp-drive-packages/core/src/store/-private/record-arrays/resource-array.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/core/src/store/-private/utils/construct-resource.ts
  warp-drive-packages/core/src/store/-types/q/cache-capabilities-manager.ts
  warp-drive-packages/core/src/store/deprecated/store.ts
  warp-drive-packages/core/src/types/cache/aliases.ts
  warp-drive-packages/experiments/src/data-worker/cache-handler.ts
  warp-drive-packages/experiments/src/persisted-cache/fetch.ts
  warp-drive-packages/json-api/src/-private/cache.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts
  warp-drive-packages/legacy/src/model/-private/references/belongs-to.ts
  warp-drive-packages/legacy/src/model/-private/references/has-many.ts
  warp-drive-packages/legacy/src/store.ts
Labels: :dart: canary, :label: chore, typescript

#10071 chore: complete rename of StableRecordIdentifier => ResourceKey
  @types/ember-data-qunit-asserts/index.d.ts
  ROADMAP.md
  contributing/key-concepts.md
  guides/misc/links-mode.md
  packages/-ember-data/src/store.ts
  packages/unpublished-test-infra/src/test-support/asserts/assert-notification.ts
  packages/unpublished-test-infra/src/test-support/asserts/index.ts
  tests/builders/app/services/store.ts
  tests/docs/fixtures/expected.js
  tests/ember-data__adapter/app/services/store.ts
  tests/ember-data__graph/app/services/store.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/helpers.ts
  tests/ember-data__graph/tests/integration/graph/edge-removal/setup.ts
  tests/ember-data__graph/tests/integration/graph/unload-test.ts
  tests/ember-data__json-api/tests/integration/cache/cache.patch-test.ts
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/serialize-test.ts
  tests/ember-data__json-api/tests/utils/schema.ts
  tests/ember-data__model/tests/utils/schema.ts
  tests/ember-data__serializer/app/services/store.ts
  tests/fastboot/app/services/store.ts
  tests/main/tests/helpers/accessors.ts
  tests/main/tests/integration/cache-handler/request-dedupe-test.ts
  tests/main/tests/integration/relationships/rollback-test.ts
  tests/main/tests/utils/schema.ts
  tests/performance/app/services/store.ts
  tests/warp-drive__ember/app/services/store.ts
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
  tests/warp-drive__ember/tests/integration/request-component-subscription-test.gts
  tests/warp-drive__experiments/app/services/store.ts
  tests/warp-drive__experiments/tests/integration/data-worker/basic-test.ts
  tests/warp-drive__experiments/tests/integration/data-worker/serialization-test.ts
  tests/warp-drive__schema-record/tests/legacy/basic-fields-reactivity-test.ts
  tests/warp-drive__schema-record/tests/legacy/basic-fields-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/alias-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/basic-fields-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/basic-fields-reactivity-test.ts
  warp-drive-packages/core/src/graph/-private/-edge-definition.ts
  warp-drive-packages/core/src/graph/-private/graph.ts
  warp-drive-packages/core/src/graph/-private/operations/replace-related-record.ts
  warp-drive-packages/core/src/graph/-private/operations/replace-related-records.ts
  warp-drive-packages/core/src/reactive/-private/default-mode.ts
  warp-drive-packages/core/src/reactive/-private/hooks.ts
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/default-cache-policy.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
  warp-drive-packages/core/src/types.ts
  warp-drive-packages/core/src/types/cache.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/experiments/src/persisted-cache/cache.ts
  warp-drive-packages/json-api/src/-private/cache.ts
  warp-drive-packages/legacy/src/compat/builders/save-record.ts
  warp-drive-packages/legacy/src/model/-private/model.ts
Labels: :dart: canary, :label: cleanup, typescript

#10072 types: rename StableNewRecordIdentifier => NewResourceKey
  warp-drive-packages/core/src/store/deprecated/-private.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/legacy/src/store/-private.ts
Labels: :dart: canary, :label: cleanup, typescript

#10073 types: rename StableExistingRecordIdentifier => PersistedResourceKey
  tests/ember-data__json-api/tests/integration/cache/cache.patch-test.ts
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/core/src/types/cache/operations.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/core/src/types/spec/document.ts
  warp-drive-packages/experiments/src/persisted-cache/cache.ts
  warp-drive-packages/json-api/src/-private/cache.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/fetch-manager.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/identifier-has-id.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/legacy-data-fetch.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/legacy-network-handler.ts
  warp-drive-packages/legacy/src/model/-private/references/belongs-to.ts
  warp-drive-packages/utilities/src/-private/active-record/save-record.ts
  warp-drive-packages/utilities/src/-private/json-api/save-record.ts
  warp-drive-packages/utilities/src/-private/rest/save-record.ts
Labels: :dart: canary, :label: cleanup, typescript

#10074 chore: deleted PersistedCache experiment
  ROADMAP.md
  warp-drive-packages/experiments/README.md
  warp-drive-packages/experiments/package.json
  warp-drive-packages/experiments/src/persisted-cache.ts
  warp-drive-packages/experiments/src/persisted-cache/README.md
  warp-drive-packages/experiments/src/persisted-cache/cache.ts
  warp-drive-packages/experiments/src/persisted-cache/db.ts
  warp-drive-packages/experiments/src/persisted-cache/fetch.ts
  warp-drive-packages/experiments/vite.config.mjs
Labels: :dart: canary, :label: cleanup

#10076 types: eliminate RecordIdentifier type variants
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  tests/warp-drive__experiments/tests/integration/document-storage/basic-test.ts
  tests/warp-drive__experiments/tests/integration/document-storage/sync-test.ts
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/core/src/store/-types/q/schema-service.ts
  warp-drive-packages/core/src/types/cache/aliases.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/experiments/src/data-worker/cache-handler.ts
  warp-drive-packages/experiments/src/document-storage/index.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts
  warp-drive-packages/legacy/src/model/-private/schema-provider.ts
Labels: :dart: canary, :label: cleanup

#10077 types: remove StableIdentifier and Identifier types as base
  tests/main/tests/integration/identifiers/configuration-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/core/src/store/-private/managers/cache-capabilities-manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-private/record-arrays/legacy-many-array.ts
  warp-drive-packages/core/src/store/-private/record-arrays/resource-array.ts
  warp-drive-packages/core/src/store/-private/utils/construct-resource.ts
  warp-drive-packages/core/src/store/-types/q/identifier.ts
  warp-drive-packages/core/src/store/deprecated/-private.ts
  warp-drive-packages/core/src/types/cache/operations.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/json-api/src/-private/cache.ts
  warp-drive-packages/legacy/src/model/-private/legacy-relationships-support.ts
Labels: :dart: canary, :label: chore

#10078 types: rename StableDocumentIdentifier => RequestKey
  @types/ember-data-qunit-asserts/index.d.ts
  ROADMAP.md
  packages/unpublished-test-infra/src/test-support/asserts/assert-notification.ts
  packages/unpublished-test-infra/src/test-support/asserts/index.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  tests/main/tests/integration/identifiers/scenarios-test.ts
  warp-drive-packages/core/src/reactive/-private/document.ts
  warp-drive-packages/core/src/request/-private/context.ts
  warp-drive-packages/core/src/request/-private/manager.ts
  warp-drive-packages/core/src/request/-private/types.ts
  warp-drive-packages/core/src/store/-private/cache-handler/handler.ts
  warp-drive-packages/core/src/store/-private/cache-handler/types.ts
  warp-drive-packages/core/src/store/-private/cache-handler/utils.ts
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/default-cache-policy.ts
  warp-drive-packages/core/src/store/-private/managers/cache-capabilities-manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/expensive-subscription.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-state.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
  warp-drive-packages/core/src/store/-private/record-arrays/resource-array.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/core/src/store/-types/q/cache-capabilities-manager.ts
  warp-drive-packages/core/src/store/-types/q/identifier.ts
  warp-drive-packages/core/src/types/cache.ts
  warp-drive-packages/core/src/types/cache/change.ts
  warp-drive-packages/core/src/types/cache/operations.ts
  warp-drive-packages/core/src/types/identifier.ts
  warp-drive-packages/ember/src/index.ts
  warp-drive-packages/experiments/src/data-worker/cache-handler.ts
  warp-drive-packages/experiments/src/data-worker/utils.ts
  warp-drive-packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: chore

#10080 chore: more renaming identifier => key|cacheKey
  warp-drive-packages/core/src/graph/-private/-diff.ts
  warp-drive-packages/core/src/graph/-private/-edge-definition.ts
  warp-drive-packages/core/src/graph/-private/-utils.ts
  warp-drive-packages/core/src/graph/-private/graph.ts
  warp-drive-packages/core/src/store/-private/default-cache-policy.ts
Labels: :dart: canary, :label: chore, typescript

#10081 chore: more renaming identifier => key|cacheKey
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-types/q/schema-service.ts
  warp-drive-packages/core/src/types/cache.ts
Labels: :dart: canary, :label: chore

#10083 Fix deprecation handling for blueprint/tutorial
  packages/-ember-data/app/services/store.js
  packages/-ember-data/app/transforms/boolean.js
  packages/-ember-data/app/transforms/date.js
  packages/-ember-data/app/transforms/number.js
  packages/-ember-data/app/transforms/string.js
  packages/store/src/index.ts
Labels: :dart: canary, :label: chore

#10091 fix: ensure setting an array field to null is possible
  tests/warp-drive__schema-record/tests/polaris/array-field-write-test.ts
  warp-drive-packages/core/src/reactive/-private/kind/array-field.ts
  warp-drive-packages/core/src/reactive/-private/kind/schema-array-field.ts
Labels: :dart: canary, :label: bug
