Repository warp-drive-data/warp-drive, pull requests merged in 2025-04, with the labels that each got.

#9894 fix: make warnMessageNoModelForKey (and similar) even more safe in prod
  packages/serializer/src/json-api.js
Labels: :dart: canary, :label: bug

#9895 backport fix: make warnMessageNoModelForKey (and similar) even more safe in prod
  packages/serializer/src/json-api.js
Labels: :dart: canary, :label: bug

#9881 fix: graph isReordered should return false when localState is null
  packages/graph/src/-private/graph.ts
  tests/main/tests/integration/relationships/rollback-test.ts
Labels: :dart: canary, :label: bug

#9896 feat: whoa debugging
  packages/build-config/src/canary-features.ts
  packages/json-api/package.json
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/validator/1.1/7.1_top-level-document-members.ts
  packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
  packages/json-api/src/-private/validator/1.1/links.ts
  packages/json-api/src/-private/validator/index.ts
  packages/json-api/src/-private/validator/utils.ts
  packages/model/src/-private/schema-provider.ts
  packages/model/src/migration-support.ts
  packages/schema-record/src/-private/schema.ts
  packages/store/src/-types/q/schema-service.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/meta-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/validation-errors-test.ts
  tests/ember-data__json-api/tests/utils/schema.ts
  tests/ember-data__model/tests/utils/schema.ts
  tests/main/tests/integration/cache-handler/lifetimes-test.ts
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/utils/schema.ts
Labels: :dart: canary, :label: feat

#9911 Add a URL to the deprecate Store extends EmberObject
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: doc

#9919 chore: silence deprecation, attempt to fix CI
  packages/build-config/src/index.ts
  packages/ember/package.json
  packages/request/package.json
  pnpm-lock.yaml
  tests/ember-data__adapter/package.json
Labels: :dart: canary, :label: chore

#9884 feat: cache patch operations for relationships and documents
  internal-tooling/src/sync-license.ts
  packages/build-config/cjs-src/addon-shim.js
  packages/build-config/package.json
  packages/build-config/src/debugging.ts
  packages/core-types/src/cache.ts
  packages/core-types/src/cache/mutations.ts
  packages/core-types/src/cache/operations.ts
  packages/core-types/src/cache/relationship.ts
  packages/core-types/src/graph.ts
  packages/core-types/src/runtime.ts
  packages/core-types/src/spec/json-api-raw.ts
  packages/diagnostic/src/-types/report.ts
  packages/diagnostic/src/internals/run.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/diagnostic/src/styles/dom-reporter.css
  packages/experiments/package.json
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/-utils.ts
  packages/graph/src/-private/graph.ts
  packages/graph/src/-private/operations/add-to-related-records.ts
  packages/graph/src/-private/operations/remove-from-related-records.ts
  packages/graph/src/-private/operations/replace-related-records.ts
  packages/graph/src/-private/operations/update-relationship.ts
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/validator/index.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/schema-record/src/-private/fields/many-array-manager.ts
  packages/store/src/-private.ts
  packages/store/src/-private/cache-handler/handler.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/document.ts
  packages/store/src/-private/managers/record-array-manager.ts
  packages/store/src/-private/record-arrays/many-array.ts
  packages/store/src/-private/store-service.ts
  pnpm-lock.yaml
  release/core/publish/steps/generate-tarballs.ts
  release/utils/package.ts
  tests/docs/fixtures/expected.js
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/integration/graph/edge-test.ts
  tests/ember-data__graph/tests/integration/graph/order-preservation-test.ts
  tests/ember-data__json-api/package.json
  tests/ember-data__json-api/tests/integration/cache/cache.patch-test.ts
  tests/ember-data__json-api/tests/integration/serialize-test.ts
  tests/ember-data__json-api/tests/test-helper.js
  tests/ember-data__json-api/tsconfig.json
  tests/main/ember-cli-build.js
Labels: :dart: canary, :label: feat

#9938 docs: add note about handlebars usage to @warp-drive/ember
  packages/ember/README.md
  packages/ember/src/index.ts
Labels: :dart: canary, :label: doc

#9947 fix: dont notify during population if the array is a collection
  packages/store/src/-private/managers/record-array-manager.ts
Labels: :dart: release, :dart: canary, :dart: lts, :label: bug

#9960 fix: enable trait registration and fix ManyArray mutation on polaris mode records
  packages/schema-record/src/-private/fields/many-array-manager.ts
  packages/schema-record/src/-private/schema.ts
Labels: :dart: canary, :label: bug

#9961 fix: generate relative links for table (resolves #9942)
  README.md
  internal-tooling/src/tasks/sync-readme-tables.ts
Labels: :dart: canary, :label: doc

#9962 fix: enable mutation to work as expected
  packages/schema-record/src/-private/fields/compute.ts
  packages/schema-record/src/-private/fields/many-array-manager.ts
  tests/warp-drive__schema-record/tests/polaris/has-many-field-mutate-test.ts
Labels: :dart: canary, :label: bug

#9964 chore: refactor PromiseState and RequestState to prep for @warp-drive/core
  packages/ember/src/-private/await.gts
  packages/ember/src/-private/promise-state.ts
  packages/ember/src/-private/request-state.ts
  packages/ember/src/-private/request.gts
  packages/ember/src/index.ts
  packages/model/src/-private/record-state.ts
  packages/store/src/-private.ts
  packages/store/src/-private/network/request-cache.ts
  packages/store/src/-private/new-core-tmp/promise-state.ts
  packages/store/src/-private/new-core-tmp/request-state.ts
  tests/warp-drive__ember/tests/integration/get-request-state-test.gts
Labels: :dart: canary, :label: chore

#9966 perf: fix teardown perf
  packages/model/src/-private/belongs-to.ts
  packages/model/src/-private/model.ts
  tests/main/tests/integration/records/create-record-test.js
Labels: :dart: canary, :label: perf, ci-perf

#9968 feat: unlock universal 🌌
  packages/ember/src/install.ts
  packages/ember/vite.config.mjs
  packages/graph/package.json
  packages/graph/src/-private/-utils.ts
  packages/request-utils/package.json
  packages/schema-record/package.json
  packages/store/package.json
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/new-core-tmp/reactivity/configure.ts
  packages/store/vite.config.mjs
  packages/tracking/eslint.config.mjs
  packages/tracking/src/index.ts
  packages/tracking/vite.config.mjs
Labels: :dart: canary, :label: feat
