Repository warp-drive-data/warp-drive, pull requests merged in 2025-08, with the labels that each got.

#10097 Fix `[Checkout]` typing in documentation
  packages/schema-record/README.md
  packages/schema-record/src/index.ts
  warp-drive-packages/core/src/reactive.ts
Labels: :dart: canary, :label: doc

#10095 feat: expose createRequestSubscription, fix: always use request store
  tests/warp-drive__ember/.mock-cache/1140e10a/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/1140e10a/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/1140e10a/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/1140e10a/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/688cdb8f/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/688cdb8f/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/688cdb8f/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/688cdb8f/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/76ce6b39/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/76ce6b39/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/76ce6b39/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/76ce6b39/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/cf99d76e/GET-0-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/cf99d76e/GET-0-users/1/res.meta.json
  tests/warp-drive__ember/.mock-cache/cf99d76e/GET-1-users/1/res.body.br
  tests/warp-drive__ember/.mock-cache/cf99d76e/GET-1-users/1/res.meta.json
  tests/warp-drive__ember/tests/integration/request-component-flexibility-test.gts
  warp-drive-packages/core/src/reactive/-private/schema.ts
  warp-drive-packages/core/src/request/-private/future.ts
  warp-drive-packages/core/src/request/-private/manager.ts
  warp-drive-packages/core/src/request/-private/types.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-state.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
  warp-drive-packages/core/src/types/request.ts
  warp-drive-packages/ember/src/-private/request.gts
  warp-drive-packages/ember/src/index.ts
  warp-drive-packages/ember/vite.config.mjs
Labels: :dart: canary, :label: feat

#10104 chore: scaffold @warp-drive/react
  docs-viewer/typedoc.config.mjs
  pnpm-lock.yaml
  tsconfig.json
  warp-drive-packages/react/CHANGELOG.md
  warp-drive-packages/react/LICENSE.md
  warp-drive-packages/react/README.md
  warp-drive-packages/react/addon-main.cjs
  warp-drive-packages/react/babel.config.mjs
  warp-drive-packages/react/eslint.config.mjs
  warp-drive-packages/react/logos/NCC-1701-a-blue.svg
  warp-drive-packages/react/logos/NCC-1701-a-gold.svg
  warp-drive-packages/react/logos/NCC-1701-a-gold_100.svg
  warp-drive-packages/react/logos/NCC-1701-a-gold_base-64.txt
  warp-drive-packages/react/logos/NCC-1701-a.svg
  warp-drive-packages/react/logos/README.md
  warp-drive-packages/react/logos/docs-badge.svg
  warp-drive-packages/react/logos/ember-data-logo-dark.svg
  warp-drive-packages/react/logos/ember-data-logo-light.svg
  warp-drive-packages/react/logos/github-header.svg
  warp-drive-packages/react/logos/social1.png
  warp-drive-packages/react/logos/social2.png
  warp-drive-packages/react/logos/warp-drive-logo-dark.svg
  warp-drive-packages/react/logos/warp-drive-logo-gold.svg
  warp-drive-packages/react/package.json
  warp-drive-packages/react/src/.gitkeep
  warp-drive-packages/react/src/index.ts
  warp-drive-packages/react/src/install.ts
  warp-drive-packages/react/tsconfig.json
  warp-drive-packages/react/typedoc.config.mjs
  warp-drive-packages/react/vite.config.mjs
Labels: :dart: canary, :label: chore

#10106 chore: scaffold @warp-drive/svelte
  .gitignore
  config/eslint/ignore.js
  pnpm-lock.yaml
  tsconfig.json
  warp-drive-packages/svelte/LICENSE.md
  warp-drive-packages/svelte/README.md
  warp-drive-packages/svelte/eslint.config.mjs
  warp-drive-packages/svelte/logos/NCC-1701-a-blue.svg
  warp-drive-packages/svelte/logos/NCC-1701-a-gold.svg
  warp-drive-packages/svelte/logos/NCC-1701-a-gold_100.svg
  warp-drive-packages/svelte/logos/NCC-1701-a-gold_base-64.txt
  warp-drive-packages/svelte/logos/NCC-1701-a.svg
  warp-drive-packages/svelte/logos/README.md
  warp-drive-packages/svelte/logos/docs-badge.svg
  warp-drive-packages/svelte/logos/ember-data-logo-dark.svg
  warp-drive-packages/svelte/logos/ember-data-logo-light.svg
  warp-drive-packages/svelte/logos/github-header.svg
  warp-drive-packages/svelte/logos/social1.png
  warp-drive-packages/svelte/logos/social2.png
  warp-drive-packages/svelte/logos/warp-drive-logo-dark.svg
  warp-drive-packages/svelte/logos/warp-drive-logo-gold.svg
  warp-drive-packages/svelte/package.json
  warp-drive-packages/svelte/src/app.html
  warp-drive-packages/svelte/src/lib/index.ts
  warp-drive-packages/svelte/src/lib/install.svelte.ts
  warp-drive-packages/svelte/tsconfig.json
  warp-drive-packages/svelte/typedoc.config.mjs
  warp-drive-packages/svelte/vite.config.mjs
  warp-drive-packages/vue/package.json
Labels: :dart: canary, :label: chore

#10109 chore: add react test-app
  packages/diagnostic/server/bun/fetch.js
  pnpm-lock.yaml
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/example-json-api/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__react/README.md
  tests/warp-drive__react/babel.config.mjs
  tests/warp-drive__react/diagnostic.js
  tests/warp-drive__react/eslint.config.mjs
  tests/warp-drive__react/index.html
  tests/warp-drive__react/package.json
  tests/warp-drive__react/tests/.gitkeep
  tests/warp-drive__react/tests/integration/request-component-test.tsx
  tests/warp-drive__react/tests/test-helper.ts
  tests/warp-drive__react/tsconfig.json
  tests/warp-drive__react/vite.config.mjs
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema/package.json
Labels: :dart: canary, :label: chore

#10111 feat: react signals
  config/vite/config.js
  pnpm-lock.yaml
  tests/warp-drive__react/babel.config.mjs
  tests/warp-drive__react/package.json
  tests/warp-drive__react/tests/integration/reactive-context-test.tsx
  tests/warp-drive__react/tests/test-helper.ts
  tests/warp-drive__react/tsconfig.json
  tests/warp-drive__react/vite.config.mjs
  warp-drive-packages/build-config/src/debugging.ts
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/reactivity/internal.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/reactivity/signal.ts
  warp-drive-packages/react/babel.config.mjs
  warp-drive-packages/react/package.json
  warp-drive-packages/react/src/-private/reactive-context.tsx
  warp-drive-packages/react/src/index.ts
  warp-drive-packages/react/src/install.ts
  warp-drive-packages/react/tsconfig.json
  warp-drive-packages/react/vite.config.mjs
Labels: :dart: canary, :label: feat

#10113 chore: cleanup types
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
  warp-drive-packages/ember/src/-private/request.gts
  warp-drive-packages/react/src/-private/reactive-context.tsx
Labels: :dart: canary, :label: chore

#10115 feat: framework agnostic test helpers
  packages/diagnostic/babel.config.mjs
  packages/diagnostic/package.json
  packages/diagnostic/src/ember.ts
  packages/diagnostic/src/helpers/-dom/-get-description.ts
  packages/diagnostic/src/helpers/-dom/-get-element.ts
  packages/diagnostic/src/helpers/-dom/-get-elements.ts
  packages/diagnostic/src/helpers/-dom/-get-window-or-element.ts
  packages/diagnostic/src/helpers/-dom/-guard-for-maxlength.ts
  packages/diagnostic/src/helpers/-dom/-helper-context.ts
  packages/diagnostic/src/helpers/-dom/-is-focusable.ts
  packages/diagnostic/src/helpers/-dom/-is-form-control.ts
  packages/diagnostic/src/helpers/-dom/-is-select-element.ts
  packages/diagnostic/src/helpers/-dom/-target.ts
  packages/diagnostic/src/helpers/-dom/-to-array.ts
  packages/diagnostic/src/helpers/-dom/-utils.ts
  packages/diagnostic/src/helpers/-dom/blur.ts
  packages/diagnostic/src/helpers/-dom/click.ts
  packages/diagnostic/src/helpers/-dom/double-click.ts
  packages/diagnostic/src/helpers/-dom/fill-in.ts
  packages/diagnostic/src/helpers/-dom/find-all.ts
  packages/diagnostic/src/helpers/-dom/find.ts
  packages/diagnostic/src/helpers/-dom/fire-event.ts
  packages/diagnostic/src/helpers/-dom/focus.ts
  packages/diagnostic/src/helpers/-dom/helper-hooks.ts
  packages/diagnostic/src/helpers/-dom/scroll-to.ts
  packages/diagnostic/src/helpers/-dom/select.ts
  packages/diagnostic/src/helpers/-dom/tab.ts
  packages/diagnostic/src/helpers/-dom/tap.ts
  packages/diagnostic/src/helpers/-dom/trigger-event.ts
  packages/diagnostic/src/helpers/-dom/trigger-key-event.ts
  packages/diagnostic/src/helpers/-dom/type-in.ts
  packages/diagnostic/src/helpers/-dom/wait-for.ts
  packages/diagnostic/src/helpers/-dom/wait-until.ts
  packages/diagnostic/src/helpers/install.ts
  packages/diagnostic/src/index.ts
  packages/diagnostic/src/react.tsx
  packages/diagnostic/vite.config.mjs
  pnpm-lock.yaml
  tests/warp-drive__ember/tests/integration/await-component-test.gts
  tests/warp-drive__ember/tests/integration/get-promise-state-test.gts
  tests/warp-drive__ember/tests/integration/get-request-state-test.gts
  tests/warp-drive__ember/tests/integration/request-component-flexibility-test.gts
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
  tests/warp-drive__ember/tests/integration/request-component-subscription-test.gts
  tests/warp-drive__ember/tests/integration/request-component-test.gts
  warp-drive-packages/core/src/request/-private/future.ts
Labels: :dart: canary, :label: chore

#10120 fix: add more context to non-cache field warnings
  warp-drive-packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
Labels: :dart: canary, :label: bug

#10118 chore: cleanup react signal config type compat
  warp-drive-packages/react/src/install.ts
Labels: :dart: canary, :label: chore

#10125 chore: dont use JS private fields
  warp-drive-packages/core/src/request/-private/context.ts
  warp-drive-packages/core/src/request/-private/manager.ts
  warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
Labels: :dart: canary, :label: chore

#10126 chore: remove accidental deps
  pnpm-lock.yaml
  tests/framework-ember/package.json
Labels: :dart: canary, :label: chore

#10129 chore: bump typescript to 5.9
  config/package.json
  docs-viewer/package.json
  internal-tooling/package.json
  package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  specs/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/framework-ember/package.json
  tests/main/package.json
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/native-types/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__react/package.json
  tests/warp-drive__schema-record/package.json
  warp-drive-packages/build-config/package.json
  warp-drive-packages/core/package.json
  warp-drive-packages/ember/package.json
  warp-drive-packages/experiments/package.json
  warp-drive-packages/json-api/package.json
  warp-drive-packages/legacy/package.json
  warp-drive-packages/react/package.json
  warp-drive-packages/svelte/package.json
  warp-drive-packages/tc39-proposal-signals/package.json
  warp-drive-packages/utilities/package.json
  warp-drive-packages/vue/package.json
Labels: :dart: canary, :label: chore

#10130 chore: bump pnpm version
  config/package.json
  package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/adapter/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/model/package.json
  packages/schema-record/package.json
  packages/schema/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/unpublished-test-infra/package.json
  specs/package.json
  tests/blueprints/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/framework-ember/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__react/package.json
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema/package.json
  warp-drive-packages/build-config/package.json
  warp-drive-packages/core/package.json
  warp-drive-packages/json-api/package.json
  warp-drive-packages/legacy/package.json
  warp-drive-packages/utilities/package.json
Labels: :dart: canary, :label: chore

#10127 feat: Diagnostic Timeline
  packages/diagnostic/src/-types.ts
  packages/diagnostic/src/-types/report.ts
  packages/diagnostic/src/helpers/-dom/-helper-context.ts
  packages/diagnostic/src/helpers/-dom/helper-hooks.ts
  packages/diagnostic/src/helpers/install.ts
  packages/diagnostic/src/internals/config.ts
  packages/diagnostic/src/internals/delegating-reporter.ts
  packages/diagnostic/src/internals/diagnostic.ts
  packages/diagnostic/src/internals/run.ts
  packages/diagnostic/src/reporters/dom.ts
  packages/diagnostic/src/styles/dom-reporter.css
  tests/builders/tests/test-helper.js
  tests/ember-data__adapter/tests/test-helper.js
  tests/ember-data__graph/tests/test-helper.ts
  tests/ember-data__json-api/tests/test-helper.js
  tests/ember-data__model/tests/test-helper.js
  tests/ember-data__request/tests/test-helper.ts
  tests/framework-ember/start.ts
  tests/warp-drive__experiments/tests/test-helper.ts
  tests/warp-drive__react/tests/test-helper.ts
Labels: :dart: canary, :label: feat

#10247 chore: bump vite/svelte/vue/vitepress
  config/package.json
  docs-viewer/package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  specs/package.json
  tests/performance/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__react/package.json
  warp-drive-packages/build-config/package.json
  warp-drive-packages/core/package.json
  warp-drive-packages/ember/package.json
  warp-drive-packages/experiments/package.json
  warp-drive-packages/json-api/package.json
  warp-drive-packages/legacy/package.json
  warp-drive-packages/react/package.json
  warp-drive-packages/svelte/package.json
  warp-drive-packages/utilities/package.json
  warp-drive-packages/vue/package.json
Labels: :label: dependencies, :dependabot:

#10272 chore: remove more private types from published output
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
  docs-viewer/tsconfig.json
  warp-drive-packages/core/src/reactive/-private/document.ts
  warp-drive-packages/core/src/request/-private/context.ts
  warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
  warp-drive-packages/core/src/store/-private/managers/notification-manager.ts
  warp-drive-packages/core/src/store/-private/managers/record-array-manager.ts
  warp-drive-packages/core/src/store/-private/network/request-cache.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-state.ts
  warp-drive-packages/core/src/store/-private/new-core-tmp/request-subscription.ts
  warp-drive-packages/legacy/src/compat/legacy-network-handler/snapshot.ts
  warp-drive-packages/legacy/src/model/-private/legacy-relationships-support.ts
  warp-drive-packages/legacy/src/model/-private/schema-provider.ts
Labels: :dart: canary, :label: chore

#10275 Add svelte test app
  pnpm-lock.yaml
  tests/framework-svelte/babel.config.mjs
  tests/framework-svelte/diagnostic.js
  tests/framework-svelte/eslint.config.mjs
  tests/framework-svelte/index.html
  tests/framework-svelte/package.json
  tests/framework-svelte/start.ts
  tests/framework-svelte/tests/request-component.spec-test.ts
  tests/framework-svelte/tsconfig.json
  tests/framework-svelte/vite.config.mjs
  warp-drive-packages/svelte/package.json
  warp-drive-packages/svelte/src/lib/install.svelte.ts
Labels: :dart: canary, :label: chore

#10279 chore: add support for LegacyNetworkHandler to holodeck
  packages/holodeck/package.json
  packages/holodeck/src/index.ts
  packages/holodeck/tsconfig.json
  pnpm-lock.yaml
Labels: :dart: canary, :label: chore

#10347 chore: tools reorg
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  release/strategy.json
  tests/smoke-tests/prepare.ts
  tools/internal-config/babel/fix-mjs.cjs
  tools/internal-config/eslint/browser.js
  tools/internal-config/eslint/diagnostic.js
  tools/internal-config/eslint/gts.js
  tools/internal-config/eslint/ignore.js
  tools/internal-config/eslint/imports.js
  tools/internal-config/eslint/isolation.js
  tools/internal-config/eslint/mocha.js
  tools/internal-config/eslint/node.js
  tools/internal-config/eslint/parser.js
  tools/internal-config/eslint/qunit.js
  tools/internal-config/eslint/typescript.js
  tools/internal-config/package.json
  tools/internal-config/rollup/external.js
  tools/internal-config/rollup/gjs.js
  tools/internal-config/utils/glob.js
  tools/internal-config/vite/compile-types-plugin.js
  tools/internal-config/vite/config.js
  tools/internal-config/vite/fix-module-output-plugin.js
  tools/internal-config/vite/keep-assets.js
  tools/internal-config/vite/move-types.js
Labels: :dart: canary, :label: chore

#10348 chore: move internal-tooling into tools
  README.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tools/internal-tooling/README.md
  tools/internal-tooling/package.json
  tools/internal-tooling/src/sync-all.ts
  tools/internal-tooling/src/sync-license.ts
  tools/internal-tooling/src/sync-logos.ts
  tools/internal-tooling/src/sync-readme-tables.ts
  tools/internal-tooling/src/sync-references.ts
  tools/internal-tooling/src/sync-scripts.ts
  tools/internal-tooling/src/tasks/-data/compatibility.ts
  tools/internal-tooling/src/tasks/-data/versions.ts
  tools/internal-tooling/src/tasks/-utils.ts
  tools/internal-tooling/src/tasks/sync-all.ts
  tools/internal-tooling/src/tasks/sync-license.ts
  tools/internal-tooling/src/tasks/sync-logos.ts
  tools/internal-tooling/src/tasks/sync-readme-tables.ts
  tools/internal-tooling/src/tasks/sync-references.ts
  tools/internal-tooling/src/tasks/sync-scripts.ts
  tools/internal-tooling/tsconfig.json
Labels: :dart: canary, :label: chore

#10351 chore: move release script into tools
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests/smoke-tests/prepare.ts
  tools/release/core/latest-for/index.ts
  tools/release/core/promote/index.ts
  tools/release/core/publish/index.ts
  tools/release/core/publish/steps/bump-versions.ts
  tools/release/core/publish/steps/confirm-strategy.ts
  tools/release/core/publish/steps/generate-mirror-tarballs.ts
  tools/release/core/publish/steps/generate-strategy.ts
  tools/release/core/publish/steps/generate-tarballs.ts
  tools/release/core/publish/steps/generate-types-tarballs.ts
  tools/release/core/publish/steps/print-strategy.ts
  tools/release/core/publish/steps/publish-packages.ts
  tools/release/core/release-notes/index.ts
  tools/release/core/release-notes/steps/confirm-changelogs.ts
  tools/release/core/release-notes/steps/get-changes.ts
  tools/release/core/release-notes/steps/submit-pr-to-branch.ts
  tools/release/core/release-notes/steps/update-changelogs.ts
  tools/release/core/utils/next-version.ts
  tools/release/guide/canary.md
  tools/release/help/-utils.ts
  tools/release/help/docs.ts
  tools/release/help/sections/about.ts
  tools/release/help/sections/manual.ts
  tools/release/index.ts
  tools/release/package.json
  tools/release/strategy.json
  tools/release/tsconfig.json
  tools/release/utils/channel.ts
  tools/release/utils/cmd.ts
  tools/release/utils/flags-config.ts
  tools/release/utils/git.ts
  tools/release/utils/json-file.ts
  tools/release/utils/package.ts
  tools/release/utils/parse-args.ts
  tools/release/utils/write.ts
Labels: :dart: canary, :label: chore

#10353 chore: rename to example-app-ember
  pnpm-lock.yaml
  tests/example-app-ember/README.md
  tests/example-app-ember/app/adapters/application.js
  tests/example-app-ember/app/app.ts
  tests/example-app-ember/app/components/.gitkeep
  tests/example-app-ember/app/components/book-list.hbs
  tests/example-app-ember/app/components/book-list.ts
  tests/example-app-ember/app/components/book-search.hbs
  tests/example-app-ember/app/components/book-search.ts
  tests/example-app-ember/app/components/infinite-books.hbs
  tests/example-app-ember/app/components/infinite-books.ts
  tests/example-app-ember/app/components/legacy-infinite-books.hbs
  tests/example-app-ember/app/components/legacy-infinite-books.ts
  tests/example-app-ember/app/components/page-link.hbs
  tests/example-app-ember/app/config/environment.d.ts
  tests/example-app-ember/app/helpers/.gitkeep
  tests/example-app-ember/app/helpers/add.ts
  tests/example-app-ember/app/helpers/and.ts
  tests/example-app-ember/app/helpers/eq.ts
  tests/example-app-ember/app/helpers/gt.ts
  tests/example-app-ember/app/helpers/lt.ts
  tests/example-app-ember/app/helpers/mod.ts
  tests/example-app-ember/app/helpers/neq.ts
  tests/example-app-ember/app/helpers/not.ts
  tests/example-app-ember/app/helpers/or.ts
  tests/example-app-ember/app/helpers/sub.ts
  tests/example-app-ember/app/index.html
  tests/example-app-ember/app/models/.gitkeep
  tests/example-app-ember/app/models/author.ts
  tests/example-app-ember/app/models/book.ts
  tests/example-app-ember/app/models/genre.ts
  tests/example-app-ember/app/resolver.ts
  tests/example-app-ember/app/router.ts
  tests/example-app-ember/app/routes/.gitkeep
  tests/example-app-ember/app/routes/application.ts
  tests/example-app-ember/app/services/request-manager.ts
  tests/example-app-ember/app/services/store.ts
  tests/example-app-ember/app/styles/app.css
  tests/example-app-ember/app/templates/.gitkeep
  tests/example-app-ember/app/templates/application.hbs
  tests/example-app-ember/app/utils/pagination-links.ts
  tests/example-app-ember/config/environment.js
  tests/example-app-ember/config/optional-features.json
  tests/example-app-ember/config/targets.js
  tests/example-app-ember/ember-cli-build.js
  tests/example-app-ember/eslint.config.mjs
  tests/example-app-ember/package.json
  tests/example-app-ember/server/index.js
  tests/example-app-ember/server/mocks/MOCK_DATA.json
  tests/example-app-ember/server/mocks/book.js
  tests/example-app-ember/testem.js
  tests/example-app-ember/tests/.gitkeep
  tests/example-app-ember/tests/index.html
  tests/example-app-ember/tests/test-helper.js
  tests/example-app-ember/tsconfig.json
  tests/example-app-ember/workers/ember-data-cache-worker.ts
Labels: :dart: canary, :label: chore

#10357 feat: useRecommendedStore for quickly scaffolding a store with configured defaults
  guides/configuration/index.md
  tests/example-app-ember/app/services/store.ts
  warp-drive-packages/core/src/index.ts
Labels: :dart: canary, :label: chore
