Repository warp-drive-data/warp-drive, pull requests merged in 2025-03, with the labels that each got.

#9704 internal: fixup diagnostic reporting
  packages/diagnostic/server/bun/socket-handler.js
  packages/diagnostic/server/reporters/default.js
  packages/diagnostic/src/internals/run.ts
Labels: :dart: canary, :label: chore

#9699 chore: update to pnpm 10
  .npmrc
  config/package.json
  package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/active-record/src/-private/builders/query.ts
  packages/adapter/package.json
  packages/build-config/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/diagnostic/src/ember.ts
  packages/diagnostic/vite.config.mjs
  packages/ember/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/json-api/src/-private/builders/query.ts
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/request/src/-private/context.ts
  packages/rest/package.json
  packages/rest/src/-private/builders/query.ts
  packages/schema-record/package.json
  packages/schema/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/store/src/-private/store-service.ts
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  patches/pnpm-sync-dependencies-meta-injected.patch
  pnpm-lock.yaml
  scripts/fix-dep-configuration.mjs
  scripts/validate-deps.js
  tests/blueprints/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/docs/fixtures/expected.js
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/performance/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema/package.json
Labels: :dart: canary, :label: chore

#9707 chore: Modernize Performance App (use Vite)
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  pnpm-lock.yaml
  tests/performance/app/adapters/application.js
  tests/performance/app/app.js
  tests/performance/app/config/environment.js
  tests/performance/app/resolver.js
  tests/performance/app/routes/basic-record-materialization.js
  tests/performance/app/routes/destroy.js
  tests/performance/app/routes/relationship-materialization-simple.js
  tests/performance/app/serializers/application.js
  tests/performance/app/services/store.ts
  tests/performance/app/styles/app.css
  tests/performance/babel.config.cjs
  tests/performance/config/environment.js
  tests/performance/config/optional-features.json
  tests/performance/ember-cli-build.js
  tests/performance/index.html
  tests/performance/package.json
  tests/performance/server/index.js
  tests/performance/server/index.ts
  tests/performance/server/tsconfig.json
  tests/performance/tests/index.html
  tests/performance/tsconfig.json
  tests/performance/vite.config.mjs
Labels: :dart: canary, :label: chore, ci-perf

#9744 chore: fixup vite config for perf
  tests/performance/vite.config.mjs
Labels: :dart: canary, :label: chore, ci-perf

#9745 feat: new perf scenario for complex records
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
  tests/performance/app/mixins/README.md
  tests/performance/app/mixins/record-mixin-a.js
  tests/performance/app/mixins/record-mixin-b.js
  tests/performance/app/mixins/record-mixin-c.js
  tests/performance/app/mixins/record-mixin-d.js
  tests/performance/app/mixins/record-mixin-e.js
  tests/performance/app/mixins/record-mixin-f.js
  tests/performance/app/mixins/record-mixin-g.js
  tests/performance/app/mixins/record-mixin-h.js
  tests/performance/app/mixins/record-mixin-i.js
  tests/performance/app/mixins/record-mixin-j.js
  tests/performance/app/models/complex-record-a.js
  tests/performance/app/models/complex-record-b.js
  tests/performance/app/models/complex-record-c.js
  tests/performance/app/models/complex-record-d.js
  tests/performance/app/models/complex-record-e.js
  tests/performance/app/models/complex-record-f.js
  tests/performance/app/models/complex-record-g.js
  tests/performance/app/models/complex-record-h.js
  tests/performance/app/models/complex-record-i.js
  tests/performance/app/models/complex-record-j.js
  tests/performance/app/router.js
  tests/performance/app/routes/complex-record-materialization-with-relationship-materialization.js
  tests/performance/app/routes/complex-record-materialization.js
  tests/performance/fixtures/create-complex-payload.ts
  tests/performance/fixtures/generated/complex-record-materialization.json.br
  tests/performance/fixtures/index.js
Labels: :dart: canary, :label: chore, ci-perf

#9748 Actually add the m2m test case to the perf test output
  .github/workflows/perf-check.yml
  .github/workflows/perf-over-release.yml
Labels: :dart: canary, :label: perf, ci-perf

#9749 chore: update perf suite
  package.json
  packages/build-config/src/debugging.ts
  tests/docs/fixtures/expected.js
  tests/performance/app/routes/update-with-same-state-m2m.js
  tests/performance/ember-cli-build.js
  tests/performance/fixtures/index.js
  tests/performance/vite.config.mjs
Labels: :dart: canary, :label: chore

#9750 FIX: Add request-utils/deprecation-support import to ember-data initializer
  packages/-ember-data/app/initializers/ember-data.js
Labels: :dart: canary, :label: bug

#9702 Don't overnotify for updates to added state that match local updates
  packages/graph/src/-private/-diff.ts
  packages/graph/src/-private/operations/replace-related-records.ts
Labels: :dart: canary, :label: bug, :label: perf, ci-perf

#9753 chore: More upgrades to monorepo tooling
  internal-tooling/.gitignore
  internal-tooling/README.md
  internal-tooling/package.json
  internal-tooling/src/-utils.ts
  internal-tooling/src/sync-references.ts
  packages/codemods/package.json
  packages/schema/package.json
  warp-drive-packages/core/README.md
Labels: :dart: canary, :label: chore

#9758 chore: update contributing docs
  contributing/become-a-contributor.md
  contributing/key-concepts.md
  contributing/linking-to-applications.md
  contributing/rfc-process.md
  contributing/setting-up-the-project.md
  contributing/submitting-prs.md
  packages/holodeck/server/index.js
Labels: :dart: canary, :label: chore

#9759 chore: Improve contributing experience
  .npmrc
  contributing/setting-up-the-project.md
  internal-tooling/README.md
  internal-tooling/package.json
  internal-tooling/src/sync-all.ts
  internal-tooling/src/sync-licence.ts
  internal-tooling/src/sync-logos.ts
  internal-tooling/src/sync-references.ts
  internal-tooling/src/sync-scripts.ts
  internal-tooling/src/tasks/-utils.ts
  internal-tooling/src/tasks/sync-all.ts
  internal-tooling/src/tasks/sync-license.ts
  internal-tooling/src/tasks/sync-logos.ts
  internal-tooling/src/tasks/sync-references.ts
  internal-tooling/src/tasks/sync-scripts.ts
  package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/build-config/package.json
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/eslint-plugin-warp-drive/package.json
  packages/experiments/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/main/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  turbo.json
Labels: :dart: canary, :label: chore

#9761 chore: reduce simple Map/Set ops
  packages/build-config/src/debugging.ts
  packages/graph/src/-private/graph.ts
  packages/json-api/src/-private/cache.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/store-service.ts
  tests/performance/app/app.js
  tests/performance/ember-cli-build.js
Labels: :dart: canary, :label: chore, ci-perf

#9762 perf: faster iteration of relationship payloads
  packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: perf, ci-perf

#9763 chore: restructure SchemaRecord test file layout to make it easier to navigate
  tests/warp-drive__schema-record/tests/legacy/basic-fields-create-test.ts
  tests/warp-drive__schema-record/tests/legacy/basic-fields-reactivity-test.ts
  tests/warp-drive__schema-record/tests/legacy/basic-fields-read-test.ts
  tests/warp-drive__schema-record/tests/legacy/legacy-mode-activation-test.ts
  tests/warp-drive__schema-record/tests/legacy/relationships-create-test.ts
  tests/warp-drive__schema-record/tests/legacy/relationships-edit-test.ts
  tests/warp-drive__schema-record/tests/legacy/relationships-reactivity-test.ts
  tests/warp-drive__schema-record/tests/legacy/relationships-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/alias-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/array-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/array-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/array-field-write-test.ts
  tests/warp-drive__schema-record/tests/polaris/basic-fields-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/basic-fields-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/belongs-to-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/derivation-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/derivation-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/has-many-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/object-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/object-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/object-field-write-test.ts
  tests/warp-drive__schema-record/tests/polaris/resource-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/resource-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-array-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-array-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-array-field-write-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-object-field-write-test.ts
Labels: :dart: canary, :label: chore

#9764 docs: LinksMode and Polymorphic Relationship Guide, stubs out guide for LegacyMode vs PolarisMode
  guides/index.md
  guides/reactive-data/index.md
  guides/reactive-data/legacy/overview.md
  guides/reactive-data/polaris/overview.md
  guides/relationships/features/links-mode.md
  guides/relationships/features/polymorphism.md
  guides/relationships/index.md
Labels: :dart: canary, :label: doc

#9766 feat: improve debuggability of SchemaRecord, RecordArray and Identifier
  guides/relationships/features/links-mode.md
  guides/relationships/features/polymorphism.md
  packages/core-types/src/identifier.ts
  packages/schema-record/src/-private/record.ts
  packages/store/src/-private/caches/identifier-cache.ts
  packages/store/src/-private/record-arrays/identifier-array.ts
  pnpm-lock.yaml
  tests/example-json-api/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: feat

#9767 feat: persist runtime config
  packages/build-config/src/runtime.ts
Labels: :dart: canary, :label: feat

#9765 Don't set isDirty to true in diff callbacks
  packages/graph/src/-private/operations/replace-related-records.ts
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/ember-data__graph/tests/test-helper.ts
Labels: :dart: canary, :label: perf, ci-perf

#9768 feat: ensure objects behave amazeballs
  internal-tooling/src/tasks/sync-scripts.ts
  packages/schema-record/src/-private/fields/managed-object.ts
  packages/schema-record/src/-private/record.ts
  packages/schema-record/src/-private/schema.ts
  tests/warp-drive__schema-record/package.json
  tests/warp-drive__schema-record/tests/legacy/legacy-mode-activation-test.ts
  tests/warp-drive__schema-record/tests/polaris/managed-array-iterable-test.ts
  tests/warp-drive__schema-record/tests/polaris/object-iterable-test.gts
  tests/warp-drive__schema-record/tests/polaris/record-array-iterable-test.ts
  tests/warp-drive__schema-record/tests/polaris/record-iterable-test.gts
  tests/warp-drive__schema-record/tests/polaris/schema-array-iterable-test.ts
Labels: :dart: canary, :label: feat

#9770 Widen Peer Range for ember-inflector
  packages/request-utils/package.json
Labels: :dart: canary, :label: chore

#9769 chore: remove restriction on new field kinds being used with legacy mode
  packages/core-types/src/schema/fields.ts
  packages/core-types/src/schema/fields.type-test.ts
  packages/json-api/src/-private/cache.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-data-fetch.ts
  packages/legacy-compat/src/legacy-network-handler/legacy-network-handler.ts
  packages/legacy-compat/src/legacy-network-handler/minimum-adapter-interface.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot.ts
  packages/model/src/-private/debug/assert-polymorphic-type.ts
  packages/model/src/-private/model.ts
  packages/model/src/-private/model.type-test.ts
  packages/model/src/-private/notify-changes.ts
  packages/model/src/-private/schema-provider.ts
  packages/schema-record/src/-private/record.ts
  packages/schema-record/src/-private/schema.ts
  packages/store/src/-private/caches/instance-cache.ts
  packages/store/src/-private/legacy-model-support/shim-model-class.ts
  packages/store/src/-types/q/ds-model.ts
  packages/store/src/-types/q/schema-service.ts
  tests/docs/fixtures/expected.js
  tests/ember-data__json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/ember-data__json-api/tests/integration/serialize-test.ts
  tests/ember-data__json-api/tests/utils/schema.ts
  tests/ember-data__model/tests/integration/model-for-test.ts
  tests/ember-data__model/tests/utils/schema.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
  tests/main/tests/unit/custom-class-support/custom-class-model-test.ts
  tests/main/tests/utils/schema.ts
  tests/warp-drive__schema-record/tests/legacy/legacy-mode-activation-test.ts
  tests/warp-drive__schema-record/tests/polaris/alias-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/resource-field-reactivity-test.ts
  tests/warp-drive__schema-record/tests/polaris/resource-field-read-test.ts
Labels: :dart: canary, :label: feat

#9773 chore: cleanup @ember/service deprecation from shipped library code
  packages/adapter/src/index.ts
  packages/debug/src/data-adapter.ts
  packages/serializer/src/index.ts
Labels: :dart: canary, :label: bug

#9771 fix: better reordering detection when remoteClearsLocal is true
  packages/build-config/vite.config.mjs
  packages/core-types/src/-private.ts
  packages/core-types/src/runtime.ts
  packages/core-types/vite.config.mjs
  packages/graph/src/-private/-diff.ts
  packages/request/src/index.ts
  packages/store/src/-private/managers/notification-manager.ts
  packages/store/src/-private/store-service.ts
  packages/unpublished-test-infra/src/test-support/asserts/assert-notification.ts
  packages/unpublished-test-infra/src/test-support/asserts/index.ts
  tests/ember-data__graph/ember-cli-build.js
  tests/ember-data__graph/tests/integration/graph/diff-preservation-test.ts
  tests/warp-drive__schema-record/tests/polaris/basic-fields-field-read-test.ts
Labels: :dart: canary, :label: perf

#9778 chore: improve contributing guidance for api documentation
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  contributing/become-a-contributor.md
  contributing/writing-api-docs.md
  packages/core-types/src/schema/fields.ts
  packages/experiments/src/persisted-cache/cache.ts
Labels: :dart: canary, :label: doc

#9779 chore: cleanup deprecations
  guides/requests/examples/1-auth.md
  pnpm-lock.yaml
  tests/ember-data__request/tests/integration/service-test.ts
  tests/fastboot/app/routes/index.ts
  tests/fastboot/app/routes/person/new.js
  tests/main/app/route.ts
  tests/main/app/routes/application.ts
  tests/main/ember-cli-build.js
  tests/main/package.json
  tests/main/tests/acceptance/relationships/has-many-test.js
  tests/main/tests/acceptance/relationships/tracking-record-state-test.js
  tests/main/tests/acceptance/tracking-create-record-test.js
  tests/main/tests/integration/application-test.js
  tests/main/tests/integration/cache-handler/store-package-setup-test.ts
  tests/main/tests/integration/store-extension-test.ts
  tests/main/tests/integration/store/model-name-test.js
  tests/performance/app/routes/add-children-then-materialize.js
  tests/performance/app/routes/add-children-to-materialized.js
  tests/performance/app/routes/add-children.js
  tests/performance/app/routes/destroy.js
  tests/performance/app/routes/relationship-materialization-complex.js
  tests/performance/app/routes/relationship-materialization-simple.js
  tests/performance/app/routes/unload-all.js
  tests/performance/app/routes/unload.js
  tests/performance/app/routes/unused-relationships.js
  tests/performance/app/routes/update-with-same-state-m2m.js
  tests/performance/app/routes/update-with-same-state.js
Labels: :dart: canary, :label: chore

#9777 docs: update overviews with recent library improvements
  .github/workflows/main.yml
  README.md
  contributing/writing-api-docs.md
  docs-generator/yuidoc.json
  docs-viewer/src/-utils.ts
  docs-viewer/src/preview-docs.ts
  packages/-ember-data/README.md
  packages/-ember-data/src/index.ts
  packages/build-config/src/-private/utils/features.ts
  packages/build-config/src/canary-features.ts
  packages/build-config/src/debugging.ts
  packages/build-config/src/deprecation-versions.ts
  packages/build-config/src/index.ts
  packages/ember/src/-private/await.gts
  packages/ember/src/-private/promise-state.ts
  packages/ember/src/-private/request-state.ts
  packages/ember/src/-private/request.gts
  packages/ember/src/index.ts
  packages/schema-record/src/-private/schema.ts
  packages/schema-record/src/index.ts
  tests/docs/fixtures/expected.js
  turbo.json
Labels: :dart: canary, :label: doc

#9781 docs: improve schema-record documentation
  packages/core-types/src/schema/fields.ts
  packages/schema-record/README.md
  packages/schema-record/src/index.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: doc

#9782 chore: add class coverage to docs tests
  tests/docs/fixtures/expected.js
  tests/docs/index.js
Labels: :dart: canary, :label: chore

#9783 docs: expand field docs
  packages/core-types/src/schema/fields.ts
  packages/schema-record/src/index.ts
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: doc

#9785 Handle case when sessionStorage is blocked
  packages/core-types/src/runtime.ts
Labels: :dart: canary, :label: bug

#9787 chore: adjust renovate config to attempt smoother upgrades
  .github/renovate.json
Labels: :dart: canary, :label: chore

#9780 chore: bump @glimmer/component
  package.json
  packages/-ember-data/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/eslint.config.mjs
  packages/ember/package.json
  packages/ember/src/-private/await.gts
  packages/ember/src/-private/request.gts
  packages/ember/vite.config.mjs
  packages/experiments/package.json
  packages/graph/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  tests/blueprints/package.json
  tests/builders/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/app/routes/index.ts
  tests/fastboot/app/templates/index.hbs
  tests/fastboot/package.json
  tests/fastboot/tests/fastboot/index-test.js
  tests/full-data-asset-size-app/package.json
  tests/main/config/ember-try.js
  tests/main/package.json
  tests/performance/package.json
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/native-types/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :dart: canary, :label: chore

#9819 chore: update test-waiters to v4
  package.json
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  patches/ember-source@3.28.12.patch
  patches/ember-source@4.4.5.patch
  pnpm-lock.yaml
  tests/blueprints/package.json
  tests/builders/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/config/ember-try.js
  tests/main/package.json
  tests/performance/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/package.json
Labels: :label: dependencies, :dart: canary

#9825 chore: cleanup new docs
  packages/-ember-data/src/index.ts
Labels: :dart: canary, :label: doc

#9844 chore: remove @types/eslint__js
  pnpm-lock.yaml
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/native-types/package.json
  tests/vite-basic-compat/package.json
Labels: :label: dependencies, :dart: canary, :label: chore

#9874 chore: automated maintenance of the README tables
  .github/workflows/main.yml
  README.md
  internal-tooling/package.json
  internal-tooling/src/sync-readme-tables.ts
  internal-tooling/src/tasks/-data/compatibility.ts
  internal-tooling/src/tasks/-data/versions.ts
  internal-tooling/src/tasks/sync-license.ts
  internal-tooling/src/tasks/sync-logos.ts
  internal-tooling/src/tasks/sync-readme-tables.ts
  internal-tooling/src/tasks/sync-references.ts
  internal-tooling/src/tasks/sync-scripts.ts
  tests/main/config/ember-try.js
Labels: :dart: canary, :label: chore

#9873 chore: migrate pnpm setting
  package.json
Labels: :dart: canary, :label: chore

#9885 fix: make warnMessageNoModelForKey safe in prod
  packages/serializer/src/rest.js
Labels: :dart: canary, :label: bug
