Repository warp-drive-data/warp-drive, pull requests merged in 2025-01, with the labels that each got.

#9629 fix: restore * versions and setup publish to not overwrite them
  .github/actions/setup/action.yml
  .github/workflows/main.yml
  config/package.json
  package.json
  packages/-ember-data/package.json
  packages/-warp-drive/package.json
  packages/active-record/package.json
  packages/adapter/package.json
  packages/build-config/package.json
  packages/build-config/src/-private/utils/deprecations.ts
  packages/build-config/src/deprecation-versions.ts
  packages/build-config/src/deprecations.ts
  packages/codemods/package.json
  packages/core-types/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/eslint-plugin-warp-drive/package.json
  packages/experiments/package.json
  packages/graph/package.json
  packages/holodeck/package.json
  packages/json-api/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/request-utils/package.json
  packages/request/package.json
  packages/rest/package.json
  packages/schema-record/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
  release/core/publish/steps/bump-versions.ts
  tests/blueprints/package.json
  tests/builders/package.json
  tests/codemods/package.json
  tests/docs/fixtures/expected.js
  tests/docs/package.json
  tests/ember-data__adapter/package.json
  tests/ember-data__graph/package.json
  tests/ember-data__json-api/package.json
  tests/ember-data__model/package.json
  tests/ember-data__request/package.json
  tests/ember-data__serializer/package.json
  tests/embroider-basic-compat/ember-cli-build.js
  tests/embroider-basic-compat/package.json
  tests/example-json-api/package.json
  tests/fastboot/package.json
  tests/full-data-asset-size-app/package.json
  tests/main/package.json
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/performance/package.json
  tests/vite-basic-compat/package.json
  tests/warp-drive__ember/package.json
  tests/warp-drive__experiments/package.json
  tests/warp-drive__schema-record/eslint.config.mjs
  tests/warp-drive__schema-record/package.json
  turbo.json
Labels: :dart: canary, :label: chore

#9637 fix: ensure v5 deprecations are resolvable
  packages/build-config/src/-private/utils/deprecations.ts
Labels: :dart: canary, :label: bug

#9633 Add smoke-tests for types, build, etc
  .github/renovate.json
  .github/workflows/compat-tests.yml
  packages/codemods/utils/logger.ts
  packages/ember/package.json
  release/core/publish/steps/generate-tarballs.ts
  release/utils/package.ts
  tests/smoke-tests/.gitignore
  tests/smoke-tests/README.md
  tests/smoke-tests/dt-types/app/type-tests.ts
  tests/smoke-tests/dt-types/package.json
  tests/smoke-tests/dt-types/tsconfig.json
  tests/smoke-tests/dt-types/types/ember-data/types/registries/model.d.ts
  tests/smoke-tests/dt-types/types/index.d.ts
  tests/smoke-tests/helpers.ts
  tests/smoke-tests/native-types/.editorconfig
  tests/smoke-tests/native-types/app/type-tests.ts
  tests/smoke-tests/native-types/package.json
  tests/smoke-tests/native-types/tsconfig.json
  tests/smoke-tests/native-types/types/index.d.ts
  tests/smoke-tests/prepare.ts
  tests/smoke-tests/run.ts
  tests/smoke-tests/tsconfig.json
  tests/warp-drive__experiments/package.json
Labels: :dart: canary, :label: bug

#9645 chore: misc updates to TS guide
  guides/typescript/0-installation.md
  guides/typescript/1-configuration.md
  guides/typescript/index.md
Labels: :dart: canary, :label: doc

#9646 docs: two-store migration approach
  guides/index.md
  guides/migrating/two-store-migration.md
  guides/typescript/0-installation.md
Labels: :dart: canary, :label: doc

#9638 chore: make tests more splittable
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-1-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-10-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-11-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-12-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-13-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-14-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-15-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-16-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-17-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-18-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-19-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-2-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-20-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-3-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-4-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-5-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-6-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-7-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-8-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-partition-9-test.ts
  tests/main/tests/integration/relationships/collection/mutating-has-many-test-infra.ts
Labels: :dart: canary, :label: chore
