Repository warp-drive-data/warp-drive, pull requests merged in 2025-05, with the labels that each got.

#9971 docs: add more documentation and type utils around LegacyMode and potential migration paths
  guides/reactive-data/legacy/overview.md
  packages/model/README.md
  packages/model/src/migration-support.ts
  packages/model/src/migration-support.type-test.ts
  packages/schema-record/README.md
  tests/docs/fixtures/expected.js
Labels: :dart: canary, :label: feat, :label: doc

#9882 Add tests for deleteRecord, unloadRecord, destoryRecord
  tests/warp-drive__schema-record/tests/polaris/schema-record-delete-test.ts
Labels: :dart: canary, :label: test

#9975 types: fixup PolarisMode schema types to check better
  config/eslint/typescript.js
  contributing/writing-api-docs.md
  docs-viewer/src/-utils.ts
  docs-viewer/src/preview-docs.ts
  docs-viewer/tsconfig.json
  packages/adapter/src/index.ts
  packages/adapter/src/json-api.ts
  packages/adapter/src/rest.ts
  packages/build-config/src/canary-features.ts
  packages/build-config/src/debugging.ts
  packages/build-config/src/deprecation-versions.ts
  packages/core-types/src/cache.ts
  packages/core-types/src/identifier.ts
  packages/core-types/src/record.ts
  packages/core-types/src/schema/fields.ts
  packages/core-types/src/schema/fields.type-test.ts
  packages/diagnostic/src/-ember/is-component.ts
  packages/eslint-plugin-warp-drive/src/rules/no-create-record-rerender.js
  packages/experiments/src/persisted-cache/cache.ts
  packages/json-api/src/-private/builders/-utils.ts
  packages/json-api/src/-private/cache.ts
  packages/json-api/src/-private/serialize.ts
  packages/legacy-compat/src/builders/find-all.ts
  packages/legacy-compat/src/builders/query.ts
  packages/legacy-compat/src/builders/save-record.ts
  packages/legacy-compat/src/legacy-network-handler/minimum-adapter-interface.ts
  packages/legacy-compat/src/legacy-network-handler/minimum-serializer-interface.ts
  packages/legacy-compat/src/legacy-network-handler/snapshot-record-array.ts
  packages/legacy-compat/src/utils.ts
  packages/model/src/-private/belongs-to.ts
  packages/model/src/-private/errors.ts
  packages/model/src/-private/has-many.ts
  packages/model/src/-private/promise-many-array.ts
  packages/model/src/-private/references/belongs-to.ts
  packages/model/src/-private/references/has-many.ts
  packages/model/src/migration-support.ts
  packages/request-utils/src/index.ts
  packages/request/src/-private/types.ts
  packages/schema-record/README.md
  packages/schema-record/src/-private/schema.ts
  packages/schema-record/src/index.ts
  packages/serializer/src/json.js
  packages/store/src/-private/cache-handler/types.ts
  packages/store/src/-private/document.ts
  packages/store/src/-private/managers/cache-manager.ts
  packages/store/src/-private/record-arrays/many-array.ts
  packages/store/src/-private/store-service.ts
  packages/store/src/-types/q/cache-capabilities-manager.ts
  packages/store/src/-types/q/schema-service.ts
  tests/main/tests/utils/schema.ts
  tests/warp-drive__schema-record/tests/legacy/relationships-create-test.ts
  tests/warp-drive__schema-record/tests/polaris/belongs-to-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/derivation-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/has-many-field-read-test.ts
  tests/warp-drive__schema-record/tests/polaris/schema-record-delete-test.ts
Labels: :dart: canary, :label: doc, typescript

#9976 docs: add more to the debugging guide
  packages/build-config/src/debugging.ts
  packages/build-config/src/index.ts
Labels: :dart: canary, :label: doc

#9977 feat: AutoCompress handler
  packages/core-types/src/request.ts
  packages/request-utils/package.json
  packages/request-utils/src/-private/handlers/auto-compress.ts
  packages/request-utils/src/handlers.ts
  packages/request-utils/tsconfig.json
  packages/request-utils/vite.config.mjs
  packages/request/src/-private/debug.ts
  pnpm-lock.yaml
  tests/docs/fixtures/expected.js
  tests/ember-data__request/package.json
  tests/ember-data__request/tests/request-utils/handlers/auto-compress-test.ts
  tests/ember-data__request/tests/test-helper.ts
Labels: :dart: canary, :label: feat

#9978 feat: constraints based CachePolicy features
  packages/build-config/src/debugging.ts
  packages/request-utils/src/index.ts
  tests/docs/fixtures/expected.js
  tests/warp-drive__ember/tests/integration/request-component-invalidation-test.gts
Labels: :dart: canary, :label: feat

#9980 docs: port vitepress site into the monorepo for versioned deploys
  .gitignore
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
  docs-viewer/docs.warp-drive.io/api-examples.md
  docs-viewer/docs.warp-drive.io/index.md
  docs-viewer/docs.warp-drive.io/markdown-examples.md
  docs-viewer/docs.warp-drive.io/public/logos/NCC-1701-a-blue.svg
  docs-viewer/docs.warp-drive.io/public/logos/NCC-1701-a-gold.svg
  docs-viewer/docs.warp-drive.io/public/logos/NCC-1701-a-gold_100.svg
  docs-viewer/docs.warp-drive.io/public/logos/NCC-1701-a-gold_base-64.txt
  docs-viewer/docs.warp-drive.io/public/logos/NCC-1701-a.svg
  docs-viewer/docs.warp-drive.io/public/logos/docs-badge.svg
  docs-viewer/docs.warp-drive.io/public/logos/ember-data-logo-dark.svg
  docs-viewer/docs.warp-drive.io/public/logos/ember-data-logo-light.svg
  docs-viewer/docs.warp-drive.io/public/logos/github-header.svg
  docs-viewer/docs.warp-drive.io/public/logos/social1.png
  docs-viewer/docs.warp-drive.io/public/logos/social2.png
  docs-viewer/docs.warp-drive.io/public/logos/warp-drive-logo-dark.svg
  docs-viewer/docs.warp-drive.io/public/logos/warp-drive-logo-gold.svg
  docs-viewer/package.json
  docs-viewer/src/prepare-website.ts
  docs-viewer/src/preview-ember-docs.ts
  docs-viewer/src/rebuild-ember-docs.ts
  pnpm-lock.yaml
Labels: :dart: canary, :label: doc

#9981 docs: programatically build guides nav, begin work on api doc extraction
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
  docs-viewer/package.json
  docs-viewer/src/site-utils.ts
  docs-viewer/typedoc.json
  pnpm-lock.yaml
Labels: :dart: canary, :label: doc

#9982 fix: simplify peer configuration to avoid bringing extra copies of glimmer/validator
  packages/-ember-data/package.json
  packages/adapter/package.json
  packages/debug/package.json
  packages/diagnostic/package.json
  packages/ember/package.json
  packages/legacy-compat/package.json
  packages/model/package.json
  packages/serializer/package.json
  packages/store/package.json
  packages/tracking/package.json
  packages/unpublished-test-infra/package.json
  pnpm-lock.yaml
Labels: :dart: canary, :label: bug

#9984 chore: add social graph content to docs site for sharing
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
Labels: :dart: canary, :label: doc

#9987 docs: add more to the setup guide, add group icons and llm files, add ability to use ResourceKey and RequestKey as types
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
  docs-viewer/docs.warp-drive.io/.vitepress/theme/index.js
  docs-viewer/package.json
  guides/1-configuration/1-overview.md
  guides/1-configuration/2-setup/1-universal.md
  package.json
  packages/core-types/src/identifier.ts
  packages/core-types/src/index.ts
  pnpm-lock.yaml
  tests/warp-drive__schema-record/app/services/store.ts
Labels: :dart: canary, :label: doc

#9993 chore: prepare more infra for @warp-drive/core package
  docs-viewer/package.json
  internal-tooling/package.json
  internal-tooling/src/tasks/sync-license.ts
  internal-tooling/src/tasks/sync-logos.ts
  packages/build-config/cjs-src/transforms/babel-plugin-transform-asserts.js
  packages/build-config/cjs-src/transforms/babel-plugin-transform-deprecations.js
  packages/build-config/cjs-src/transforms/babel-plugin-transform-features.js
  packages/build-config/cjs-src/transforms/babel-plugin-transform-logging.js
  packages/build-config/src/babel-macros.ts
  packages/build-config/src/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  release/strategy.json
  tsconfig.json
  warp-drive-packages/core/package.json
Labels: :dart: canary, :label: chore

#9995 docs: add docs for Checkout, instantiateRecord, teardownRecorod
  packages/schema-record/README.md
  packages/schema-record/src/-private/record.ts
  packages/store/src/-private/store-service.ts
Labels: :dart: canary, :label: doc

#9996 docs: caching guide
  guides/3-caching.md
  guides/5-caching.md
  guides/images/caching-dark-1.png
  guides/images/caching-dark.png
  guides/images/caching-light.png
Labels: :dart: canary, :label: doc

#9999 docs(concepts/requests): fix glimmer-ts code example
  guides/concepts/requests.md
Labels: :dart: canary, :label: doc

#10004 feat: @warp-drive/ember
  guides/1-configuration/2-setup/1-universal.md
  packages/tracking/src/index.ts
  pnpm-lock.yaml
  tests/builders/tsconfig.json
  tests/ember-data__adapter/tsconfig.json
  tests/ember-data__graph/tsconfig.json
  tests/ember-data__json-api/tsconfig.json
  tests/ember-data__model/tsconfig.json
  tests/ember-data__serializer/tsconfig.json
  tests/embroider-basic-compat/tsconfig.json
  tests/example-json-api/tsconfig.json
  tests/fastboot/tsconfig.json
  tests/main/tsconfig.json
  tests/performance/tsconfig.json
  tests/vite-basic-compat/tsconfig.json
  tests/warp-drive__ember/tsconfig.json
  tests/warp-drive__experiments/tsconfig.json
  tests/warp-drive__schema-record/tsconfig.json
  tsconfig.json
  warp-drive-packages/ember/CHANGELOG.md
  warp-drive-packages/ember/LICENSE.md
  warp-drive-packages/ember/README.md
  warp-drive-packages/ember/addon-main.cjs
  warp-drive-packages/ember/babel.config.mjs
  warp-drive-packages/ember/eslint.config.mjs
  warp-drive-packages/ember/logos/NCC-1701-a-blue.svg
  warp-drive-packages/ember/logos/NCC-1701-a-gold.svg
  warp-drive-packages/ember/logos/NCC-1701-a-gold_100.svg
  warp-drive-packages/ember/logos/NCC-1701-a-gold_base-64.txt
  warp-drive-packages/ember/logos/NCC-1701-a.svg
  warp-drive-packages/ember/logos/README.md
  warp-drive-packages/ember/logos/docs-badge.svg
  warp-drive-packages/ember/logos/ember-data-logo-dark.svg
  warp-drive-packages/ember/logos/ember-data-logo-light.svg
  warp-drive-packages/ember/logos/github-header.svg
  warp-drive-packages/ember/logos/social1.png
  warp-drive-packages/ember/logos/social2.png
  warp-drive-packages/ember/logos/warp-drive-logo-dark.svg
  warp-drive-packages/ember/logos/warp-drive-logo-gold.svg
  warp-drive-packages/ember/package.json
  warp-drive-packages/ember/src/-private/await.gts
  warp-drive-packages/ember/src/-private/request.gts
  warp-drive-packages/ember/src/.gitkeep
  warp-drive-packages/ember/src/index.ts
  warp-drive-packages/ember/src/install.ts
  warp-drive-packages/ember/tsconfig.json
  warp-drive-packages/ember/typedoc.config.mjs
  warp-drive-packages/ember/vite.config.mjs
Labels: :dart: canary, :label: feat

#10007 feat: split API Docs in sidebar
  docs-viewer/docs.warp-drive.io/.vitepress/config.mts
  docs-viewer/typedoc.config.mjs
Labels: :dart: canary, :label: doc
