Repository warp-drive-data/warp-drive, pull requests merged in 2025-09, with the labels that each got.

#10362 Fix typo in migration docs
  guides/the-manual/misc/migrating/two-store-migration.md
Labels: :dart: canary, :label: doc

#10365 feat: easier transactional commits
  tests/builders/tests/integration/create-record-test.ts
  tests/builders/tests/integration/delete-record-test.ts
  tests/builders/tests/integration/update-record-test.ts
  tests/main/tests/integration/cache/spec-cache-errors-test.ts
  tests/main/tests/integration/cache/spec-cache-state-test.ts
  tests/main/tests/integration/cache/spec-cache-test.ts
  warp-drive-packages/core/src/store/-private/cache-handler/handler.ts
  warp-drive-packages/core/src/store/-private/managers/cache-manager.ts
  warp-drive-packages/core/src/types/cache.ts
  warp-drive-packages/experiments/src/data-worker/cache-handler.ts
  warp-drive-packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: feat

#10366 feat: make it easier to lookup a possible prior request
  tests/main/tests/integration/records/rematerialize-test.js
  warp-drive-packages/core/src/store/-private/caches/instance-cache.ts
  warp-drive-packages/core/src/store/-private/managers/cache-key-manager.ts
  warp-drive-packages/core/src/store/-private/store-service.ts
  warp-drive-packages/json-api/src/-private/cache.ts
Labels: :dart: canary, :label: feat

#10369 docs: cleanup types for request builders
  warp-drive-packages/core/src/types/spec/document.ts
  warp-drive-packages/utilities/src/-private/active-record/find-record.ts
  warp-drive-packages/utilities/src/-private/active-record/query.ts
  warp-drive-packages/utilities/src/-private/active-record/save-record.ts
  warp-drive-packages/utilities/src/-private/json-api/find-record.ts
  warp-drive-packages/utilities/src/-private/json-api/query.ts
  warp-drive-packages/utilities/src/-private/json-api/save-record.ts
  warp-drive-packages/utilities/src/-private/rest/find-record.ts
  warp-drive-packages/utilities/src/-private/rest/query.ts
  warp-drive-packages/utilities/src/-private/rest/save-record.ts
Labels: :dart: canary, :label: chore

#10370 docs: fixup PromiseState
  specs/src/await-component.spec.ts
  specs/src/get-promise-state.spec.ts
  tests/framework-react/tests/await-component.spec-test.tsx
  warp-drive-packages/core/src/reactive.ts
  warp-drive-packages/core/src/store/-private.ts
  warp-drive-packages/ember/src/-private/await.gts
  warp-drive-packages/ember/src/index.ts
Labels: :dart: canary, :label: chore

#10374 chore: update json-api test suite to use new packages
  pnpm-lock.yaml
  tests/ember-data__json-api/tests/integration/-smoke.ts
  tests/ember-data__json-api/tsconfig.json
  tests/json-api/.mock-cache/546c9e3a/GET::users_1::0/res.body.br
  tests/json-api/.mock-cache/546c9e3a/GET::users_1::0/res.meta.json
  tests/json-api/README.md
  tests/json-api/app/app.ts
  tests/json-api/app/config/environment.d.ts
  tests/json-api/app/index.html
  tests/json-api/app/resolver.ts
  tests/json-api/app/router.ts
  tests/json-api/app/styles/app.css
  tests/json-api/app/templates/.gitkeep
  tests/json-api/app/templates/application.hbs
  tests/json-api/config/environment.js
  tests/json-api/config/optional-features.json
  tests/json-api/config/targets.js
  tests/json-api/diagnostic.js
  tests/json-api/ember-cli-build.js
  tests/json-api/eslint.config.mjs
  tests/json-api/package.json
  tests/json-api/tests/.gitkeep
  tests/json-api/tests/index.html
  tests/json-api/tests/integration/cache/cache.patch-test.ts
  tests/json-api/tests/integration/cache/collection-data-documents-test.ts
  tests/json-api/tests/integration/cache/error-documents-test.ts
  tests/json-api/tests/integration/cache/meta-documents-test.ts
  tests/json-api/tests/integration/cache/resource-data-documents-test.ts
  tests/json-api/tests/integration/cache/validation-errors-test.ts
  tests/json-api/tests/integration/serialize-test.ts
  tests/json-api/tests/test-helper.js
  tests/json-api/tests/utils/schema.ts
  tests/json-api/tsconfig.json
Labels: :dart: canary, :label: chore

#10375 chore: make non-GET holodeck replay work
  packages/holodeck/server/index.js
  packages/holodeck/src/index.ts
  packages/holodeck/src/mock.ts
  tests/json-api/.mock-cache/36ff0af3/POST::api_user_ops_bulk.create::0/f6c45fa65d57493c31a4f1b85eddcf6f.body.br
  tests/json-api/.mock-cache/36ff0af3/POST::api_user_ops_bulk.create::0/f6c45fa65d57493c31a4f1b85eddcf6f.meta.json
  tests/json-api/tests/integration/cache/mutation-request-test.ts
Labels: :dart: canary, :label: chore

#10380 chore: update some broken references in docs
  packages/eslint-plugin-warp-drive/docs/no-invalid-relationships.md
  packages/eslint-plugin-warp-drive/src/rules/no-create-record-rerender.js
  packages/eslint-plugin-warp-drive/src/rules/no-external-request-patterns.js
  packages/eslint-plugin-warp-drive/src/rules/no-invalid-relationships.js
  packages/eslint-plugin-warp-drive/src/rules/no-invalid-resource-ids.js
  packages/eslint-plugin-warp-drive/src/rules/no-invalid-resource-types.js
  packages/eslint-plugin-warp-drive/src/rules/no-legacy-request-patterns.js
  tests/ember-data__graph/README.md
Labels: :dart: canary, :label: doc

#10121 feat: legacy ModelFragments support
  packages/holodeck/src/index.ts
  pnpm-lock.yaml
  tests/legacy/.mock-cache/755b85fa/POST::people::0/62b4aeb1c382e34e9e63d68f1ba5c09a.body.br
  tests/legacy/.mock-cache/755b85fa/POST::people::0/62b4aeb1c382e34e9e63d68f1ba5c09a.meta.json
  tests/legacy/.mock-cache/755b85fa/POST::people::0/7d133e1cf66a7a00d4bb12bd2ba05b89.body.br
  tests/legacy/.mock-cache/755b85fa/POST::people::0/7d133e1cf66a7a00d4bb12bd2ba05b89.meta.json
  tests/legacy/.mock-cache/da547acd/POST::people::0/62b4aeb1c382e34e9e63d68f1ba5c09a.body.br
  tests/legacy/.mock-cache/da547acd/POST::people::0/62b4aeb1c382e34e9e63d68f1ba5c09a.meta.json
  tests/legacy/.mock-cache/da547acd/POST::people::0/7d133e1cf66a7a00d4bb12bd2ba05b89.body.br
  tests/legacy/.mock-cache/da547acd/POST::people::0/7d133e1cf66a7a00d4bb12bd2ba05b89.meta.json
  tests/legacy/.mock-cache/da547acd/POST::people::0/92d1adaddadfe0f1e214dbc766db2d70.body.br
  tests/legacy/.mock-cache/da547acd/POST::people::0/92d1adaddadfe0f1e214dbc766db2d70.meta.json
  tests/legacy/.mock-cache/f6956340/PUT::users_1::0/c64e725be718d96627c539f67da5f894.body.br
  tests/legacy/.mock-cache/f6956340/PUT::users_1::0/c64e725be718d96627c539f67da5f894.meta.json
  tests/legacy/babel.config.mjs
  tests/legacy/diagnostic.js
  tests/legacy/eslint.config.mjs
  tests/legacy/index.html
  tests/legacy/package.json
  tests/legacy/start.ts
  tests/legacy/tests/-test-store/schemas/animal.ts
  tests/legacy/tests/-test-store/schemas/info.ts
  tests/legacy/tests/-test-store/schemas/lion.ts
  tests/legacy/tests/-test-store/schemas/name.ts
  tests/legacy/tests/-test-store/schemas/order.ts
  tests/legacy/tests/-test-store/schemas/passenger.ts
  tests/legacy/tests/-test-store/schemas/person.ts
  tests/legacy/tests/-test-store/schemas/prefix.ts
  tests/legacy/tests/-test-store/schemas/product.ts
  tests/legacy/tests/-test-store/schemas/user.ts
  tests/legacy/tests/-test-store/schemas/vehicle.ts
  tests/legacy/tests/-test-store/schemas/zoo.ts
  tests/legacy/tests/-test-store/store.ts
  tests/legacy/tests/integration/app-test.ts
  tests/legacy/tests/integration/nested-test.ts
  tests/legacy/tests/unit/fragment-array-test.ts
  tests/legacy/tests/unit/fragment-test.ts
  tests/legacy/tests/unit/utilities/with-array-defaults-test.ts
  tests/legacy/tests/unit/utilities/with-fragment-array-defaults-test.ts
  tests/legacy/tests/unit/utilities/with-fragment-defaults-test.ts
  tests/legacy/tsconfig.json
  tests/legacy/vite.config.mjs
  warp-drive-packages/core/src/reactive/-private.ts
  warp-drive-packages/core/src/reactive/-private/record.ts
  warp-drive-packages/legacy/src/index.ts
  warp-drive-packages/legacy/src/model-fragments.ts
  warp-drive-packages/legacy/src/model-fragments/extensions/fragment-array.ts
  warp-drive-packages/legacy/src/model-fragments/extensions/fragment.ts
  warp-drive-packages/legacy/src/model-fragments/hooks/model-for.ts
  warp-drive-packages/legacy/src/model-fragments/index.ts
  warp-drive-packages/legacy/src/model-fragments/instance-initializers/fragment-extensions.ts
  warp-drive-packages/legacy/src/model-fragments/utilities/with-array-defaults.ts
  warp-drive-packages/legacy/src/model-fragments/utilities/with-fragment-array-defaults.ts
  warp-drive-packages/legacy/src/model-fragments/utilities/with-fragment-defaults.ts
  warp-drive-packages/legacy/src/model-fragments/utilities/with-legacy.ts
  warp-drive-packages/legacy/src/model/migration-support.ts
  warp-drive-packages/legacy/vite.config.mjs
Labels: :dart: canary, :label: feat

#10388 Fix validator fields parsing for Nick
  warp-drive-packages/json-api/src/-private/validator/1.1/7.2_resource-objects.ts
  warp-drive-packages/json-api/src/-private/validator/utils.ts
Labels: :dart: canary, :label: bug

#10390 fix: Docs typo
  guides/the-manual/misc/typescript/configuration.md
Labels: :dart: canary, :label: doc

#10400 add(doc): ResourceSchema
  guides/the-manual/schemas/resource-schemas.md
Labels: :dart: canary, :label: doc

#10402 add(doc): ObjectSchema and Fields documentation
  guides/the-manual/schemas/object-schemas.md
  guides/the-manual/schemas/simple-fields.md
Labels: :dart: canary, :label: doc

#10403 chore: add a few more tests for relationships
  tests/core/tests/polaris-mode/has-many-field-read-test.ts
Labels: :dart: canary, :label: chore
